### ISSUE TITLE
ServiceGenerator Error

### ISSUE THREAD

**Issue by andyjslee** [google/google-api-objectivec-client-for-rest#100]
I am trying to run the ServiceGenerator, and get the following error:

GTLRService.h:38:11: 'GTMSessionFetcher.h' file not found

**Comment by thomasvl** [comment]
We're likely going to need more info to help out.  You said _run_, but given the error message, I'm thinking maybe you are trying to build it and the build is failing?  When you download this library, did you do a recursive git clone so you got the SessionFetcher via a submodule?

https://github.com/google/google-api-objectivec-client-for-rest/wiki/ServiceGenerator

**Comment by thomasvl** [comment]
Closing this out since there doesn't seem to be follow up.
