### ISSUE TITLE
iOS Framework issues

### ISSUE THREAD

**Issue by jerryhalstead** [google/google-api-objectivec-client-for-rest#108]
I integrated this into our iOS app as a framework (using for YouTube). A few issues:

GTMAppAuthFetcherAuthorization.h complained that GTMSessionFetcher.h couldn't be found. I resolved by adding this in preprocessor macros:
GTMAPPAUTH_USER_IMPORTS=1

OIDRegistrationRequest.h &  OIDRegistrationResponse.h weren't included in the framework and AppAuth.h tries to import them.

Finally, our app is non-arc (we override files when needed) and we get warnings for the following files/vars of:
"No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed"
"default property attribute 'assign' not appropriate for non-GC object"

GTLRBatchQuery.h
@property(atomic, nullable) NSArray<GTLRQuery *> *queries;  

GTLRService.h
@property(atomic) NSNumber *shouldFetchNextPages;
@property(atomic, getter=isRetryEnabled) NSNumber *retryEnabled;
@property(atomic) NSNumber *maxRetryInterval;

**Comment by thomasvl** [comment]
@WilliamDenniss for the AppAuth issues.

What version of Xcode are you using and compiler settings are you using to get those warnings?  We can see what we can add to our builds to help catch those warnings going forward.

**Comment by jerryhalstead** [comment]
Xcode 8.2.1, which settings are you interested in? 

I also changed the framework's 'build active architecture only' to NO, since our project complained that the framework didn't have the right architecture.

**Comment by thomasvl** [comment]
> Xcode 8.2.1, which settings are you interested in?

clang should kick out the _-Wblahblabh_ at the end of the warnings you mentioned.  Just getting those will let us know what settings came into play.

**Comment by jerryhalstead** [comment]
This one?

In file included from /Users/jhalstead/iPhone/VideoStar/GTLR.framework/Headers/GTLRService.h:22:
/Users/jhalstead/iPhone/VideoStar/GTLR.framework/Headers/GTLRBatchQuery.h:28:1: warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Wobjc-property-no-attribute]
@property(atomic, nullable) NSArray<GTLRQuery *> *queries;

**Comment by thomasvl** [comment]
Yup, thanks.

**Comment by thomasvl** [comment]
I'm not seeing a setting directly related to that, can you double check your project/target settings to figure out what is enabling this?

**Comment by jerryhalstead** [comment]
Sounds like it's something set by xcode itself? (http://stackoverflow.com/questions/22613154/warning-when-omitting-removing-strong-attribute-from-property)

Most likely driven by our non-arc file that is using the framework.

**Comment by thomasvl** [comment]
#109 will fix the warnings from these headers.

**Comment by thomasvl** [comment]
Actually, re the AppAuth headers, it sounds like you might have updated to a newer comment that what the Deps/AppAuth one is pointing at.  If you keep the Deps pointed this repo points at, things should build.

**Comment by jerryhalstead** [comment]
Right, the files are in the checkout, but they weren't in the Build Phases Headers list and so they didn't make it into the framework.

**Comment by thomasvl** [comment]
Right, so don't update that module, use the version our Deps points to and you should be good.  If you want to update to newer code, then you'll need to update the GTLR project also as your using something we haven't moved up to yet (I believe we're still on the last tagged release).

**Comment by jerryhalstead** [comment]
I'm pretty sure I used what the deps points to, got the whole thing using gitHub Desktop.

**Comment by thomasvl** [comment]
Here's what I have when I check:

```
$ cd Deps/AppAuth
$ git log
commit 8ef151e0a29a969749617336d78da661525d6caf
Author: William Denniss <wdenniss@google.com>
Date:   Wed Dec 14 14:25:52 2016 -0800

    Version bump to 0.7.1

[...]
```

**Comment by jerryhalstead** [comment]
commit a62b4910a4a0526a3e3216d3f069d04dfcfac4df
Merge: 04533d9 7e827c6
Author: William Denniss <will@icog.net>
Date:   Sun Mar 5 20:30:26 2017 -0800

Guess I need to figure out how to get the project properly.

**Comment by aaroncrespo** [comment]
I can reproduce the first issue, it requires building this project as a framework/module

The headers exposed by this library have stuff that looks like 
```
#if GTL_USE_SESSION_FETCHER
  #define GTLUploadFetcherClass GTMSessionUploadFetcher
  #define GTLUploadFetcherClassStr @"GTMSessionUploadFetcher"

  #if GTL_USE_FRAMEWORK_IMPORTS
    #import <GTMSessionFetcher/GTMSessionFetcher.h>
    #import <GTMSessionFetcher/GTMSessionFetcherService.h>
  #else
    #import "GTMSessionFetcher.h". <--- these imports aren't allowed in modules.
    #import "GTMSessionFetcherService.h"
  #endif  // GTL_USE_FRAMEWORK_IMPORTS
#else
```

This is fine for pods because these preprocessor flags aren't exposed to the client (CocoaPods adds an xcconfig to your project that most people ignore) When built in isolation like most SDK's these days, the client app has no idea they need to set these flags. For a project that uses many SDK features this list could be long and if you want to not use CocoaPods becomes a very error prone setup step.

`GTL_USE_FRAMEWORK_IMPORTS=1` and `GTL_USE_SESSION_FETCHER=1` in GCC flags

In my experience these edge cases with build infrastructure will keep happening until frameworks are better supported. 

Carthage has some good guidance on creating Projects that support Carthage, Cocoapods and SwiftPM. 

AppAuth-iOS a root dependency of many google session libraries recently added Carthage support. (and because of similar approach soon SwiftPM)

**Comment by actuallymrj** [comment]
I am also having the same issue where the GTL_USE_FRAMEWORK_IMPORTS flag is not being seen and and getting dumped into the following line as a compile error.
`
 #import "GTMSessionFetcher.h". <--- these imports aren't allowed in modules.
`

**Comment by thomasvl** [comment]
What is _GoogleAPIClientForREST v3.17.0_?  The current release in this project is v1.2.1.

You also didn't really indicate how you are building, if you are using CocoaPods, it should be adding the defines for you.  If you are manually creating projects/etc. then you might have to add the defines yourself, exactly how will depend on your specific set up.

**Comment by actuallymrj** [comment]
@thomasvl Sorry, I was looking at the wrong pod include line, I am using 1.2.1 building with Cocoapods.

**Comment by thomasvl** [comment]
Who is including GTLRService.h and what target is it that is ultimately failing?  Is this one of the projects/targets the pods has created or something within your code?

**Comment by actuallymrj** [comment]
MyAppTarget has a swift file that has `import GoogleAPIClientForREST` . The compiler throws an error stating  "Could not build Objective-C module 'GoogleAPIClientForREST'"
Clicking on the error takes me to GTLRService.h, inside the GoogleAPIClientForREST/Core pod where there's an error on `#import "GTMSessionFetcher.h"` stating 'GTMSessionFetcher.h' file not found. 

Looking at the Pods-MyAppTarget.[debug|release].xcconfig file in both App project and Pods project and they both have the following line:
`GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 $(inherited) GTM_OAUTH2_USE_FRAMEWORK_IMPORTS=1 $(inherited) GTLR_USE_FRAMEWORK_IMPORTS=1`

But, when I go into the GoogleAPIClientForREST.xcconfig file I only see: 
`GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 $(inherited) GTLR_HAS_SESSION_UPLOAD_FETCHER_IMPORT=1`

This, combined with being jumped into the GTLR_USE_FRAMEWORK_IMPORTS == 0 case in GTLRService.h file leads me to believe that flag isn't being set correctly by the pod.

**Comment by thomasvl** [comment]
Actually, I've got changes on master to change some of this, I just haven't pushed them in a release yet.  Is there an easy way you can get your setup to use master instead of a tagged release?

**Comment by actuallymrj** [comment]
Not necessarily, we're pretty heavily dependent on using Cocoapods for the GoogleDrive API and I don't know of a way to point Cocopods at a non-versioned podspec. I did notice the file had some changes on master, as you're saying. If it's planned to go into the next upcoming version and would fix the issue I have a few weeks of slack time and could try again with the next version.

**Comment by thomasvl** [comment]
fyi - Just pushed 1.3.0 that changes around the imports and should hopefully help simplify things.

If someone ends up on this issue in the future with something they think is related, please open a new issue instead since this issue is actually a mix of things making it a little harder to figure out which problem someone is having when they comment.
