### ISSUE TITLE
Missing country property in GTLRBooksQuery_VolumesList

### ISSUE THREAD

**Issue by yoasha** [google/google-api-objectivec-client-for-rest#110]
I'm currently migrating my code from the old API (google-api-objectivec-client) to this API and found out that the following property doesn't exist in GTLRBooksQuery_VolumesList:

```Objective-C
/** ISO-3166-1 code to override the IP-based location. */
@property(nonatomic, copy, nullable) NSString *country;
```

It's available on several other request classes but not in the mentioned one. Please note that this functionality existed in the previous API and removed from the current one. 

Can this functionality be added back to the current API? I guess this property can either be added to GTLRBooksQuery_VolumesList, or alternatively move all together to the base class GTLRBooksQuery. Can you please suggest?

**Comment by thomasvl** [comment]
The old library used a single query class for all queries, then means all possible arguments were exposed, but some of them didn't actually apply to every query.

If you look at [header entry for books.bookshelves.volumes.list](https://github.com/google/google-api-objectivec-client/blob/master/Source/Services/Books/Generated/GTLQueryBooks.h#L158-L172), you'll notice the country didn't actually apply to it.

So while you might have been passing it, the [server docs](https://developers.google.com/books/docs/v1/reference/bookshelves/volumes/list) don't document it and thus it shouldn't have had any impact on what was returned.

**Comment by yoasha** [comment]
Thanks for clarifying!
