### ISSUE TITLE
GTLRYouTube 

### ISSUE THREAD

**Issue by jerryhalstead** [google/google-api-objectivec-client-for-rest#111]
In the previous version, before AppAuth, when a user's account is identified as "unlinked" we'd open a webview to:
https://m.youtube.com/create_channel?chromeless=1&next=/channel_creation_done

And then monitor the webview's load requests for "channel_creation_done" per these API instructions: 
https://developers.google.com/youtube/create-channel

Is there a recommended way to do this with the new GTLRYouTube and AppAuth? We can send them to an SFSafariViewController, but there's no way to know when they are done/successful.

I apologize if this is the wrong place to ask this.

**Comment by thomasvl** [comment]
It might make sense to directly add this over on AppAuth since that's from the folks doing Google signins in general, and know more of the details around using SFSafariViewController, etc.

fyi - @WilliamDenniss

**Comment by jerryhalstead** [comment]
Along those lines, if you perform a GTLRYouTubeQuery_VideosInsert with an unlinked account the uploadProgressBlock gets called a couple times and then nothing else happens, the executeQuery's completionHandler doesn't get called. In the GTL version it would get called with an error and if [errStr isEqualToString:@"(Unauthorized)"] we'd check to see if the account wasn't linked.

**Comment by thomasvl** [comment]
That sounds like a real bug, can you provide a example to show to cause this so we can take a look?

**Comment by jerryhalstead** [comment]
Well, I was going to try using the YouTube example to showcase it but having a hard time getting that to compile and I don't have much time to debug it right now.

But, you should be able to use that, log in with a gmail account that doesn't have an associated YouTube account and then try to upload a movie.

**Comment by thomasvl** [comment]
What's the error with building the example?  If you use the Deps at the revisions we point to, everything should build.  The travis.ci config on the commits says the example build with the last commit.
