### ISSUE TITLE
Resuming completed upload

### ISSUE THREAD

**Issue by araustin** [google/google-api-objectivec-client-for-rest#114]
When I have my schema set to the Debug build configuration, resuming an upload that already completed hits the GTLR_DEBUG_ASSERT on line 1226 of GTLRService.m.

I'm not sure if this what you would consider an issue, but I had already made this example up before I realized I could get around it by switching my build configuration.

I have this in a view controller with start and resume buttons. After the upload completes, I resume, and encounter the crash.

    var resumeUrl: URL?
    var progressHandler: GTLRServiceUploadProgressBlock?
    var completionHandler: GTLRServiceCompletionHandler = { ticket, video, error in print("upload complete") }

    func startUpload() {
        
        let auth = YouTubeAuthService()
        guard let authorization = auth.authorization else { return }

        let video = GTLRYouTube_Video()

        let url = Bundle.main.url(forResource: "test", withExtension: "mp4")
        let params = GTLRUploadParameters(fileURL: url!, mimeType: "video/mp4")
        params.useBackgroundSession = true
        params.shouldUploadWithSingleRequest = false

        progressHandler = { [weak self] ticket, numberOfBytesRead, dataLength in
            print("progress", Float(numberOfBytesRead) / Float(dataLength))
            if let fetcher = ticket.objectFetcher as? GTMSessionUploadFetcher {
                self?.resumeUrl = fetcher.uploadLocationURL
            }
        }

        let query = GTLRYouTubeQuery_VideosInsert.query(withObject: video, part: "snippet,status", uploadParameters: params)
        query.executionParameters.uploadProgressBlock = progressHandler
        let service = GTLRYouTubeService()

        // for some reason setting the chunk size is necessary or the upload does not continue in background
        service.serviceUploadChunkSize = UInt(kGTMSessionUploadFetcherStandardChunkSize)

        service.authorizer = authorization

        service.executeQuery(query, completionHandler: completionHandler)
    }

    func resumeUpload() {

        let auth = YouTubeAuthService()
        guard let authorization = auth.authorization else { return }

        let video = GTLRYouTube_Video()

        let url = Bundle.main.url(forResource: "test", withExtension: "mp4")
        let params = GTLRUploadParameters(fileURL: url!, mimeType: "video/mp4")
        params.useBackgroundSession = true
        params.shouldUploadWithSingleRequest = false
        params.uploadLocationURL = resumeUrl

        progressHandler = { ticket, numberOfBytesRead, dataLength in
            print("progress", Float(numberOfBytesRead) / Float(dataLength))
        }
        let query = GTLRYouTubeQuery_VideosInsert.query(withObject: video, part: "snippet,status", uploadParameters: params)
        query.executionParameters.uploadProgressBlock = progressHandler
        let service = GTLRYouTubeService()
        service.serviceUploadChunkSize = UInt(kGTMSessionUploadFetcherStandardChunkSize)

        service.authorizer = authorization

        service.executeQuery(query, completionHandler: completionHandler)

    }

**Comment by thomasvl** [comment]
I guess the first question is why resume something that completed?  😄 

Do you have a [log handy](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic), it would be interesting to see what the response is in this case.

**Comment by araustin** [comment]
Ha, if only I could stop the people testing my app from doing weird stuff, right?

My app tries to resume unfinished uploads when the app starts up. To get to this edge case, the user starts an upload, presses the home key, and waits while the upload completes on the background thread. Then the user kills the app from the multitasking screen. The completion handler is never called, and my app doesn't know the upload completed, so it tries to resume when it is next started.

Maybe there is some way to get notification of the completed upload when the app is suspended, but I don't know what it is. I tried `application:handleEventsForBackgroundURLSession:completionHandler:` but it does not seem to be called.

Anyway, thanks for looking at this. I've attached a log

[HQxYouTubeUploader_Example_log_3-30_12-18-33PM.zip](https://github.com/google/google-api-objectivec-client-for-rest/files/883578/HQxYouTubeUploader_Example_log_3-30_12-18-33PM.zip)

**Comment by thomasvl** [comment]
What's the message of the assert?  Assuming I'm reading this log right, the first fetch says it is html with no payload, the second one is json, which should be handled.

**Comment by araustin** [comment]
The message is 'Got unexpected content type '(null)''

It seems the fetcher.responseHeaders are nil so contentType is nil which makes isJSON NO and isBatchResponse NO so you end up at the assert.

I'm not sure how the responeHeaders are set but I'll debug a little more and see if I can find out.

**Comment by sergiocampama** [comment]
This may be related to an issue we are seeing with the session fetcher, where when pausing an upload after the last chunk was set, and resuming, would prevent the correct content type to be resolved.

**Comment by siuying** [comment]
I also seen this error. When it crashed, ``fetcher`` has no request or response object, but ``downloadData`` is a json:

```
{
    id = "{id}";
    kind = "drive#file";
    mimeType = "application/x-zip";
    name = "{filename}";
}
```

This happen when the code try to resume an upload 

```
(lldb) po executingQuery
GTLRDriveQuery_FilesUpdate 0x6000039388c0: {PATCH pathTemplate:files/{fileId} params:(fileId) urlQParams:(prettyPrint) bodyObject:GTLRDrive_File GTLRUploadParameters 0x6000012ec400: {MIMEType:application/octet-stream, file:{file}, uploadLocation:https://www.googleapis.com/resumable/upload/drive/v3/files?prettyPrint=false&upload_id={id}&upload_protocol=resumable}}
```

**Comment by siuying** [comment]
1. In the `[GTMSessionUploadFetcher sendQueryForUploadOffsetWithFetcherProperties:]` method, chunkFetcher is not set. 
https://github.com/google/gtm-session-fetcher/blob/fc437070ab58308b7d33ec350e5ee81c536ab5da/Source/GTMSessionUploadFetcher.m#L1127
2. In `[GTMSessionUploadFetcher chunkFetcher:finishedWithData:error]`, when a request is finished, `[GTMSessionUploadFetcher destroyChunkFetcher]` is called. In such case, `chunkFetcher` is nil and thus `_recentChunkReponseHeaders` is nil.
3. In `[GTLRService fetchObjectWithURL:..]`, it try to access fetcher.response but get nil, hence raise an assertion error "Got unexpected content type '(null)" later. https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Objects/GTLRService.m#L800

add following line `[GTMSessionUploadFetcher sendQueryForUploadOffsetWithFetcherProperties:]`  after `self.fetcherInFlight = queryFetcher;` fixes it:
```
  self.chunkFetcher = queryFetcher;
```

**Comment by siuying** [comment]
@thomasvl would you accept a PR to fix this issue at gtm-session-fetcher? unfortunately I cannot reproduce this in unit test.

**Comment by thomasvl** [comment]
Any issue in the session fetcher so big fixed, so go ahead and send PRs for things you see that seem like bugs.
