### ISSUE TITLE
Error 500 - Get Download drive.files.export

### ISSUE THREAD

**Issue by aalrazgan** [google/google-api-objectivec-client-for-rest#116]
I am running into an issue with google drive files that are larger than 5 MB (Maybe?) in size. I am trying to download them and export them as ```application/pdf``` but runs into error 500.

I am using the following code to retrieve and download the drive file (doc, ppt, or xls): 

```
- (void)downloadFile:(NSString *)fileID
         completionBlock:(void (^)(NSString *))onCompletionBlock
               failBlock:(void (^)(NSError *))onDownloadFailBlock {

    GTLRQuery *query = [GTLRDriveQuery_FilesExport queryForMediaWithFileId:resource.external_id mimeType:@"application/pdf"];
    GTLRDriveService *service = self.driveService;

    [service executeQuery:query
          completionHandler:^(GTLRServiceTicket *callbackTicket,
                            GTLRDataObject *dataObject,
                            NSError *callbackError) {
            if (callbackError == nil) {
                // The file downloaded successfully; its data is available as dataObject.data
                // File has been downloaded 
            } else {
                if (onDownloadFailBlock) {
                    onDownloadFailBlock(callbackError);
                }
                return;
            }
    }];
}
```

Below is an log that I get using ```GTMSessionFetcher```:
```
Download drive.files.export

2017-03-30 22:37:50 +0000  elapsed: 29.406sec
Request: GET https://www.googleapis.com/drive/v3/files/[fileID]/export?alt=media&mimeType=application%2Fpdf
Request headers:
  Accept: application/json
  Authorization: Bearer _snip_
  Cache-Control: no-cache
  Content-Type: application/json; charset=utf-8
  User-Agent: org.cocoapods.GoogleAPIClientForREST/1.2.1 google-api-objc-client/3.0 iPhone/10.2 hw/sim (gzip)

Response: status 500
Response headers:
  Cache-Control: private, max-age=0
  Content-Encoding: gzip
  Content-Length: 123
  Content-Type: application/json; charset=UTF-8
  Date: Thu, 30 Mar 2017 22:37:50 GMT
  Expires: Thu, 30 Mar 2017 22:37:50 GMT
  Server: GSE
  Vary: Origin, X-Origin
  alt-svc: quic=":443"; ma=2592000; v="37,36,35"
  x-content-type-options: nosniff
  x-frame-options: SAMEORIGIN
  x-xss-protection: 1; mode=block

Response body: (180 bytes)
{
  "error" : {
    "message" : "Internal Error",
    "errors" : [
      {
        "reason" : "internalError",
        "message" : "Internal Error",
        "domain" : "global"
      }
    ],
    "code" : 500
  }
}
```

For what's it worth, it seems to me there is a limit of 30 seconds when it will throw back this error - 500. For files that are less than 5 MB in size, it is doing it correctly and I am able to get back the pdf file so I am 100% sure it is not an authentication issue. 

I have also tried changing the mimeType to ```vnd.openxmlformats-officedocument.wordprocessingml.document``` and I would get a 403 error that says ``` "message": "This file is too large to be exported."```.

Any idea how to go around this problem?

Thank you.

**Comment by thomasvl** [comment]
Just clarifying, are you saying after 30 seconds there is no error?  It could be that it takes a moment for the upload to propagate or something.  If that is the case, this doesn't so much sound like a problem with the client library as much as it is a server issues/restriction, so you'll likely want to use the [support areas listed for the drive api](https://developers.google.com/drive/v3/web/support), as the server folks are going to be reachable there.  (This library works by generating the api for all the services it supports, so we don't know the ins/outs of every api that can be generated)

**Comment by aalrazgan** [comment]
Not really, it never reaches past 30 seconds. Once I make an export call and it reaches 30 seconds (usually with 5 MB files or more), it will throw the 500 error. It is a server issue and I will create an issue over there.

Thank you.
