### ISSUE TITLE
GTLR integration 

### ISSUE THREAD

**Issue by Mohammad-Rabi** [google/google-api-objectivec-client-for-rest#118]
Hey guys,

I have an App that connected to google calendar using GTL old library, i have integrated the new library GTLR.

The problem is when i try to fetch the calendars using the following segment of code the app will crash.

` GTLRCalendarQuery_CalendarListList *query = [GTLRCalendarQuery_CalendarListList query];
    calendarListTicket = [service executeQuery:query completionHandler:^(GTLRServiceTicket *ticket, id calendarList, NSError *error) {}];`

Here is my Stack Trace :

2017-04-12 15:53:49.660 Calendar[34395:1904790] Stack Trace: (
	0   CoreFoundation                      0x000000010afb5b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010aa16141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b025134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010af3c840 ___forwarding___ + 1024
	4   CoreFoundation                      0x000000010af3c3b8 _CF_forwarding_prep_0 + 120
	5   Calendar                            0x00000001050116b7 -[GTMSessionFetcherService fetcherDidCreateSession:] + 199
	6   Calendar                            0x00000001053328bc -[GTMSessionFetcher beginFetchMayDelay:mayAuthorize:] + 5356
	7   Calendar                            0x0000000105330470 -[GTMSessionFetcher beginFetchWithCompletionHandler:] + 320
	8   Calendar                            0x000000010535ba47 -[GTLRService fetchObjectWithURL:objectClass:bodyObject:dataToPost:ETag:httpMethod:mayAuthorize:completionHandler:executingQuery:ticket] + 7783
	9   Calendar                            0x000000010535f686 -[GTLRService fetchObjectWithURL:objectClass:bodyObject:ETag:httpMethod:mayAuthorize:completionHandler:executingQuery:ticket] + 1222
	10  Calendar                            0x000000010536abaa -[GTLRService executeQuery:completionHandler:] + 3370
	11  Calendar                            0x000000010512a502 +[GoogleUtils fetchCalendarList:completion:] + 402
	12  Calendar                            0x0000000105129fc9 +[GoogleUtils syncWithGoogleCalendar:] + 345
	13  Calendar                            0x00000001053a46bb -[BaseCalendarViewController startGoogleSyncWithHud:] + 187
	14  Calendar                            0x00000001052e89be -[CalendarViewController viewDidLoad] + 1134
	15  UIKit                               0x0000000108e21cca -[UIViewController loadViewIfRequired] + 1235
	16  UIKit                               0x0000000108e2210a -[UIViewController view] + 27
	17  UIKit                               0x0000000108cea63a -[UIWindow addRootViewControllerViewIfPossible] + 65
	18  UIKit                               0x0000000108cead20 -[UIWindow _setHidden:forced:] + 294
	19  UIKit                               0x0000000108cfdb6e -[UIWindow makeKeyAndVisible] + 42
	20  Calendar                            0x00000001050d4d8b -[CalendarAppDelegate application:didFinishLaunchingWithOptions:] + 4651
	21  UIKit                               0x0000000108c75957 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 299
	22  UIKit                               0x0000000108c7723c -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4119
	23  UIKit                               0x0000000108c7d584 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1709
	24  UIKit                               0x0000000108c7a793 -[UIApplication workspaceDidEndTransaction:] + 182
	25  FrontBoardServices                  0x0000000112e665f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	26  FrontBoardServices                  0x0000000112e6646d -[FBSSerialQueue _performNext] + 186
	27  FrontBoardServices                  0x0000000112e667f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	28  CoreFoundation                      0x000000010af5bc01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	29  CoreFoundation                      0x000000010af410cf __CFRunLoopDoSources0 + 527
	30  CoreFoundation                      0x000000010af405ff __CFRunLoopRun + 911
	31  CoreFoundation                      0x000000010af40016 CFRunLoopRunSpecific + 406
	32  UIKit                               0x0000000108c7902f -[UIApplication _run] + 468
	33  UIKit                               0x0000000108c7f0d4 UIApplicationMain + 159
	34  Calendar                            0x00000001050c5ce4 main + 52
	35  libdyld.dylib                       0x000000010fcff65d start + 1
	36  ???                                 0x0000000000000001 0x0 + 1
)

I really appreciate any help you can provide.
Thanks you in advance

**Comment by thomasvl** [comment]
That snippets a little lite to really tell what's going on.  If you have it that reduced, do you have a simple test project you can attach?  What versions of things are you using?
