### ISSUE TITLE
GTMAuth dependency fails to build

### ISSUE THREAD

**Issue by aaroncrespo** [google/google-api-objectivec-client-for-rest#119]
Trying to build a Project that uses this Library and GTMAuth for sessions/auth fails due to GTMAuth failing to compile.

**Comment by aaroncrespo** [comment]
Most of the details are in various issues in the GTMAuth library repo.

**Comment by aaroncrespo** [comment]
a pod spec with 
```
...
  s.dependency 'GoogleAPIClient/Drive'
  s.dependency 'GTMAppAuth'
end
```
and `pod lib lint` will repro.

**Comment by thomasvl** [comment]
Sounds like you want to open the issue with GTMAppAuth then?  https://github.com/google/GTMAppAuth

Make sure you include the details about the version you are using, the actual errors, etc.

**Comment by aaroncrespo** [comment]
There are months worth of issues on that project, jus trying to raise visibility.

**Comment by thomasvl** [comment]
Unfortunately, they are different people also.  If there's a specific issue with the details you can point to, we can try to ping some folks behind the scenes.

**Comment by thomasvl** [comment]
Closing out as GTMAppAuth seems to have recently done a 0.6.0 release, so hopefully the issues were resolved.
