### ISSUE TITLE
Expanding already logged in user's scopes possibility.

### ISSUE THREAD

**Issue by AlexandrKuznetsovSS** [google/google-api-objectivec-client-for-rest#120]
Hi, I collided with the problem of expanding user's scope. I have already logged in user in my app, when user want to open their GoogleDrive, I expand scopes with Drive permission and than, as said in docs, call `-signIn` method from Google Sign-In framework. But in any case user can choose another account, so I loose logged in user's data, and my `-currentUser` become `nil` immediately after scopes are changed.

Is there any possibility to expand already logged in user's scopes or do something to be sure that user can't choose another account in allowing Drive permission process? 

I aware about -`loginHint` property, but "Use another account" variant remains available.
Thanks.

**Comment by thomasvl** [comment]
Unfortunately, those of us that maintain this library don't have much direct experience with that SignIn library.  You're best by is likely the _Help_ info linked off [their docs](https://developers.google.com/identity/sign-in/ios/).

**Comment by AlexandrKuznetsovSS** [comment]
Okay, anyway, thanks for response, I'll try to dig deeper. Have a nice day.
