### ISSUE TITLE
SKIP_INSTALL isn't set on GTLROSXCore and AppAuth-macOS

### ISSUE THREAD

**Issue by R4N** [google/google-api-objectivec-client-for-rest#124]
When attempting to archive a macOS project that includes GTLR it generates a generic xcarchive rather than a macOS App Archive.  This is because the SKIP_INSTALL isn't set on GTLROSXCore or AppAuth-macOS.

I believe they need to be set in the repective project files similar to what this pull request did for iOS: https://github.com/google/google-api-objectivec-client-for-rest/pull/28

Specifically add `SKIP_INSTALL = YES;` to these build configurations:

GTLROSXCore ~ Debug (4F38F7120B66EF2C00B24B81)
GTLROSXCore ~ Release (4F38F7130B66EF2C00B24B81)

AppAuth-macOS ~ Debug (340DAE551D58216A00EC285B)
AppAuth-macOS ~ Release (340DAE561D58216A00EC285B)

What's the best way to proceed here?  Should I issue a PR on both projects?

**Comment by thomasvl** [comment]
PR would be great.

**Comment by thomasvl** [comment]
Fixed via ##126
