### ISSUE TITLE
Youtube video upload hangs query hangs with no youtube channel on the google account

### ISSUE THREAD

**Issue by PhilipDukhov** [google/google-api-objectivec-client-for-rest#125]
I used GTLRYouTubeQuery_VideosInsert to upload video from a google account, which doesn't have a youtube channel.
Service uploadProgressBlock was called two times - both times 107 bytes uploaded, and than neither this one nor the execute callback was called.
I placed breakpoints on NSURLSessionTaskDelegate methods and saw "401 Unauthorized" error, but I would prefer get some callback called for this case.

Now I am checking availability user to upload the video with GTLRYouTubeQuery_ChannelsList query, "status" part, and value on key "isLinked" seems to be the one I need. Is it correct? Can it be that there is another unhandled error situation?

Interesting thing - iOS Photos app in the same case uploaded the video - well it also hanged but after uploading video just with "Uploading to YT" and 100% progress bar, and when I created youtube channel on that account - it appeared as uploaded, and Photos app actually finished the upload.

**Comment by thomasvl** [comment]
Can you use the library [http logging](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) to capture the response so we can see what happening in your case?

When invoking executeQuery are you using the completion handler form or the delegate/selector version?

**Comment by PhilipDukhov** [comment]
HTTP logging show this message:
`2017-05-16 05:36:07 +0000      youtube.videos.insert      request/response log
elapsed: 0.375sec
request: POST https://www.googleapis.com/resumable/upload/youtube/v3/videos?part=snippet%2Cstatus&prettyPrint=false
   headers: 8 
   data: 107 bytes, application/json; charset=utf-8
response:  status 401 unauthorized  ⚑
   headers: 9 
   data: 195 bytes, application/json `
I am using the handler version, and now tried the delegate one - result is the same.

**Comment by thomasvl** [comment]
The logs should be a directory with the overview and details, the details will have the full info.

Can you share a snippet of what making your query looks like?

**Comment by PhilipDukhov** [comment]
Here is a sample, remember to log in with account without youtube channel.
[YoutubeUploadSample.zip](https://github.com/google/google-api-objectivec-client-for-rest/files/1004466/YoutubeUploadSample.zip)
And this is the content of fetch_1.txt:

`youtube.videos.insert

2017-05-16 13:15:42 +0000  elapsed: 0.793sec
Request: POST https://www.googleapis.com/resumable/upload/youtube/v3/videos?part=snippet%2Cstatus&prettyPrint=false
Request headers:
  Accept: application/json
  Cache-Control: no-cache
  Content-Type: application/json; charset=utf-8
  User-Agent: org.cocoapods.GoogleAPIClientForREST/1.0.3 google-api-objc-client/3.0 iPhone/10.3 hw/sim (gzip) (GTMSUF/1)
  X-Goog-Upload-Command: start
  X-Goog-Upload-Content-Length: 5320048
  X-Goog-Upload-Content-Type: video/quicktime
  X-Goog-Upload-Protocol: resumable

Request body: (112 bytes)
{
  "status" : {
    "privacyStatus" : "private"
  },
  "snippet" : {
    "title" : "sampleTitle -1.01327896118164e-06",
    "categoryId" : "23"
  }
}

Response: status 401
Response headers:
  Content-Length: 195
  Content-Type: application/json; charset=UTF-8
  Date: Tue, 16 May 2017 13:15:41 GMT
  Server: UploadServer
  Vary: Origin, X-Origin
  Www-Authenticate: Bearer realm="https://accounts.google.com/", error=invalid_token
  alt-svc: quic=":443"; ma=2592000; v="37,36,35"
  x-goog-upload-status: final
  x-guploader-uploadid: AEnB2UqrWjfbjfnLjCugMCFvHDr0kuxeOEEZj1xZtHSzp-7Xse49V_lYnbcMMm3ttUgGEX8eI1iF7rHPWyr25LgE0anbJhaiIpya4OIQutV_an3HY-jxnjU

Response body: (195 bytes)
{
  "error" : {
    "message" : "Unauthorized",
    "errors" : [
      {
        "message" : "Unauthorized",
        "locationType" : "header",
        "reason" : "youtubeSignupRequired",
        "domain" : "youtube.header",
        "location" : "Authorization"
      }
    ],
    "code" : 401
  }
}
-----------------------------------------------------------
`

**Comment by sergiocampama** [comment]
I can reproduce locally with the sample project, looking into this

**Comment by sergiocampama** [comment]
We've identified the issue as coming from the GTMSessionFetcher... Looking into possible solutions

**Comment by mwyman** [comment]
A bug in the retry handling mechanism (when using the upload fetcher) is causing the completion handler you originally pass to beginFetchWithCompletionHandler: to get released on retry. We have a fix in the works.

**Comment by sergiocampama** [comment]
this has been solved in https://github.com/google/gtm-session-fetcher/pull/83
