### ISSUE TITLE
Can't pull v1.3.0 from pod update

### ISSUE THREAD

**Issue by actuallymrj** [google/google-api-objectivec-client-for-rest#138]
If I try to declare `pod 'GoogleAPIClientForREST/Drive', '~> 1.3.0'` in my Podfile, I get an error that the version couldn't be found after the latest 1.3.0 release. When leaving off the version specifier, it updates to version 1.2.1 by default, as if 1.3.0 doesn't exist.

**Comment by actuallymrj** [comment]
As a follow up, a `pod repo update` does not seem to fix the issue.

**Comment by thomasvl** [comment]
Doh, reading my shell history, I did validations, but didn't do the push.  😦   doing a trunk push now.

**Comment by thomasvl** [comment]
Sorry again about that, it should in now.  Although I'm having issues checking on just about any pod on cocoapod.org at the moment.

**Comment by actuallymrj** [comment]
No worries, thanks for the fast turn around.
