### ISSUE TITLE
Sending mail with a attachment

### ISSUE THREAD

**Issue by ablyeom** [google/google-api-objectivec-client-for-rest#14]
Hi, I'm trying to send a mail with a attachment.
Mail was delivered properly, but attachment is not delivered.

Here is my code. Is there any problems?

Please help me.

``` objective-c
mailMessage.raw = GTLREncodeWebSafeBase64([rawMessage dataUsingEncoding:NSUTF8StringEncoding]);

GTLRUploadParameters *imageParams = [GTLRUploadParameters uploadParametersWithData:UIImagePNGRepresentation(image)
                                                                          MIMEType:@"message/rfc822"];

GTLRGmailQuery_UsersMessagesSend *query = [GTLRGmailQuery_UsersMessagesSend queryWithObject:mailMessage
                                                                                     userId:email
                                                                           uploadParameters:imageParams];

GTLRGmailService *service = [[GTLRGmailService alloc] init];
service.authorizer = self.user.authentication.fetcherAuthorizer;

[service executeQuery:query completionHandler:^(GTLRServiceTicket *callbackTicket, GTLRGmail_Message *object, NSError *callbackError) {
    if (callbackError) {
        DDLogError(@"%@", callbackError);
        DDLogError(@"UserInfo[@\"data\"] - %@", callbackError.userInfo[@"data"]);
        return;
    }
    DDLogInfo(@"Sent - %@", object);
}];
```

**Comment by sergiocampama** [comment]
I'm not particularly familiar with the Gmail api, but can you try adding the image in a GTLRGmail_MessagePartBody, which goes into a GTLRGmail_MessagePart, which goes into your GTLRGmail_Message object?

**Comment by ablyeom** [comment]
Hm.... GMTSessionFetcher's logs show me a `uploadId` for the attachment. But it is not in email.

@sergiocampama I tried. but .... it didn't work.

**Comment by sergiocampama** [comment]
Have you checked https://developers.google.com/gmail/api/guides/uploads?

If not, I'd encourage you to contact support as specified in https://developers.google.com/gmail/api/support

**Comment by thomasvl** [comment]
If you didn't get anything back from the server, saying there was an issue, then it sounds like the issue is likely server side.  So as Sergio suggest, the support side of the gmail api may be your best bet (https://developers.google.com/gmail/api/support).  Collecting an http log (https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) might be useful to provide the server folks more details.

**Comment by Saulenco** [comment]
I have stuck also on the attachment part @ablyeom  did you manage to find a solution ?

**Comment by meharoofnajeeb** [comment]
@ablyeom Same here. I am also stuck on attachment part. There aren't any proper examples mentioned either.
