### ISSUE TITLE
Unable to download Large PDF Files

### ISSUE THREAD

**Issue by tmvipinster** [google/google-api-objectivec-client-for-rest#141]
We are trying to download large PDF files using the following lines of code

  ```
  query = [GTLRDriveQuery_FilesGet queryForMediaWithFileId:downloadUrlString];
    NSURLRequest *downloadRequest = [driveService requestForQuery:query];
    self.fetcher = [driveService.fetcherService fetcherWithURL:downloadRequest.URL];
     [self.fetcher beginFetchWithCompletionHandler:^(NSData *data, NSError *error) {
      // Our App Specific code
    }];
```

This works perfectly for PDF files<70 MB  and also for other types of files with even larger file size like 200 MB

But when we try to download PDF files > 70 MB it fails with error 
`
Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x60805344aad0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://www.googleapis.com/download/drive/v3/files/fileID?alt=media, NSErrorFailingURLKey=https://www.googleapis.com/download/drive/v3/files/fileID?alt=media, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}`

Tried increasing time out of downloadRequest.timeoutInterval but no luck.

What might be the possible root cause for this?

**Comment by thomasvl** [comment]
The time out code be on either the client or server side, from this info it a little hard to tell.

The code fragment you have there appears to also be trying to download into memory, if you use `fetcher.destinationFileURL` you can have the download go directly to a file to reduce the memory costs.

As far as generally downloading large files, especially in a mobile space, you might want to consider using HTTP range support so you can resume downloads, etc.

**Comment by tmvipinster** [comment]
@thomasvl 

Thanks for the update.

But the issue seems to be only with PDF files. Other larger files I am able to download like videos,zip files > 300 MB
We have looked into the feasibility of using Range headers but this is not viable as of now.

Please let me know if you need any further information like wireshark trace etc

**Comment by thomasvl** [comment]
@sergiocampama can you see if you can repo this?

**Comment by sergiocampama** [comment]
I can't seem to reproduce this locally. I used 100 Mb pdfs and they seem to work OK. Would it be possible for you to provide a sample project and a file that we can use to reproduce this?

**Comment by tmvipinster** [comment]
I have the PDF ready with me . Please give me a couple of days to create a sample project and I will be uploading the same here
