### ISSUE TITLE
Upload Limit Exceeded

### ISSUE THREAD

**Issue by DeepaSuhas** [google/google-api-objectivec-client-for-rest#143]
In Google API SDK (https://github.com/google/google-api-objectivec-client-for-rest)  if I upload too many videos in a short time. then I am getting a message saying that  "The operation couldn't be completed. (com.google.HTTPStatus error 400.) ".  How will I come to know that the upload is failed because of upload limit Exceeded. ? Do the API throw an appropriate error for the above issue?

But In YouTube website, if I upload too many videos in a short time, I am getting a message saying "The upload has failed because you uploaded too many videos in a short time. You'll need to wait before uploading more videos." 

Help me to solve this issue.

**Comment by thomasvl** [comment]
First up, your quotas should be in the developer console.  You'd have to check the public docs on the YouTube api for what options they give for getting more quota.  [Our wiki mention of quota](https://github.com/google/google-api-objectivec-client-for-rest/wiki#api-quotas).

When you execute a query, the handler can get called back with an `NSError` argument and the result would be `nil`.  If there server returned a detailed JSON error, that is included within the `NSError`, [`+[GTLRErrorObject underlyingObjectForError:]`](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Objects/GTLRErrorObject.h#L46) will extract the `GTLRErrorObject` if there is on, if that returns `nil`, then continue to inspect the `NSError` as it was some other error.  There are two different JSON formats for errors, so `GTLRErrorObject` exposes methods for both, best bet it to consult the headerdocs for the class and [YouTubes page on their service specific errors](https://developers.google.com/youtube/v3/docs/errors).

**Comment by DeepaSuhas** [comment]
I used  +[GTLRErrorObject underlyingObjectForError:] to extract the error. But I am getting nil value.

In NSError object there is a userInfo which has "data" field. It contains the following
 value "7b226572726f72223a7b226572726f7273223a5b7b22646f6d61696e223a22796f75747562652e766964656f222c22726561736f6e223a2275706c6f61644c696d69744578636565646564222c226d657373616765223a2254686520757365722068617320657863656564656420746865206e756d626572206f6620766964656f732074686579206d61792075706c6f61642e227d5d2c22636f6465223a3430302c226d657373616765223a2254686520757365722068617320657863656564656420746865206e756d626572206f6620766964656f732074686579206d61792075706c6f61642e227d7d"

I converted this value using http://string-functions.com/hex-string.aspx. I got this string value 
" {"error":{"errors":[{"domain":"youtube.video","reason":"uploadLimitExceeded","message":"The user has exceeded the number of videos they may upload."}],"code":400,"message":"The user has exceeded the number of videos they may upload."}} ."

Is there any method in your SDK which converts the hex to string. ?

**Comment by thomasvl** [comment]
Can you get a [http log](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) showing this happening.  The error object should have been directly returned, so I'd like to see exactly what was on the wire to see if a bug is needed against the YouTube server team.

**Comment by amitanmol** [comment]
@DeepaSuhas You can use below code to convert the hex to string and print in log:

NSLog(@"Error: %@", [[NSString alloc] initWithData:data encoding:NSASCIIStringEncoding]);
