### ISSUE TITLE
GTLRService.h: authorizer property not imported in Swift module

### ISSUE THREAD

**Issue by actuallymrj** [google/google-api-objectivec-client-for-rest#147]
In GTLRService.h

The following property is not created when importing into a Swift project with 
`import GoogleAPIClientForREST`

```
/**
 *  An authorizer adds user authentication headers to the request as needed.
 *
 *  This may be overridden on individual queries with the @c shouldSkipAuthorization property.
 */
@property(nonatomic, retain, nullable) id <GTMFetcherAuthorizationProtocol> authorizer;
```

The generated module contains the following:

```
/**
     *  Some services require a developer key for quotas and limits.
     */
    open var apiKey: String?

    
    /**
     *  An authorizer adds user authentication headers to the request as needed.
     *
     *  This may be overridden on individual queries with the @c shouldSkipAuthorization property.
     */

/// This is where the authorizer should be declared.
    
    /**
     *  Enable fetcher retry support.  See the explanation of retry support in @c GTMSessionFetcher.h
     *
     *  Default value is NO, but retry is also enabled if the retryBlock is not nil.
     *
     *  This may also be specified for a single query in the query's @c executionParameters property.
     */
    open var isRetryEnabled: Bool
```

Is it possible that this is because it's declared as retain, instead of strong?

I think not being able to set this property is why I'm getting an error of "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup." when trying to submit a Drive Query in Swift.

**Comment by thomasvl** [comment]
Odds are you are using a Bridging header in Swift.  Since the protocol is just forward declared, it silently gets dropped.  If you add something like `#import "GTMSessionFetcher/GTMSessionFetcher.h"` to your bridging header, the protocol will be defined.

**Comment by actuallymrj** [comment]
@thomasvl that worked, thanks!

**Comment by thomasvl** [comment]
np.

Just added it to the [Building Wiki](https://github.com/google/google-api-objectivec-client-for-rest/wiki/BuildingTheLibrary#using-a-swift-bridging-header) also.

Sadly, when this first came up, it took a while to figure it out, and Apples docs don't seem to directly speak to this "behavior".  ☹️

**Comment by 27lahawa29** [comment]
I don't understand this email... can you briefly bullet explain 101???:)

Thanks A lot

Shelly Forgione

On Jul 6, 2017, at 2:59 PM, Thomas Van Lenten <notifications@github.com> wrote:

Odds are you are using a Bridging header in Swift. Since the protocol is just forward declared, it silently gets dropped. If you add something like #import "GTMSessionFetcher/GTMSessionFetcher.h" to your bridging header, the protocol will be defined.

**Comment by actuallymrj** [comment]
@27lahawa29 if you looks at GTLRService.h instead of including GTMSessionFetcher.h directly in the header where the protocol declaration would be directly inserted into the file at preprocessing, it is forward declared using `@protocol GTMFetcherAuthorizationProtocol;` at line 32. Essentially promising to the compiler that it's declaration will be encountered at some point. The compiler wasn't able to expand the header into a module file for inclusion in Swift as this declaration wasn't found, causing the line that used it `@property(nonatomic, retain, nullable) id <GTMFetcherAuthorizationProtocol> authorizer;` at line 275 to be omitted from the Swift module import.

**Comment by thomasvl** [comment]
@27lahawa29 please unwatch projects if you don't understand them, replying to all the issues/pull requests asking other people to explain them isn't very fair.

**Comment by ghinminesuyog** [comment]
I have tried what @thomasvl has mentioned, I added a bridging file but I still get the error "Value of type 'GTLRCalendarService' has no member 'authorizer'". Do I have to explicitly include the bridging header file?

**Comment by mohitathwani** [comment]
I'm using Cocoapods with Xcode 11.1 and the fetcherAuthorizer on GTLRDriveService cannot be found.
