### ISSUE TITLE
File not found for library included by cocoapods

### ISSUE THREAD

**Issue by amofbnow** [google/google-api-objectivec-client-for-rest#149]
I'm trying to install google-api-objectivec-client-for-rest lib from google, i'm using cocoapods, this is my pod:

    # Uncomment this line to define a global platform for your project
    platform :ios, '9.0'
    
    target 'YoutubeTest' do
      # Uncomment this line if you're using Swift or would like to use dynamic frameworks
      use_frameworks!
    
      # Pods for YoutubeTest
    
        pod 'GTMAppAuth'
        pod 'GoogleAPIClientForREST'
    
    end

with a `pod install` i can see library on my xcode project, but when i try to insert in a class it returns me always "file not found". For example, i have to use those methods to try to upload a video on youtube (i take this methods in the examples of the library, "YouTubeSample"), this is one example:

    - (void)uploadVideoFile {
        // Collect the metadata for the upload from the user interface.
        
        // Status.
        GTLRYouTube_VideoStatus *status = [GTLRYouTube_VideoStatus object];
        status.privacyStatus = _uploadPrivacyPopup.titleOfSelectedItem;
        
        // Snippet.
        GTLRYouTube_VideoSnippet *snippet = [GTLRYouTube_VideoSnippet object];
        snippet.title = _uploadTitleField.stringValue;
        NSString *desc = _uploadDescriptionField.stringValue;
        if (desc.length > 0) {
            snippet.descriptionProperty = desc;
        }
        NSString *tagsStr = _uploadTagsField.stringValue;
        if (tagsStr.length > 0) {
            snippet.tags = [tagsStr componentsSeparatedByString:@","];
        }
        if ([_uploadCategoryPopup isEnabled]) {
            NSMenuItem *selectedCategory = _uploadCategoryPopup.selectedItem;
            snippet.categoryId = selectedCategory.representedObject;
        }
        
        GTLRYouTube_Video *video = [GTLRYouTube_Video object];
        video.status = status;
        video.snippet = snippet;
        
        [self uploadVideoWithVideoObject:video
                 resumeUploadLocationURL:nil];
    }

To use the methods i'm including the "pod installed libraries" in this way in the .m file class

    #import <AppAuth/AppAuth.h>
    #import <GTMAppAuth/GTMAppAuth.h>

those code lines returns <AppAuth/AppAuth.h> not found or <GTMAppAuth/GTMAppAuth.h> not found. In the google project wiki i can't find useful information about this problem, there's something wrong in my inclusion? There something i have to check in Build settings?
I'm using Xcode 8.3.2

**Comment by sergiocampama** [comment]
I just tried to create a project with your same Podfile, and was able to use `#import <AppAuth/AppAuth.h>` to load AppAuth symbols with no problem. Perhaps you're using an old version of cocoapods?
