### ISSUE TITLE
Youtube Data API V3 not working for channel with OAuth 2.0

### ISSUE THREAD

**Issue by sachinvas** [google/google-api-objectivec-client-for-rest#15]
I have authenticated the user with the Google/SignIn. I have the access token, when I create a request to get the channelId for a particular username, it throws the error

{
    error =     {
        code = 403;
        errors =         (
                        {
                domain = usageLimits;
                extendedHelp = "https://code.google.com/apis/console";
                message = "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.";
                reason = dailyLimitExceededUnreg;
            }
        );
        message = "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.";
    };
}

I am sending the accessToken in the http header with the "Authorization".

When I use the APIKey instead of accessToken it works as expected.
I checked in the OAuth Playground, it is working as expected.

**Comment by thomasvl** [comment]
You'll have to provide more details; normally you just need to set an authorizer as mentioned in the [wiki](https://github.com/google/google-api-objectivec-client-for-rest/wiki#authentication-and-authorization).  From the snippet, it sounds like the requests aren't being authorized.
