### ISSUE TITLE
Release Build Failure

### ISSUE THREAD

**Issue by stevendev** [google/google-api-objectivec-client-for-rest#171]
GTLRiOSCore cannot run with release build.

```
ld: bitcode bundle could not be generated because '/Users/stevenzhang/Library/Developer/Xcode/DerivedData/GTLRCore-evyewhrnttwcbpfqxbjdwxomvdwn/Build/Products/Release-iphoneos/libAppAuth-iOS.a(OIDErrorUtilities.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/stevenzhang/Library/Developer/Xcode/DerivedData/GTLRCore-evyewhrnttwcbpfqxbjdwxomvdwn/Build/Products/Release-iphoneos/libAppAuth-iOS.a' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
![screen shot 2017-09-08 at 5 39 20 pm](https://user-images.githubusercontent.com/1029394/30205851-bfbf0262-94bc-11e7-9147-68cb4885eeb6.png)

**Comment by thomasvl** [comment]
Sorry for the delay in looking, I've I'm reading your error correctly, the error isn't actually with this library but is actually with AppAuth -

> ld: bitcode bundle could not be generated because '/Users/stevenzhang/Library/Developer/Xcode/DerivedData/GTLRCore-evyewhrnttwcbpfqxbjdwxomvdwn/Build/Products/Release-iphoneos/libAppAuth-iOS.a(OIDErrorUtilities.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/stevenzhang/Library/Developer/Xcode/DerivedData/GTLRCore-evyewhrnttwcbpfqxbjdwxomvdwn/Build/Products/Release-iphoneos/libAppAuth-iOS.a' for architecture armv7

Note the _... libAppAuth-iOS.a(OIDErrorUtilities.o)' was built without full bitcode. All object files and libraries for bitcode ..._

`AppAuth.xcodeproj` is just an external reference from the `GTLRCore.xcodeproj` project.  So the fix will be needed in that project instead.

**Comment by StevenEWright** [comment]
I believe I know the cause. I think it may be because AppAuth is performing single object linking. I’ll sync with the current appauth maintainers.

**Comment by WilliamDenniss** [comment]
I wonder if [this](https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9) will fix it.
```On Build Settings -> Other C flags, set Debug to -fembed-bitcode-marker, and Release to -fembed-bitcode. Make sure that is set for your project, and not the targets.```

Can you make this change in the AppAuth.xcodeproj and try again? If it works, please submit the change to [AppAuth](https://github.com/openid/AppAuth-iOS) (or let us know that it resolves the issue).

**Comment by StevenEWright** [comment]
Yeah, so I left my last comment in haste and just wanted to circle back around. I think we fully understand the problem now.

My understanding is that, when using xcode’s setting for “BITCODE ENABLED” exclusively, it functions as follows: for all non-archive builds, it only adds the parameter ‘-femit-bitcode-marker’ to the compilation(s) this parameter seems to be basically a hack. It adds an empty bitcode section to the object file as a signal to the rest of the process that says “yeah, don’t worry, when you build for archiving (App Store) I’ll go ahead and actually emit the bitcode here”. Only when you build for archiving does it actually emit the LLVM IR to the object file by passing ‘-femit-bitcode’. In this case, based on the linker settings in the screenshot, it looks like bitcode generation had been explicitly requested, and failed correctly at linking time when there was no bitcode in the AppAuth library to link with the GTLR bitcode.

It sounds like the most robust solution is for us to just always emit bitcode for AppAuth - which will prevent confusion generally, at a small cost to AppAuth build time and size of temporary object files / etc. which seems like a worthwhile trade off for ease of use.

**Comment by R4N** [comment]
@StevenEWright @WilliamDenniss 

Awesome, Ya I noticed that adjusting those flags on AppAuth resolved it as well, and that was my initial inclination for the fix.  It was just odd to me that the flag wasn't being automatically passed in as I thought it would be.  But the further analysis makes sense.

Can confirm with the latest pulled down from AppAuth into my Vanilla test project, Release config builds without generating this bitcode error.

Thanks for making the adjustment!
