### ISSUE TITLE
drive.files.list v2 to get 404 error

### ISSUE THREAD

**Issue by LinkDentity** [google/google-api-objectivec-client-for-rest#181]
We recently got many many 404 error when calling drive api drive.files.list, does anyone have a clue? Our app was using drive api for more than 3 years, and a couple of days ago we released a new version to App store to support ios 11 and iPhone X, since then about 1/4 calls have this 404 error on api drive.files.list.

Please help!!!

**Comment by thomasvl** [comment]
With out more info, it is going to be hard to guess what is happening.  If you turn on the built in [http logging](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) it may make it easier to inspect what is in the servers reply to figure out what is going wrong.

**Comment by LinkDentity** [comment]
Thanks a lot for your help! it turned out that we made a silly mistake when signing up new users...Everything is ok now!
