### ISSUE TITLE
How to Get the Direct Download Link for a Google Drive File ?

### ISSUE THREAD

**Issue by mt-lelang** [google/google-api-objectivec-client-for-rest#184]
I have a link for downloading the content of the file in a browser (webContentLink) and accesstoken:
The direct link have the format: webContentLink + &accesstoken=aceesstoken did not work like v2

**Comment by Condebk717** [comment]
I want my api key to be more private, sometimes I see some on the tab web search?

**Comment by thomasvl** [comment]
This library generated helpers for 100+ apis, so we aren't really experts on all of the apis it can work with.  For questions on specific services, you should look at those docs and there help areas for where/how to ask questions.  In the case of drive: https://developers.google.com/drive/api/v3/support
