### ISSUE TITLE
Add instructions to build the Example project

### ISSUE THREAD

**Issue by grantkemp** [google/google-api-objectivec-client-for-rest#19]
I just tried to buidl the example project for Calendar and it generated an error: 

(null): error:XXXXX for rest/Deps/gtm-session-fetcher/Source/GTMSessionFetcher.h: No such file or directory
(null): error:XXXXX for rest/Deps/gtm-session-fetcher/Source/GTMSessionFetcherService.h: No such file or directory
(null): error:XXXXX for rest/Deps/gtm-session-fetcher/Source/GTMSessionUploadFetcher.h: No such file or directory

**Comment by thomasvl** [comment]
How did you pull the sources, it you are pulling directly it uses git submodules to fill in the Deps directory. So if you fetch wasn't recursive, you will be missing the other modules the examples depend on.

**Comment by grantkemp** [comment]
It turned out it was the submodule not coming down.  Hopefully my additions to the readme will prevent that in the future for others. 

Thanks for looking.  Closing this off.
