### ISSUE TITLE
Property Accessor for "userDefined" in GTLRPeopleService_Person

### ISSUE THREAD

**Issue by cturner787** [google/google-api-objectivec-client-for-rest#198]
I've noticed that the property accessor for the userDefined field for GTLRPeopleService_Person seems to be missing. The SDK seems to properly retrieve the property JSON object when adding "userDefined" to the person fields mask and calling PeopleGet, however; it appears as "userDefined?" when printing the description of the Person object.

Will there be an enhancement to add get/set functionality for the userDefined property in the future, to make it easier to handle custom People fields?

**Comment by thomasvl** [comment]
Do you mean https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/PeopleService/GTLRPeopleServiceObjects.h#L1307?  Are you using an old release?

**Comment by cturner787** [comment]
Ah, that's what I was looking for. My bad! I'll update what I've got.
