### ISSUE TITLE
GTLRYouTubeService - absent in cocoapods 

### ISSUE THREAD

**Issue by Briahas** [google/google-api-objectivec-client-for-rest#199]
Hi.
After installing in Swift project **GoogleAPIClientForREST** framework via pods and importing it in via 
`import GoogleAPIClientForREST`
, I cant create an object of **GTLRYouTubeService** class:
`Use of unresolved identifier 'GTLRYouTubeService'`

Any suggestions of what was done wrong?

**Comment by thomasvl** [comment]
Sounds like you are maybe just depending on the `Core` subspec.  There is a subspec for each different service (so you don't get the bloat of linking all services when you only need one) - https://github.com/google/google-api-objectivec-client-for-rest/wiki/BuildingTheLibrary#cocoapods

**Comment by Briahas** [comment]
Yep, you are correct:
`pod 'GoogleAPIClientForREST/YouTube'`
, fixed this issue.
