### ISSUE TITLE
Swift cant see 'authorizer' property in GTLRService.

### ISSUE THREAD

**Issue by Briahas** [google/google-api-objectivec-client-for-rest#200]
Hi.
Cant set **authorizer** property to GTLRYouTubeService object because of the subj.
Look at the screenshot that compare Obj-C header and autogenerated Swift:
http://take.ms/hLIVB

**Comment by thomasvl** [comment]
The issue is around how Swift handles the bridging header, see https://github.com/google/google-api-objectivec-client-for-rest/wiki/BuildingTheLibrary#using-a-swift-bridging-header

**Comment by Briahas** [comment]
Absolutely correct
`#import <GTMSessionFetcher/GTMSessionFetcher.h>		
#import <GTMSessionFetcher/GTMSessionFetcherService.h>`
, in bridging-header saves situation
