### ISSUE TITLE
I have to subscribe channel via my application

### ISSUE THREAD

**Issue by arunpandiyanp** [google/google-api-objectivec-client-for-rest#201]
is this any chance to subscribe youtube channel to my application.i searched lot .but i cannot found any objective c coding to subsribe channel .please refer some example project or coding. thanks

**Comment by thomasvl** [comment]
A quick peek at the YouTube api docs seems to say:
https://developers.google.com/youtube/v3/docs/subscriptions

Which seems to map to:
https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/YouTube/GTLRYouTubeQuery.h#L4916-L5147

**Comment by arunpandiyanp** [comment]
Sorry i am new in ios . https://developers.google.com/youtube/v3/docs/subscriptions/insert#usage  does not has objective c
![screen shot 2018-01-30 at 8 08 24 pm](https://user-images.githubusercontent.com/22564397/35571920-66f88708-05f9-11e8-8020-4fcb6cd8137b.png)

**Comment by thomasvl** [comment]
Their docs may not have it, but the second link I proved was for the generated ObjC for their api that seems to include it.
