### ISSUE TITLE
Batch request for a generic URL like Android?

### ISSUE THREAD

**Issue by meilers** [google/google-api-objectivec-client-for-rest#202]
I'm trying to make a batch request for the Google Maps Geocoding API (https://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452&key=YOUR_API_KEY)

There seems to be an easy way on Android:

```
BatchRequest batch = new BatchRequest(httpTransport, httpRequestInitializer);
batch.setBatchUrl(new GenericUrl(/*your customized batch URL goes here*/));
batch.queue(httpRequest1, dataClass, errorClass, callback);
batch.queue(httpRequest1, dataClass, errorClass, callback);
batch.execute();
```

But I haven't found a way to do it on iOS. What would be the equivalent?

**Comment by thomasvl** [comment]
This library is for the apis that support discovery (https://developers.google.com/apis-explorer/#p/), I don't know that the maps apis you are asking about are in that set.

Information about the Maps iOS SDK can be found at: https://developers.google.com/maps/documentation/ios-sdk/

Scrolling down a bit they list geocoding as a related api (https://developers.google.com/maps/documentation/geocoding/start).

You might want to try asking on the [Maps iOS SDK support area](https://developers.google.com/maps/documentation/ios-sdk/support) if they have a wrapper for the geocoding apis or try the [geocoding api's support page](https://developers.google.com/maps/documentation/geocoding/support).
