### ISSUE TITLE
Unable to Send HTML Rich Message using GTLGmailMessage

### ISSUE THREAD

**Issue by nirajjoshi** [google/google-api-objectivec-client-for-rest#206]
I am using gmail API where I send email using GTLGmailMessage. When I try to send normal Text message by setting it to GTLGmailMessage.raw it's being sent successfully.  

I tried same code with HTML rich content. It's sending mail  successfully but html content source is being displayed in received  email.

Here is my code to prepare raw email body: 

`private func generateRawString() -> String {

let dateFormatter: DateFormatter = DateFormatter()
dateFormatter.dateFormat = "EEE, dd MMM yyyy HH:mm:ss Z"; //RFC2822-Format
let todayString: String = dateFormatter.string(from: Date())

let externalDataSource = self.emailActivity.storedInServerFolder?.forEmailAccount?.externalDataSource
let senderEmail: String = (externalDataSource?.userName)!
let senderName: String = (emailActivity.activityOwner?.leFullName)!

var rawMessage = ""
var bodyText = ""
var bodyHTML = ""

rawMessage = rawMessage + "Date: \(todayString)\r\n"
rawMessage = rawMessage + "From: \(senderName) <\(senderEmail)>\r\n"
rawMessage = rawMessage + addParticipants(with: Constants.ActivityRoleTypes.kKeyActivityTypeEmailRoleTo, roleType: "To: ")
rawMessage = rawMessage + addParticipants(with: Constants.ActivityRoleTypes.kKeyActivityTypeEmailRoleCc, roleType: "Cc: ")
rawMessage = rawMessage + addParticipants(with: Constants.ActivityRoleTypes.kKeyActivityTypeEmailRoleBcc, roleType: "Bcc: ")
rawMessage = rawMessage + "Subject: \((emailActivity.activityName)!)\r\n\r\n"

if let actDesc = emailActivity.activityDescription{
    bodyText = actDesc
    bodyText = bodyText.replacingOccurrences(of: "\n", with: "<br>")
}
if let htmlContent = emailActivity.activityHtmlContent {
    bodyHTML = htmlContent
}

var finalHTMLBody = self.createHTMLBody(bodyText: bodyText, htmlContent: bodyHTML)
finalHTMLBody += "\r\n\r\n" + Constants.PLACE_HOLDERS.kEmailDraftBody

rawMessage = rawMessage + finalHTMLBody

return GTLEncodeWebSafeBase64(rawMessage.data(using: String.Encoding.utf8))
`

This is the reference link for Code I am using to send mail. How send Email using Gmail api in swift
Googled a lot. Is there any encoding/decoding left for html specific part?

**Comment by thomasvl** [comment]
Unfortunately since the library can used with any api that supports vending an api document, it means it supports a lot of services we don't always have direct experience with.  You might want to try the gmail service's support options: https://developers.google.com/gmail/api/support, as those method are more likely to reach people who know the details of the service.

**Comment by nirajjoshi** [comment]
@thomasvl : Thanks for your help. I have already raised this issue/question. Still No help so far...
Here is the link:
https://stackoverflow.com/questions/48821308/how-to-send-html-rich-message-using-gtlgmailmessage
