### ISSUE TITLE
how can i use this without cocoapod

### ISSUE THREAD

**Issue by zhouhuanjie** [google/google-api-objectivec-client-for-rest#208]
I want share a video to youtube in my ios app,but for some reason i don't use cocoapod in my project,so how could i use this library in my ios app.Glad to get reasponse.Thanks.

**Comment by sergiocampama** [comment]
You can download one of the releases from this [page](https://github.com/google/google-api-objectivec-client-for-rest/releases) and add the sources to your project, or if you're using git, you can add this repository as a submodule using `git submodule init && git submodule add https://github.com/google/google-api-objectivec-client-for-rest`

**Comment by thomasvl** [comment]
The wiki has page on building the library into your project: https://github.com/google/google-api-objectivec-client-for-rest/wiki/BuildingTheLibrary
