### ISSUE TITLE
Getting client secret

### ISSUE THREAD

**Issue by grantkemp** [google/google-api-objectivec-client-for-rest#21]
In your Calendar example apps you ask for API Key and Secret, however Google's Api Console only lets us create a client id under creds.  

The documentation for Googles' api also doesn't mention creating secret. 
https://support.google.com/googleapi/answer/6158857?hl=en-GB

Can you add to the documentation how to generate a key and secret specifically so it can be done easily and get the Calendar project working as expected.

**Comment by grantkemp** [comment]
Fixed in this pull request: [BugFix Pull Request](https://github.com/google/google-api-objectivec-client-for-rest/pull/22)
Client Secret is now left blank ( Found on another github library but strangely not easily within the docs in an obvious way. 

If Client Secret has been removed, it might be easier to remove the fields altogether.

**Comment by thomasvl** [comment]
Yea, the docs get a little tricky at time for where to put things, this is documented on the auth modules wiki: https://github.com/google/gtm-oauth2/wiki#registering-your-application
