### ISSUE TITLE
Please provide this api client for rest in swift.

### ISSUE THREAD

**Issue by KDLNiranjan** [google/google-api-objectivec-client-for-rest#210]
I need to get the announcements for the particular class. Where i cant get kGTLRAuthScopeClassroom"Announcements". How to access this even if i use objc header. Please help.

**Comment by loveislife35535** [comment]
Ggdhl of v

**Comment by loveislife35535** [comment]
DJ hv

**Comment by thomasvl** [comment]
I'm not really sure what you are asking.

I'm guessing you are referring to [`kGTLRAuthScopeClassroomAnnouncements`](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/Classroom/GTLRClassroomService.h#L36)

That is an [authorization scope](https://github.com/google/google-api-objectivec-client-for-rest/wiki#authentication-and-authorization).  Generally folks use [GTMAppAuth](https://github.com/google/GTMAppAuth) or [Google Sign-In](https://developers.google.com/identity/sign-in/ios/) for their auth needs.  Both of those have apis when setting things up that take the list of scopes for the server apis calls (queries) you will be making.

**Comment by KDLNiranjan** [comment]
Hi,

My code:
 func fetchAnnouncements() {

        print(courseIdentifier)

        let query =
GTLRClassroomQuery_CoursesAnnouncementsGet.query(withCourseId:
courseIdentifier, identifier: courseIdentifier)

//        query.pageSize = 40

        service.executeQuery(query, delegate: self, didFinish:
#selector(displayAnnouncements(ticket:finishedWithObject:error:)))

    }

    // Process the response and display output
    @objc func displayAnnouncements(ticket: GTLRServiceTicket,
finishedWithObject result : GTLRClassroom_ListAnnouncementsResponse, error
: NSError?) {

        if let error = error {
            showAlert(title: "Error", message: error.localizedDescription)
            return
        }

        guard let courses = result.announcements, !courses.isEmpty else {

            return
        }

       for course in courses {
            // The API field "id" is renamed "identifier" in this library.

            contents.add(courses)

            print(contents)
        }
        announcerTable.reloadData()


    }

But i cant get the course list. I am getting a error: *Request is missing
required authentication credential. Expected OAuth 2 access token, login
cookie or other valid credential.*

Please help me getting the announcement results.

Thanks,

NIRANJANiOS DEVELOPER

M : +91 9566 110493
[image: kutung] <http://kutung.com>
<https://www.linkedin.com/company/kutung-digital>
<https://www.facebook.com/KutungDigital/>

   -

   Sunny Side, 2nd Floor, # 49, 1st Main Road, Gandhi Nagar,

   Adyar, Chennai - 600 020, India
   -

   +91 44 4355 8882
   -

   info@kutung.com
   -

   www.kutung.com <http://kutung.com>

DISCLAIMERS : This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. This message contains confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system.

On Mon, Mar 12, 2018 at 7:59 PM, Thomas Van Lenten <notifications@github.com

**Comment by KDLNiranjan** [comment]
Hi,

My code:
 func fetchAnnouncements() {
      
        print(courseIdentifier)
       
        let query = GTLRClassroomQuery_CoursesAnnouncementsGet.query(withCourseId: courseIdentifier, identifier: courseIdentifier)
       
//        query.pageSize = 40
       
        service.executeQuery(query, delegate: self, didFinish: #selector(displayAnnouncements(ticket:finishedWithObject:error:)))
       
    }
   
    // Process the response and display output
    @objc func displayAnnouncements(ticket: GTLRServiceTicket, finishedWithObject result : GTLRClassroom_ListAnnouncementsResponse, error : NSError?) {
       
        if let error = error {
            showAlert(title: "Error", message: error.localizedDescription)
            return
        }
       
        guard let courses = result.announcements, !courses.isEmpty else {
          
            return
        }
       
       for course in courses {
            // The API field "id" is renamed "identifier" in this library.
       
            contents.add(courses)
           
            print(contents)
        }
        announcerTable.reloadData()
       
     
    }

But i cant get the course list. I am getting a error: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid credential.

Please help me getting the announcements.

**Comment by thomasvl** [comment]
You likely need to be signed in, see [Authentication and Authorization](https://github.com/google/google-api-objectivec-client-for-rest/wiki#authentication-and-authorization) about using one of the two mentioned libraries to provide an Authorizer to the Service.
