### ISSUE TITLE
Is this library in maintenance mode?

### ISSUE THREAD

**Issue by 0joshuaolson1** [google/google-api-objectivec-client-for-rest#211]
The other clients either state they're in maintenance mode, are in beta, or are PHP.

**Comment by thomasvl** [comment]
> The other clients either state they're in maintenance mode, are in beta, or are PHP.

I can't figure out what _PHP_ refers to compared to _maintenance mode_ or _beta_?

This library is generally usable and does get updates as issues come up.  Somewhat regularly we regenerate the code for the public services so they can be used without developers having to generate the code themselves.

**Comment by 0joshuaolson1** [comment]
Great. By PHP I meant the [library for that language](https://github.com/google/google-api-php-client) is neither beta nor maintain-only.

So it looks like this one and that one are the most 'official' clients at this point. If that's correct, please close.

Thank you!
