### ISSUE TITLE
youtube resumable upload  "Invalid Credentials"

### ISSUE THREAD

**Issue by zhouhuanjie** [google/google-api-objectivec-client-for-rest#213]
when i send this request to host  "https://www.googleapis.com/upload/youtube/v3/videos",i get error. show "Invalid Credentials".
and i use GTMAppAuth library to get Authorization token from (OIDAuthState *)authState.lastTokenResponse.accessToken.
here is the code.

NSString *graphPath = @"https://www.googleapis.com/upload/youtube/v3/videos";
    
    NSMutableDictionary *parameters = [NSMutableDictionary new];
    
    [parameters setObject:@"resumable" forKey:@"uploadType"];
    
    NSMutableDictionary *dicSnippet =[NSMutableDictionary new];
    [dicSnippet setObject:@"title" forKey:@"title"];
    [dicSnippet setObject:@"description" forKey:@"description"];
    [dicSnippet setObject:@"22" forKey:@"categoryId"];
    [dicSnippet setObject:@[@"cool", @"video", @"more keywords"] forKey:@"tags"];
    [dicSnippet setObject:@"1" forKey:@"channelId"];
    
    [parameters setObject:dicSnippet forKey:@"snippet"];
    
    NSMutableDictionary *dicStatus =[NSMutableDictionary new];
    [dicStatus setObject:@"public" forKey:@"privacyStatus"];
    [dicStatus setObject:@"True" forKey:@"embeddable"];
    [dicStatus setObject:@"youtube" forKey:@"license"];
    
    [parameters setObject:dicStatus forKey:@"status"];
    
    NSMutableURLRequest *request = [[AFHTTPRequestSerializer serializer] multipartFormRequestWithMethod:@"POST" URLString:graphPath parameters:parameters constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        NSString *fileMimeType = @"video/*";
        NSError *error;
        [formData appendPartWithFileURL:[NSURL URLWithString:videoUrl] name:@"video" fileName:@"" mimeType:fileMimeType error:&error];
        if(error)
            NSLog(@"Error: %@",error);
    } error:nil];
    NSLog(@"request:%@",request);
    NSString *token = [[NSUserDefaults standardUserDefaults] objectForKey:YoutubeAccessTokenKey];
    if (token.length > 0) {
        [request setValue:token forHTTPHeaderField:@"Authorization"];
    }

**Comment by thomasvl** [comment]
So it doesn't look like you are using this project at all.  You seem to be hand building your requests and doing your own networking.  My guess is that last few lines pulling a `token` out of `NSUserDefaults` is likely your problem.  Normally `GTMAppAuth` can wrap things, and provide a token on demand with requests because you have to refresh your token every so often.

If you use this library, it supports an `authorizer` model, where you set one that you get from `GTMAppAuth` and the library takes care of adding the information for you.

If you want to got with building the requests yourself but still use `GTMAppAuth` for token management, you likely want to follow up with that project for how to bet go about it.  If you want to bypass `GTMAppAuth`, you might have to dig much more into the OAuth2 specs to understand everything involved you manual refresh/etc. your token and provide them on each request.

**Comment by zhouhuanjie** [comment]
@thomasvl 
Thanks for response
I guess it was token's problem too,but i don't know how to resovle it.
I can upload a video to youtube using this library with GTMAppAuth.But than's not what i want;
I want upload resumable video to youtube using http. Follow with this: [https://developers.google.com/youtube/v3/guides/using_resumable_upload_protocol](url)

but i don't know how to get the auth token, since the accessToken from GTMAppAuth is not correct.
here is the descpribe in youtube doc:

post /upload/youtube/v3/videos?uploadType=resumable&part=parts http/1.1
host: www.googleapis.com
authorization: bearer auth_token
content-length: content_length
content-type: application/json; charset=utf-8
x-upload-content-length: x_upload_content_length
X-Upload-Content-Type: X_UPLOAD_CONTENT_TYPE
video resource

**Comment by debutdeveloper** [comment]
I am also trying to upload video with resumable session with my own token, and i wanna bypass GTMAppAuth. I have created my appropriate token response with my own data but it looks the upload ticket need the request too, for uploading process.

**Comment by thomasvl** [comment]
The [`authorizer`](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Objects/GTLRService.h#L275) is just protocol based, any class that confirms to the protocol ([`GTMFetcherAuthorizationProtocol `](https://github.com/google/gtm-session-fetcher/blob/master/Source/GTMSessionFetcher.h#L639-L678))can be used.  If the token needs refreshing during the upload, the object will get called back to do so.
