### ISSUE TITLE
Google authentication issue on the latest macOS update

### ISSUE THREAD

**Issue by andy61i** [google/google-api-objectivec-client-for-rest#222]
**Setup**
macOS Sierra 10.12.6 (16G1314) OR macOS High Sierra 10.13.4 (17E199)
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Pods**
  - GoogleAPIClientForREST (1.3.4)
  - GoogleAPIClientForREST/Core (1.3.4)
  - GoogleAPIClientForREST/Drive (1.3.4)
  - GoogleAPIClientForREST/Oauth2 (1.3.4)
  - GTMAppAuth (0.7.0)
  - GTMSessionFetcher (1.1.15)
  - GTMSessionFetcher/Core (1.1.15)
  - GTMSessionFetcher/Full (1.1.15)

**Problem**
The following  authentication code worked well before the latest macOS update:
```
#define CLIENT_ID @"382239646343-0elsgpt33tkmvod7pgdc8qbn6e9sn169.apps.googleusercontent.com"
#define CLIENT_SECRET @"deleted"
#define REDIRECT_URI @"com.googleusercontent.apps.382239646343-0elsgpt33tkmvod7pgdc8qbn6e9sn169:/oauthredirect"
#define DRIVE_SCOPE @"https://www.googleapis.com/auth/drive"

OIDServiceConfiguration* configuration = [GTMAppAuthFetcherAuthorization configurationForGoogle];
    OIDAuthorizationRequest *request = [[OIDAuthorizationRequest alloc] initWithConfiguration:configuration
                                                                                     clientId:CLIENT_ID
                                                                                 clientSecret:CLIENT_SECRET
                                                                                       scopes:@[DRIVE_SCOPE]
                                                                                  redirectURL:[NSURL URLWithString:REDIRECT_URI]
                                                                                 responseType:OIDResponseTypeCode
                                                                         additionalParameters:nil];
    self.authorizationFlow = [OIDAuthState authStateByPresentingAuthorizationRequest:request
                                                                            callback:^(OIDAuthState * _Nullable authState, NSError * _Nullable error) {
        if (authState) {
            GTMAppAuthFetcherAuthorization* authorization = [[GTMAppAuthFetcherAuthorization alloc] initWithAuthState:authState];
            self.service.authorizer = authorization;
            ...
        } else {
            self.service.authorizer = nil;
            ...
        }
    }];
```

Since the update there is a problem:
- Chrome starts and offer to select a Google account => Select one
- Appears a page to allow access to Google Drive files => Allow
- A popup appears with a query to start the app initiated this authentication

<img width="626" alt="popup" src="https://user-images.githubusercontent.com/635819/38863318-e5b68bf8-423f-11e8-9743-b5a5ded9cbe8.png">

Then there are 3 possible scenarios:
1. Wait a couple of seconds. The underling "allow access page" will automatically forwards to Google Search (as on the screen above). Then pressing "Open SafeInCloud Password Manager" will do nothing.
2. Be quick and press "Open" button immediately. Then authentication will work.
3. If the "Always open these type of links" checkbox was pressed in scenario 1 (on previous macOS build) or in scenario 2, then authentication will work automatically.

So, the problem is this autoforwarding from the "allow access page" to Google Search pages.

**Testing**
The app to test problem: 
[https://www.safe-in-cloud.com/download/beta/SafeInCloud.dmg](https://www.safe-in-cloud.com/download/beta/SafeInCloud.dmg)
Steps to reproduce:
- Start the app
- Select 'Restore database from a cloud'
- Select 'Google Drive'

**Comment by thomasvl** [comment]
Anything around the auth flows is going to be with the code in GTMAppAuth or AppAuth itself, not this library for the SessionFetcher.  So you might want to reopen this on one of those projects so other folks that see similar issues can more easily find the issue.

In the mean time, paging @WilliamDenniss for any ideas.

**Comment by andy61i** [comment]
It is not a hijack thing. It's a BUG thing)) I am a developer of SafeInCloud Password Manager app with user base of over 300K people on Mac, Windows, Android and iOS platforms. Recently I started receiving user complains about Google Drive authentication on the latest macOS update. I investigated the problem and reported here, because the bug cannot be fixed on the app's side - it is somewhere in GoogleAPIClientForREST or GTMAppAuth as you suggested.

**Comment by andy61i** [comment]
I also reported this issue to GTMAppAuth:
[https://github.com/google/GTMAppAuth/issues/67](https://github.com/google/GTMAppAuth/issues/67)
and AppAuth-iOS:
[https://github.com/openid/AppAuth-iOS/issues/231](https://github.com/openid/AppAuth-iOS/issues/231)

**Comment by StevenEWright** [comment]
Does this help? https://github.com/openid/AppAuth-iOS#bulb-alternative-custom-uri-schemes

Let's follow up on the AppAuth page. I suggest we close this issue. TL;DR: this is working "as expected", the AppAuth docs discuss it, and also provide a solution.

**Comment by thomasvl** [comment]
Closing this since it looks like discussion is moved to the AppAuth-iOS project.
