### ISSUE TITLE
In the wiki it mentions using Google Sign In as an approach but no method is shown

### ISSUE THREAD

**Issue by grantkemp** [google/google-api-objectivec-client-for-rest#23]
In the wiki, you mention that its possible to use Google Sign In to connect to one of the services, but this doesn't seem to be documented clearly in the various google projects, let alone in a single Github example. ( Please correct me if I am wrong) 

If not, it would be really useful to have a simple example that shows the power of the new Google Sign in flow and this library to connect to something simple like the analytics reporting api. 

If above is possible, would be great to get some guidance, on how it works once I have the token and creds via the Google Sign in library , and I will be happy to contribute the the project example back to this for others to use.

**Comment by thomasvl** [comment]
That SDK is by a different set of folks within the company, so we don't have direct experience with it.  They do expose a [authorizer](https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_authentication.html#a4bae2b2c1dacae3419014e8981b64088) that can be set on a GTLRService.  But yes, it is one of the things we'll likely look at adding more info on in the future.

**Comment by grantkemp** [comment]
Cool - I will have a bash at it, and share how far I get.

**Comment by ubragg** [comment]
FYI, I was able to use the authorizer exposed by the Google Sign-In library and everything seemed to work.  It seems that it is just another way (with its own quirks) to do exactly the same thing as the new GTMAppAuth library, so ideally those two would converge.

**Comment by nawar** [comment]
Is it possible to get some Wiki update on this?
@ubragg how did you manage to do that?

**Comment by nawar** [comment]
I found a way to make it work, I'd love some feedback if this is the right way to approach it. 

```Swift
fileprivate let calendarScope : [String] = ["https://www.googleapis.com/auth/calendar", "https://www.googleapis.com/auth/calendar.readonly"]
fileprivate var calendarService : GTLRCalendarService?

fileprivate func setCalendarService() {
        
        if calendarService != nil {
            return
        }
        
        let service = GTLRCalendarService()
        // Have the service object set tickets to fetch consecutive pages
        // of the feed so we do not need to manually fetch them
        service.shouldFetchNextPages = true
        // Have the service object set tickets to retry temporary error conditions
        // automatically
        service.isRetryEnabled = true
        
        // Setup the authorizer
        let auth = GTMOAuth2Authentication()
        guard let user = GIDSignIn.sharedInstance().currentUser else {
            print(#function + " error - No user found")
            return
        }
        auth.scope = calendarScope.joined(separator: " ")
        auth.clientID = clientID
        auth.clientSecret = nil
        auth.userEmail = user.profile.email
        auth.userID = user.userID
        auth.accessToken = user.authentication.accessToken
        auth.refreshToken = user.authentication.refreshToken
        auth.expirationDate = user.authentication.accessTokenExpirationDate
        service.authorizer = auth
        
        // setup
        calendarService = service
 }

```
Then we call `setCalendarService()` before any query.

**Comment by thomasvl** [comment]
See my comment on Aug 15, 2016; they seem to expose a `fetcherAuthorizer` that you should be able to set as the `service.authorizer`.

As far as more info on the wiki here; I'm hesitant to add wiki info here documenting other projects as it is something else to track/maintain as those things change.  😦 

Re GTMAppAuth vs. Google Sign-In library, yes, I've talked a little to them about trying to get the two things to converge to reduce the confusion.

**Comment by raiha7** [comment]
Will give it ago

**Comment by sharpfive** [comment]
If you're trying the above technique in a Swift app you'll want to read this thread: https://groups.google.com/forum/#!topic/google-api-objectivec-client/bNIipVqGz2c
