### ISSUE TITLE
Setting up caching with Google Drive API fetch

### ISSUE THREAD

**Issue by hugofalkman** [google/google-api-objectivec-client-for-rest#232]
Am using the GTLRService method request(for: GTLRQuery) to generate a URLRequest. Then invoking fetcher(with: URLRequest) works fine to download a Google Drive API fileId.

But I would like to use a URLSession dataTask(with: URLRequest) for the download to do caching using URLProtocol and URLSessionDataDelegate. 

The comments in the source code of the request(for: GTLRQuery) method say: "For requests to non-public resources, the request will not yet be authorized;  that can be done using the GTLR service's authorizer."

I guess I might use the GTLRQuery additionalHTTPHeaders method to add the authorization to the URLRequest, but is it documented anywhere how to create the header from a GTMFetcherAuthorizationProtocol object?

Please if at all possible respond using Swift terminology, my objc knowledge is minimal.

**Comment by thomasvl** [comment]
Sounds like your question is more about GIDSignIn usage since you are using that for your own manual requests.  But since they conform to `GTMFetcherAuthorizationProtocol`, you should be able to just use the method it provides: https://github.com/google/gtm-session-fetcher/blob/master/Source/GTMSessionFetcher.h#L643-L645.  I'm not sure if they offer any other wrappers over that.

**Comment by hugofalkman** [comment]
Thanks. Tried both the selector and completion handler versions of the authorizer authorizeRequest method but can't see that it actually updated the URLRequest. Google Drive certainly didn't accept the (updated?) request.

BUT in the comments header of GTMSessionFetcher.h there was a section on caching. So the following code was all that was required to have a working Google Drive API with caching, which was all I needed. (Changed the issue heading accordingly.)

    fetcher.configuration = .default
    fetcher.configurationBlock = { (fetcher, config) in
        config.urlCache = URLCache(
            memoryCapacity: 0,
            diskCapacity: 200 * 1024 * 1024,
            diskPath: "magic")
        config.requestCachePolicy = .returnCacheDataElseLoad
        config.timeoutIntervalForRequest = 30
    }

**Comment by thomasvl** [comment]
> Thanks. Tried both the selector and completion handler versions of the authorizer authorizeRequest method but can't see that it actually updated the URLRequest. Google Drive certainly didn't accept the (updated?) request.

So the completion block got called without it updating the request?  That surprises me and sounds worth of an issue opened against GIDSignIn.
