### ISSUE TITLE
I can not copy folders.

### ISSUE THREAD

**Issue by paveway** [google/google-api-objectivec-client-for-rest#252]
Previously, I was able to copy folders.
But now this message is displayed and I can not copy the folder.
How can I copy a folder?

Error message: This file can not be copied by the user.

With the same process, I can copy files.

**Comment by thomasvl** [comment]
Sorry, not really sure if this a build issue or maybe some api issue, so we can't really do much to try to offer much help.  Can you provide more details about what you are doing and what is failing?

**Comment by paveway** [comment]
Copy the file or folder using GTLRDriveQuery_FilesCopy.
When copying, specify the ID of the copy destination folder in the CopyFile method and execute it.

I can still copy files with this method.
Previously, I could copy folders with this method.
However, I can not copy folders with this method now.

I am using GTMAppAuth for authentication.
I have specified "https://www.googleapis.com/auth/drive" as the scope.

I extract excerpts related to copying.

I omit processing related to authentication.
If necessary, I will post it later.

- Development environment

Xcode 10
Swift 4.2

- Podfile

...
pod 'GoogleAPIClientForREST/Drive'
pod 'GTMAppAuth'
...

- AppDelegate.swift

```swift
class AppDelegate: UIResponder, UIApplicationDelegate {

    let googleDriveServiceDrive = GTLRDriveService()

    ...
}
```

- GoogleDriveFileCopyViewController.swift

```swift
class GoogleDriveFileCopyViewController: UIViewController {

    ...

    /**
     Copy file or folder

     @param srcFile: Copy source file or folder object
     @param destId: Copy destination folder ID
     */
    func copyFile(_ srcFile: GTLRDrive_File, destId: String) {
        guard let srcId = srcFile.identifier else {
            return
        }

        guard let name = srcFile.name else {
            return
        }

        let copyFile = GTLRDrive_File()
        copyFile.name = name
        copyFile.parents = [destId]

        let query = GTLRDriveQuery_FilesCopy.query(withObject: copyFile, fileId: srcId)
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        let serviceDrive = appDelegate.googleDriveServiceDrive
        serviceDrive.executeQuery(query, completionHandler: { (ticket: GTLRServiceTicket?, updatedFile: Any?, error: Error?) -> Void in
            if let error = error {
                return
            }

            // Below, processing in case of success
            ...
        })
    }
}
```

**Comment by thomasvl** [comment]
[HTTP Logging](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) might help in that it will capture what is being send/received.  The details within the error are likely what will help.

Is this the same folders you tried to copy before that are now failing?  Have the permissions on the folders been changed?  i.e. - maybe the owner has changed things?

It also sounds like this is going to be a general issue with the drive api, and not specific to the ObjC library, so you might want to check out there [support options](https://developers.google.com/drive/api/v3/support).  The HTTP Log will be useful for helping provide them details of what is being sent and what isn't working.
