### ISSUE TITLE
Don't quite understand the didFinish selector in executeQuery

### ISSUE THREAD

**Issue by JustusWest** [google/google-api-objectivec-client-for-rest#258]
I'm trying to make an iOS app that reads and writes data from the Google Sheets API. I've implemented login successfully but am having trouble with executeQuery. Using Swift 4 and Xcode 10.
My code
```Swift
func readSchedule(with params: String,
                      then: ((scheduleWeek) -> Void)?,
                      fail: ((Error) -> Void)?) {
        let service = GTLRSheetsService()
        let spreadsheetId = //hardcoded sheet id here
        let range = params
        let query = GTLRSheetsQuery_SpreadsheetsValuesGet
            .query(withSpreadsheetId: spreadsheetId, range:range)
        service.executeQuery(query,
                             delegate: self,
                             didFinish: #selector(displayResultWithTicket(ticket:finishedWithObject:error:))
        )
        print("After query") // Executes this print
        
    }
    
    // Not sure how format this function properly.
    @objc func displayResultWithTicket(ticket: GTLRServiceTicket,
                                       finishedWithObject result : GTLRSheets_ValueRange,
                                       error : NSError?) {
        print(result)                //Never executes this print
        print("After result print") //Never executes this print
    }
```
When I call the readSchedule function in my viewController it prints "After query" so that function is being reached, but the prints in displayResultWithTicket never execute, so I assume it is not reaching that function?

**Comment by thomasvl** [comment]
What thread do you start the query from?

You mentioned you had login done, but I don't see anything in the snipped setting the `authorizer` on your service?  Normally, something will own the `GTLRSheetsService` and set the authorizer on it, so all queries executed with it will then have the needed credentials.  It could also be that you have the service as a local here, so it is getting released before the query can complete.

**Comment by JustusWest** [comment]
I managed to resolve the issue on my own. I hadn't set the needed credentials so the query was failing. Once I added the authorizer and key it worked fine. Thanks for the reply!
