### ISSUE TITLE
Unclear instructions on how to use the Examples

### ISSUE THREAD

**Issue by nowakca** [google/google-api-objectivec-client-for-rest#260]
https://github.com/google/google-api-objectivec-client-for-rest/tree/master/Examples  says I need to download two submodules, then names 3 submodules.

It doesn't say where to download them to, how to establish the dependencies, etc.  (If I wanted to build the Youtube sample for Mac OS (which I do), how would I proceed, for example)

Also, not being familiar with submodules, I'm not clear why I'd need to clone then as a separate step, pull.

It's also a bit disconcerting to launch a project, be presented with warnings immediately, and after XCode resolves them, end up with fatal errors that aren't related to Google Project identification stuff.

Is there somewhere that has a reasonably easy to follow example of how to access youtube?

**Comment by thomasvl** [comment]
Sorry about that, hopefully that provides better pointers.
