### ISSUE TITLE
How to build for iOS Simulator

### ISSUE THREAD

**Issue by fruxo-** [google/google-api-objectivec-client-for-rest#269]
Hi,
I’m looking for instructions on how to build GTLR for iOS simulator.

I am building for iOS by running:
```
1. google-api-objectivec-client-for-rest/Source $ xcodebuild clean
2. google-api-objectivec-client-for-rest/Source $ xcodebuild -target GTLRiOSCore
```
which results into:
```
3. google-api-objectivec-client-for-rest/Source $ file build/Release-iphoneos/GTLR.framework/GTLR 
build/Release-iphoneos/GTLR.framework/GTLR: Mach-O universal binary with 2 architectures: [arm_v7:Mach-O dynamically linked shared library arm_v7] [arm64]
build/Release-iphoneos/GTLR.framework/GTLR (for architecture armv7):        Mach-O dynamically linked shared library arm_v7
build/Release-iphoneos/GTLR.framework/GTLR (for architecture arm64):        Mach-O 64-bit dynamically linked shared library arm64
```

Then I add the generated ``GTLR.framework`` folder (taken from ``build/Release-iphoneos/GTLR.framework``) to my project, run it on a real device and it all works just fine.

However I have not found a way to generate the same framework for running on the simulator.
I’ve tried with ``xcodebuild -target GTLROSXCore``, installed the resulting framework under my app, built it, but when it comes to installation on the Simulator the following error shows up:
```
Failed to load Info.plist from bundle at path […]/Developer/CoreSimulator/Devices/<UUID>/data/Library/Caches/…/<MyApp>/Frameworks/GTLR.framework
```

Any suggestion, please?

**Comment by fruxo-** [comment]
I seem to have resolved this by running:
```
google-api-objectivec-client-for-rest $ ./Tests/xcode_tests.sh iOSCore Release
```
which results into:
```
file .../Library/Developer/Xcode/DerivedData/GTLRCore-fuypvkjjhycxdafvxmfjdmtwzdve/Build/Products/Release-iphonesimulator/GTLR.framework/GTLR
.../Library/Developer/Xcode/DerivedData/GTLRCore-fuypvkjjhycxdafvxmfjdmtwzdve/Build/Products/Release-iphonesimulator/GTLR.framework/GTLR: Mach-O universal binary with 2 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64]
.../Library/Developer/Xcode/DerivedData/GTLRCore-fuypvkjjhycxdafvxmfjdmtwzdve/Build/Products/Release-iphonesimulator/GTLR.framework/GTLR (for architecture i386):      Mach-O dynamically linked shared library i386
.../Library/Developer/Xcode/DerivedData/GTLRCore-fuypvkjjhycxdafvxmfjdmtwzdve/Build/Products/Release-iphonesimulator/GTLR.framework/GTLR (for architecture x86_64):    Mach-O 64-bit dynamically linked shared library x86_64
```

Would you agree with this solution is there another way, possibly the same way for both the Simulator and the iOS framework generation?

Thanks.

**PS:** it’d be great if this was also documented in the wiki/

**Comment by thomasvl** [comment]
This seems to be a little more about how to use Xcode and `xcodebuild` than anything specific to this library.  `man xcodebuild` will give you an introduction to the command line args, generally speaking, Xcode uses a model where the sdk needed is different for the simulator vs. the devices, so you need to use `-sdk iphoneos` vs. `-sdk iphonesimulator`.

The `xcode-tests.sh` script is for running our tests on CI, so we don't really make any claims that this is going to set things up for integration.
