### ISSUE TITLE
iOS Embedded Framework: image not found error

### ISSUE THREAD

**Issue by JonasGessner** [google/google-api-objectivec-client-for-rest#27]
I've tried adding the framework to an iOS app and apparently the framework isn't copied over to the device? I get a dyld error:

```
dyld: Library not loaded: @loader_path/../Frameworks/GTLR.framework/GTLR
  Referenced from: /var/containers/Bundle/Application/87B4187F-D9FC-40D6-BE4A-4541B848E163/Test.app/Test
  Reason: image not found
```

I've created a new project from scratch and only added the GTLR project, added the framework to `Embedded Binaries` and added `-DGTLR_USE_FRAMEWORK_IMPORTS=1` to other linker flags. It's very strange because normally the error occurs when you're not properly adding a framework to the embedded binaries but I definitely did that. The framework is built and even added to the .app but I still get the dyld error. Xcode 8b6.

<img width="398" src="https://cloud.githubusercontent.com/assets/1156152/17783987/f24b2b2e-657a-11e6-8e8a-4fd35399370b.png">

Another thing I noticed: Skip Install is set to `NO`. It should be `YES`, otherwise you can't properly archive an app to submit it to the App Store.

**Comment by thomasvl** [comment]
The `..` in `loader_path/../Frameworks/GTLR.framework/GTLR` looks a little odd as that usually is what you get for a macOS binary (because the app goes in a `MacOS` directory within the binary).  Are you sure you are trying to get the iOS framework and not the macOS one?

**Comment by thomasvl** [comment]
Actually, looks like we might have the setting wrong in the project for the iOS case, try fixing that to drop the `..` and see how things go.

**Comment by JonasGessner** [comment]
Yeah It's the iOS framework not the OS X one. The Target is just messed up. I created a blank Cocoa Touch Framework target, added all the files and it works just fine. You'll probably want to delete the iOS target and create a new one from scratch.

**Comment by JonasGessner** [comment]
I just read your second comment, I tried dropping the `..` and it's working! Thanks for the quick help! And please also set skip install to true in your next commit :)

**Comment by thomasvl** [comment]
Will do. Feel free to send in a PullRequest if you want.
