### ISSUE TITLE
Google Photos API - any plan to integrate?

### ISSUE THREAD

**Issue by xaphod** [google/google-api-objectivec-client-for-rest#274]
Related to this from 3 years ago - 
https://github.com/google/google-api-objectivec-client-for-rest/issues/8

Is there a plan to add the Google Photos API to this project? We just got accepted as a Photos partner and want to get going but would really love to use this project instead of writing lots of this code ourselves. We already use this project for Gmail and Drive integrations - keep up the great work.

**Comment by thomasvl** [comment]
At this library level, we don't really have visibility into the server teams plans.  If they have a help/feedback section for the program, I'd suggest asking there as they will hopefully be able to more directly answer.

**Comment by xaphod** [comment]
Hi @thomasvl I'm confused -- the Google Photos team already has a REST API published at https://developers.google.com/photos/library/reference/rest/ with a Discovery Document. 
Are you saying that there's more needed from the Photos server team before this library can build support for it?

**Comment by thomasvl** [comment]
Interesting.  Apparently it isn't [listed is discovery](https://www.googleapis.com/discovery/v1/apis?name=photoslibrary), so it doesn't show up in the [API Explorer](https://developers.google.com/apis-explorer/#p/)

Until they list it, you can always generate from that discovery document yourself.

**Comment by thomasvl** [comment]
PS - I filed a bug internally against them to try and get them listed in discovery/api explorer.

**Comment by xaphod** [comment]
Thanks for filing the bug, bonus points if you comment/close back here when it gets fixed :)
I managed to generate from the discovery doc as you mentioned, neato. 
Steps for others:

1. Grab a copy of this repo, and also make sure [GTMSessionFetcher](https://github.com/google/gtm-session-fetcher) under `Deps` (you can see the empty folder already where its root should be)
2. open `Source/Tools/ServiceGenerator/ServiceGenerator.xcodeproj`, build (it will fail if you didn't put GTMSessionFetcher in the right place), and copy the binary you built from XCode's left pane -> Products to somewhere you can run it
3. Save the JSON contained at the [Google photos discovery doc](https://photoslibrary.googleapis.com/$discovery/rest?version=v1) in the same folder as the binary of the ServiceGenerator
4. Drop to terminal, get to the folder where the binary is, make a subfolder called `out`, and run this: `./ServiceGenerator --outputDir ./out ./rest.json`

If successful it'll generate a bunch of files in `./out/`. I was able to add these into my main project manually without a problem: they are able to reference what they need from the rest of this repo if you're using it in a Pod like I am.

**Comment by thomasvl** [comment]
Apparently not listing it is be design by the team because they say some client libraries don't fully support things.  So generating yourself as long as the api you need work seems to be the option for ObjC at the moment.

**Comment by xaphod** [comment]
Ok thanks for letting me know.

**Comment by JcChimjj** [comment]
#247

**Comment by jonnyijapan** [comment]
> Interesting. Apparently it isn't [listed is discovery](https://www.googleapis.com/discovery/v1/apis?name=photoslibrary), so it doesn't show up in the [API Explorer](https://developers.google.com/apis-explorer/#p/)
> 
> Until they list it, you can always generate from that discovery document yourself.

https://www.googleapis.com/discovery/v1/apis?name=photoslibrary

This API gives

```
{
 "kind": "discovery#directoryList",
 "discoveryVersion": "v1"
}
```

Does it mean it's fixed?

**Comment by thomasvl** [comment]
No, that's an empty list, compare it to something like https://www.googleapis.com/discovery/v1/apis?name=discovery that actually returns an entry also.

**Comment by jonnyijapan** [comment]
> If successful it'll generate a bunch of files in `./out/`. I was able to add these into my main project manually without a problem: they are able to reference what they need from the rest of this repo if you're using it in a Pod like I am.

Thanks for this. I was able to follow these instructions, but I had to add the Source/Objects/* classes into my project for the generated GTLRPhotosLibrary* classes to build.
