### ISSUE TITLE
GTLR. Framework and Google SignIn Dependencies. Framework File Conflict

### ISSUE THREAD

**Issue by MMSuperD** [google/google-api-objectivec-client-for-rest#276]
We also use GTLR. framework (static library generated from: google/google-api-objectivec-client-for-rest), Google SignIn. framework (static library), Google SignIn Dependencies. framework (static library) to create file conflicts.

The conflict documents are as follows:

Duplicate symbol_OBJC_IVAR_$_GTMSession Upload Fetcher. _isPaused in:

/ Users/sh-lx/Downloads/SSCA(Google

/ Users/sh-lx/Downloads/SSCA (Google

Duplicate symbol_OBJC_IVAR_$_GTMSession Upload Fetcher. _isRestarted Upload in:

/ Users/sh-lx/Downloads/SSCA(Google

/ Users/sh-lx/Downloads/SSCA (Google

Duplicate symbol_OBJC_IVAR_$_GTMSession Upload Fetcher. _uploadData in:

/ Users/sh-lx/Downloads/SSCA(Google

/ Users/sh-lx/Downloads/SSCA (Google

Duplicate symbol_OBJC_IVAR_$_GTMSession Upload Fetcher. _uploadLocation URL in:

/ Users/sh-lx/Downloads/SSCA(Google

/ Users/sh-lx/Downloads/SSCA (Google

Duplicate symbol_OBJC_IVAR_$_GTMSession Upload Fetcher. _uploadFileURL in:

/ Users/sh-lx/Downloads/SSCA(Google

/ Users/sh-lx/Downloads/SSCA (Google

Duplicate symbol_OBJC_IVAR_$_GTMSession Fetcher. _challengeBlock in:

/ Users/sh-lx/Downloads/SSCA(Google

/ Users/sh-lx/Downloads/SSCA(Google

Duplicate symbol_OBJC_IVAR_$_GTMSession Fetcher. _initial Begin FetchDate in:

/ Users/sh-lx/Downloads/SSCA(Google

/ Users/sh-lx/Downloads/SSCA(Google

Ld: 172 duplicate symbols for architecture armv7

Clang: error: linker command failed with exit code 1 (use-v to see invocation)

Wait

Ask for advice

**Comment by thomasvl** [comment]
Sounds like you are getting two copies of the GTMSessionFetcher, the Xcode project in this project bundles the SessionFetcher to help folks just using it, you'll need to remove those sources if you are getting that library via some other package.
