### ISSUE TITLE
Sheets GTLRSheetsQuery_SpreadsheetsValuesBatchGet

### ISSUE THREAD

**Issue by nelselima** [google/google-api-objectivec-client-for-rest#285]
Hey!

Could figure out if this is an issue or just me not figuring out how to properly use the API.

Looking at the Spreadsheet get method and comparing with the Batchget, I've noticed that the GTLRSheetsQuery_SpreadsheetsValuesBatchGet.query(...) method accepts only one parameter which is the spreadsheetId.

Tried the additionalURLQueryParameters but this is a [String : String] dict, how could an array of Strings (containing the several ranges for the batchget) be passed through?

Thanks!

**Comment by thomasvl** [comment]
The method to create the query object (`GTLRSheetsQuery_SpreadsheetsValuesBatchGet`) only takes the required arguments, the `spreadsheetId` in this case, but there are several other parameters defined on the object for the optional parameters.  You likely should read over all the properties on the class - https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/Sheets/GTLRSheetsQuery.h#L685-L730, not just the ones to the creation method.

**Comment by nelselima** [comment]
Hi Thomas!

Thank you for your help!

How could the other properties be set?
I couldn't access the `ranges` property and got no luck using the property `@property(atomic, copy, nullable) NSDictionary<NSString *, NSString *> *additionalURLQueryParameters;` for the ranges (I've successfully used this for `valueRenderOption`).

Kind regards!

**Comment by thomasvl** [comment]
> I couldn't access the `ranges` property

Why?  What's the error?

**Comment by nelselima** [comment]
Sure!

Accessing ranges property directly:
```
let sheetsQuery: GTLRSheetsQuery = GTLRSheetsQuery_SpreadsheetsValuesBatchGet.query(withSpreadsheetId: spreadsheetId)

sheetsQuery.ranges = [["Sheet1!A1:A10", "Sheet1!G1:G10"]]
```
Error: "Value of type 'GTLRSheetsQuery' has no member 'ranges' "

Setting using additionalURLQueryParameters is not possible because it's a `[String : String]` dictionary and ranges is a `[String]`

**Comment by thomasvl** [comment]
Why are you forcing the type down to `GTLRSheetsQuery`?  Let the Swift compiler infer the type or use the correct specific type:

```
let sheetsQuery =
    GTLRSheetsQuery_SpreadsheetsValuesBatchGet.query(withSpreadsheetId: spreadsheetId)
```

or

```
let sheetsQuery: GTLRSheetsQuery_SpreadsheetsValuesBatchGet =
    GTLRSheetsQuery_SpreadsheetsValuesBatchGet.query(withSpreadsheetId: spreadsheetId)
```

Since you are forcing it to the more generic type you are preventing yourself from using the added properties.

**Comment by nelselima** [comment]
Right... my bad...
Sorry for wasting your time and thank you once again!
