### ISSUE TITLE
How can I return the result of a “GTLRSheetsQuery_SpreadsheetsValuesGet” query after it finishes execution (Swift using Sheets API)?

### ISSUE THREAD

**Issue by sid32502** [google/google-api-objectivec-client-for-rest#292]
I'm trying to create an inventory management app for iOS using Swift and the Google Sheets API. Before starting that, I want to get acquainted with the API and make sure everything works properly. To do that, I want to create a function getCell that returns the contents of a cell at a hardcoded row and column (given in A1 notation as required). Since the Sheets API's implementation in Swift seems to require a callback model (I'm a beginner on callbacks and async programming in general), I haven't figured out how to return the cell's contents in my function after the query finishes.

I've followed the Sheets API iOS Quickstart provided by Google (https://developers.google.com/sheets/quickstart/ios?ver=swift&hl=zh-cn) to enable the API in the Developers Console and install the necessary Cocoapods (my Podfile installs 'GoogleAPIClientForREST/Sheets' and 'GoogleSignIn'). I got the included code to run and work properly after converting some parts to newer Swift syntax.

The issue arose when I wrote my getCell function in the ViewController.swift file. As can be seen in the code below, I assumed that the query would finish by the time getCellQuery finishes, so that getCell would be able to access the global variable updated by the callback function (displayResultWithTicket). However, the debug print statements I put in show that the callback function only executes at the end of the program, after getCell checks the global variable and finds nothing new. Note that the spreadsheet ID needs to be replaced with a real one to run this code.

```
import GoogleAPIClientForREST
import GoogleSignIn
import UIKit

struct MyVariables {
    static var currentCell: String? = nil
}

class ViewController: UIViewController, GIDSignInDelegate, GIDSignInUIDelegate {

    private let scopes = [kGTLRAuthScopeSheetsSpreadsheets]
    private let service = GTLRSheetsService()

    @IBOutlet weak var signInButton: GIDSignInButton!

    override func viewDidLoad() {
        super.viewDidLoad()

        GIDSignIn.sharedInstance().delegate = self
        GIDSignIn.sharedInstance().uiDelegate = self
        GIDSignIn.sharedInstance().scopes = scopes
    }

    func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!) {
        if let error = error {
            print("\(error.localizedDescription)")
            self.service.authorizer = nil
        } else {
            self.signInButton.isHidden = true
            self.service.authorizer = user.authentication.fetcherAuthorizer()

            //main program starts here
            print("Cell: " + getCell(a1: "Inventory!A1"))
        }
    }

    func getCell(a1: String) -> String {
        print("Started getCell")
        getCellQuery(a1: a1)
        if MyVariables.currentCell != nil {
            print("Finished getCell")
            return MyVariables.currentCell!
        } else {
            print("Error: the global variable is nil and probably hasn't been changed")
            print("Finished getCell")
            return ""
        }
    }

    func getCellQuery(a1: String) {
        print("Started getCellQuery")
        let spreadsheetId = "INSERT ID HERE"

        // arbitrary row and column in A1 notation
        let getRange = a1
        let getQuery = GTLRSheetsQuery_SpreadsheetsValuesGet.query(withSpreadsheetId: spreadsheetId, range:getRange)
        service.executeQuery(getQuery, delegate: self, didFinish: #selector(displayResultWithTicket(ticket:finishedWithObject:error:)))
        print("Finished getCellQuery")
    }

    @objc func displayResultWithTicket(ticket: GTLRServiceTicket,
                                       finishedWithObject result : GTLRSheets_ValueRange,
                                       error : NSError?) {
        print("Started callback")
        if let error = error {
            print("\(error.localizedDescription)")
            return
        }

        // turn 2d array into string
        let rows = result.values!
        for row in rows {
            for item in row {
                // update global variable
                MyVariables.currentCell = item as? String
            }
        }
        print("Finished callback")
    }
}
```

After signing in, I would expect the following in the console:
```

> Started getCell
> Started getCellQuery
> Started callback
> Finished callback
> Finished getCellQuery
> Finished getCell
> Cell: <Whatever the cell has>

```
Instead, I get this:
```

> Started getCell
> Started getCellQuery
> Finished getCellQuery
> Error: the cell value is nil and probably hasn't been changed
> Finished getCell
> Cell: 
> Started callback
> Finished callback

```
Separately, I've also tried using a while loop to wait for the global variable to be updated, but it seems like Swift is consistently opting to call the callback function at the end of the entire program, which is annoying.

If there's a less clunky approach for this simple task, it would be great to know.

**Comment by thomasvl** [comment]
Queries are async, that's why they take a completion method.  They are async because you don't want to block your app on the network.  You should use the completion callback to post something back to your app's main thread to update its UI based on the result.

**Comment by sid32502** [comment]
@thomasvl Thanks for the reply. What do you mean in terms of code by "post something back to your app's main thread" if that doesn't mean updating a global variable? 

As a separate but related question, is there any way to wait for the callback to finish and accomplish something like the code segment below (it doesn't compile)?
```
    func getCell(a1: String) -> String {
        let spreadsheetId = "INSERT ID HERE"
        let getQuery = GTLRSheetsQuery_SpreadsheetsValuesGet.query(withSpreadsheetId: spreadsheetId, range: a1)
        service.executeQuery(getQuery) { (ticket, result, error) in
            if let response = result {
                let rows = (response as! GTLRSheets_ValueRange).values!
                for row in rows {
                    for item in row {
                        // I know this line doesn't work but this is the idea I want to achieve
                        return (item as! String)
                    }
                }
            }
            else {
                print("Result was nil")
            }
        }
    }
```

**Comment by thomasvl** [comment]
"post something back to your app's main thread" - how will depend on how you design your app, the library supports getting those on other than the main queue/thread.  Using a global variable isn't likely to be thread safe if you are doing processing of results in the packaged.  Apple has a bunch of docs on threading/dispatch queues/etc. and doing work off the main thread and coordinating back.
