### ISSUE TITLE
GTLR_BUILT_AS_FRAMEWORK not being read early enough.

### ISSUE THREAD

**Issue by koedal** [google/google-api-objectivec-client-for-rest#30]
I've added GTLR_BUILT_AS_FRAMEWORK custom compiler flag to my target as I'm using the google-api project as a framework. I've added the GTLRDrive.h and associated files to my project but they won't compile due to the GTLR_BUILT_AS_FRAMEWORK not being recognized at compile time. I've checked that the flag is being set in my other files and it is. 

Any ideas how to make this flag get set before the GTLRDrive.h's imports get compiled?

**Comment by thomasvl** [comment]
When you say _GTLR_BUILT_AS_FRAMEWORK custom compiler flag_, what do you mean?  It is a pre preprocessor flag, in the Xcode UI it is _Preprocessor Macros_, when ends up setting `GCC_PREPROCESSOR_DEFINITIONS` in the project file (on in an xcconfig files).

**Comment by koedal** [comment]
I was setting the GTLR_BUILT_AS_FRAMEWORK the same way it is being set in the DriveSample.xcodeproj . When I set it as a preprocessor macro it now works. Thanks. The docs mention in 'Linking to this Framework' setting a -DGTLR_USE_FRAMEWORK_IMPORTS=1 but I didn't get that working either. Where in the project file is that to be used, preprocessor as well?

**Comment by thomasvl** [comment]
The Drive example is using the `OTHER_CFLAGS` settings to do it.  The one I pointed at is just Xcode UI over doing that.  Both will work.  I've tweaked the wiki to call out setting it on `OTHER_CFLAGS` since that comes up in other parts of the docs also and matches the examples.

The other question is where were you setting it. Xcode can have settings at the project level or on the target.  Without knowing how your project(s) is/are set up it's sorta hard to say where you put it and which will and which won't work.

**Comment by koedal** [comment]
I'm setting it on the Target. Also, I'm using v1.0.2 of the framework if that makes a difference.

Other C Flags doesn't work for me. Also the docs have GTLR_USE_FRAMEWORK_IMPORTS whereas the actual code uses GTLR_BUILT_AS_FRAMEWORK. Setting it in Other C Flags doesn't work for me; only Preprocessor Macros does.

![custom compiler flag](https://cloud.githubusercontent.com/assets/1350867/17821493/935bf6be-6617-11e6-93cf-a9b572a396f3.png)

![file not found](https://cloud.githubusercontent.com/assets/1350867/17821538/bb2dd7fc-6617-11e6-862e-f7f60dd49e23.png)

**Comment by thomasvl** [comment]
Oops, you are correct, the wrong name was on the wiki.  `GTLR_BUILT_AS_FRAMEWORK` is for use when manually adding the Framework from the GTLRCore project to your build.  `GTLR_USE_FRAMEWORK_IMPORTS` is used under the hood when using CocoaPods to get it to pull it it's dependencies (SessionFetcher, etc.) via those frameworks.

As far why it isn't working on Other C Flags, I'd likely have to see your project to figure out your structure and what command lines Xcode is actually generating to understand why it isn't working.

**Comment by koedal** [comment]
It almost appears to be a timing issue because if I put a #if GTLR_BUILT_AS_FRAMEWORK somewhere else in my code with a print() command (Swift) the print command is executed, so the macro flag is being set. It just seems to be getting set after the Drive files are compiled even though they are part of my projects target.

**Comment by thomasvl** [comment]
That may be the details that are missing.  What target did you put the Drive sources on?  What is actually compiling when things fail?  It could be that some part of module maps, bridging headers, etc. is what is failing, and not generally comping the sources that is failing.

**Comment by koedal** [comment]
The Drive sources are on my project's target. It fails when building my target.

**Comment by thomasvl** [comment]
A project can have multiple targets, what type of target is it?  Your app target? Something else (library, framework, etc.)?  Building a target takes many steps, what step is actually causing the error?

**Comment by koedal** [comment]
App target; I only have one and this is a brand new iOS Xcode project.

As per the step. I only have one .swift file currently. The error shows it was during 'Compiling Swift source files'. In particular, trying to import the GTLRDrive.h in my Bridging-Header.h

**Comment by thomasvl** [comment]
Update the docs and the examples to always use the preprocessor setting instead, hopefully that will better support folks looking to use Swift.
