### ISSUE TITLE
GTMSessionFetcherService issue

### ISSUE THREAD

**Issue by arashetm** [google/google-api-objectivec-client-for-rest#309]
I got this error after adding one of my view controllers into bridging-header.

> Definition of 'GTMSessionFetcherService' must be imported from module 'GTMSessionFetcher.GTMSessionFetcherService' before it is required

I tried lots of importing ways and none of them worked.
What should I do?

**Comment by thomasvl** [comment]
That really isn't enough information to tell what is happening.  Are you using cocoapods to pull in things or did you manually add sources to your project?  Where does the message come from?  What's the exact error message during a compile?  Can you make a small sample that shows the same problem?  From the message, it sounds like it is specific to you how have set things up, so without more details about how you have set up your project other people aren't likely to be able to help figure out what is wrong.

**Comment by arashetm** [comment]
I want to fetch data by this:
`GTMSessionFetcher *myFetcher = [drive.fetcherService fetcherWithURL:[NSURL URLWithString:url]];`
And get that error.
Also I'm using cocoapods.

**Comment by thomasvl** [comment]
Add

```
#import <GTMSessionFetcher/GTMSessionFetcherService.h>
```

Since we have a type `GTMSessionFetcher` that header is specific to that type, it isn't an umbrella header like for other modules.
