### ISSUE TITLE
Support Mac Catalyst

### ISSUE THREAD

**Issue by JonasGessner** [google/google-api-objectivec-client-for-rest#310]
This library is using a number of APIs that are deprecated and that are unavailable on mac catalyst. Adding calls to newer APIs and appropriate availability checks and preprocessor checks to know when to use the newer APIs would allow supporting Catalyst, which would be nice!

<img width="411" src="https://user-images.githubusercontent.com/1156152/66708324-1a3e4a80-ed4f-11e9-9294-e791146ce8bb.png">

**Comment by jonas-sleepcycle** [comment]
Would love this as well!

**Comment by appfrilans** [comment]
Would love this as well!! Is there any work-around in the meantime?

**Comment by thomasvl** [comment]
So from the error messages, this doesn't appear to be an issue here, but instead an issue on the [GTMSessionFetcher](https://github.com/google/gtm-session-fetcher).  Mind opening an issue with that instead and we'll track the work needed there directly?

**Comment by JonasGessner** [comment]
Done: https://github.com/google/gtm-session-fetcher/issues/156

Would love to see this soon. Thanks
