### ISSUE TITLE
dyld: Symbol not found: _OBJC_CLASS_$_GTLRDriveQuery_FilesList

### ISSUE THREAD

**Issue by mohitathwani** [google/google-api-objectivec-client-for-rest#311]
I just installed the GoogleAPIForREST pod and started writing some code and con't proceed dues to this error: 
`dyld: Symbol not found: _OBJC_CLASS_$_GTLRDriveQuery_FilesList`

My set up is Xcode 11.2 Swift 5.1

Is anybody else seeing this?

**Comment by mohitathwani** [comment]
This seems to work fine on the device. Issue is for simulator only.

**Comment by thomasvl** [comment]
Try doing a clean and rebuild?  It sounds like something was wrong in the initial build after configuring the cocoapods. You are using the Xcode Workspace CocoaPods creates and not the project?  I believe the Workspace needs to be used (and not the Xcode Project file) to get everything linked together.

**Comment by mohitathwani** [comment]
I am using the workspace and also you were correct, a clean build solved the problem. Thanks!
