### ISSUE TITLE
Question about Syncing and Merging

### ISSUE THREAD

**Issue by mohitathwani** [google/google-api-objectivec-client-for-rest#313]
So I'm curious to know how this library handles the following situations specifically for Google Sheets

1. User tries to add info but is offline.
    For whatever reason, if the user is offline and the user has added content to a sheet, does this framework cache the delta and post it to the server when network is available? If yes, what is the merge strategy? If no, what is the timeout period?

2. How does this framework decide how to merge to ensure data is always consistent between the server and the client?

**Comment by thomasvl** [comment]
This library doesn't maintain any state.  It is for sending requests and getting back responses.  Any sort of offline modeling of higher level concepts (editing a spreadsheet) would be something an application builds on top of it.
