### ISSUE TITLE
Files downloaded from GoogleDrive are corrupted and limited approximately to 70KB

### ISSUE THREAD

**Issue by SergeiKu** [google/google-api-objectivec-client-for-rest#316]
- GoogleAPIClientForREST/Drive (1.3.10)
- GTMSessionFetcher (>= 1.1.7)
- device: iOS 13
- Xcode 11.

Our app allows the users to see the files in their Google Drives and download them saving in the device.
Once the app fetches a file from Google Drive by this code.

`currentCloudService = .googleDrive
            driveService = GTLRDriveService()
            let authorizer = OauthManager.sharedInstance.getAuthorizationObjectFor(userId: currentGoogleUser.id)
            driveService.authorizer = authorizer!
            documentFilename = googleDriveFile.name
            
            guard let canAuth = driveService.authorizer!.canAuthorize, canAuth else {
                LoadingOverlay.shared.showOverlay(view)
                DocytAlertView.showAlertWith("Error", message: "Failed to authorize with Google Drive", type: .closeType, actionHandler: nil)
                return
            }
            let fetcher = driveService.fetcherService.fetcher(withURLString: googleDriveFile.webContentLink!)
            fetcher.beginFetch { (data, error) -> Void in
                guard error == nil else {
                    self.dispatchAlert("Error", alert: error!.localizedDescription)
                    return
                }
                self.documentLocalPath = DocytFileManager.instance.mkTmpFileWithExtension(self.googleDriveFile.fileExtension!)
                let url = URL(fileURLWithPath: self.documentLocalPath!)
                do {
                    try data?.write(to: url, options: .atomic)
                    dispatch_to_main_queue {
                        self.displayFileFromLocalPath(self.documentLocalPath)
                    }
                } catch {
                    self.showAlert("Error", alert: "Failed to save file to local storage")
                }
            }`

the downloaded file always has a size of approximately 70KB though the original file is bigger. So it becomes corrupted. If I just use this link: `googleDriveFile.webContentLink!` and past it directly to a web browser I am getting the file with the correct size. The issue is reproducible in 100% of cases. I checked it with pdf and jpeg files.

**Comment by thomasvl** [comment]
Does the download complete with success?

Looks like you are also trying to hold the file in memory which is always risky for larger files, there is fetcher support for downloading directly to files to avoid those issues.

If you enable the fetcher logging (https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic), does it give any indication what's happening?

**Comment by SergeiKu** [comment]
Hi, @thomasvl  Thank you for the fast reply!
I have just tried to switch logging on and there are results:

> 2019-11-06 06:28:28 +0000      (No fetcher comment set)      request/response log
elapsed: 31.560sec
redirected from https://docs.google.com/.......
request: GET https://accounts.google.com/ServiceLogin?service=wise.........
   headers: 5    authorized
response:  status 200
   headers: 15   sets cookies 
   data: 70473 bytes, text/html 

as you can see the data in the response is 70473 bytes but original file is about 180 KB.

**Comment by thomasvl** [comment]
That looks like a redirect from a drive urls to a html login page; if so, that's why it isn't the original file you were expected.  So maybe your authorization isn't right, or how you are using the drive api to do a download isn't correct.

The drive sample with this project shows doing a download, I'd suggest looking at that.

**Comment by SergeiKu** [comment]
@thomasvl Hmm, I think you are right. I will explore the sample and try to figure out what is wrong then. But what is interesting, when I switched to use this way to download files everything started work fine:

`guard let fileID = googleDriveFile.identifier else {
                return
            }
            
           self.driveService.executeQuery(GTLRDriveQuery_FilesGet.queryForMedia(withFileId: fileID)) { (ticket, file, error) in
              guard error == nil else {
                   self.dispatchAlert("Error", alert: error!.localizedDescription)
                   return
               }
                guard let data = (file as? GTLRDataObject)?.data else {
                   return
               }
                 self.documentLocalPath = DocytFileManager.instance.mkTmpFileWithExtension(self.googleDriveFile.fileExtension!)
                 let url = URL(fileURLWithPath: self.documentLocalPath!)
                 do {
                   try data.write(to: url, options: .atomic)
                     dispatch_to_main_queue {
                         self.displayFileFromLocalPath(self.documentLocalPath)
                     }
                 } catch {
                     self.dispatchAlert("Error", alert: "Failed to save file to local storage")
                 }
             }`

**Comment by SergeiKu** [comment]
Yes, it redirects me to this page. Though I have no idea why (at the moment). Yes, it redirects me to this page. Though I have no idea why (at the moment). I can see files in the drive and can even download them successfully if I use another way as described above... It would be great if you could suggest why it might happen.
<img width="659" alt="Screenshot 2019-11-07 at 08 02 04" src="https://user-images.githubusercontent.com/25579299/68361516-30b0a980-0135-11ea-8b08-3f1ae9a12dda.png">

**Comment by thomasvl** [comment]
Looking at the docs for files: https://developers.google.com/drive/api/v3/reference/files


Property name | Value | Description
-- | -- | --
webContentLink | string | A link for downloading the content of the file in a browser. This is only available for files with binary content in Google Drive.

So from that, I'd expect what is happening is you are getting an url that should only work in the browser, since the download attempt won't have the normal session cookies a browser would have, it is getting redirected to login and confirm access first.

**Comment by SergeiKu** [comment]
Ah, got it! @thomasvl Great thanks for your help! I will study the doc and the example.
