### ISSUE TITLE
Code Signing Required on Framework when Linking to Framework

### ISSUE THREAD

**Issue by koedal** [google/google-api-objectivec-client-for-rest#32]
Xcode says code signing is required when linking to the framework and building for a device. Can you update the default code signing settings to be the Automatic settings so I don't have to fork the project for just this setting?

![code signing required](https://cloud.githubusercontent.com/assets/1350867/17821967/030e87d6-661a-11e6-8fcf-6489d0e8883c.png)

![automatic code signing](https://cloud.githubusercontent.com/assets/1350867/17821980/1015555e-661a-11e6-8958-fe3529f20c24.png)

**Comment by thomasvl** [comment]
Sure.  You can also send an a PR for it.  Note: I haven't had a chance to look in detail at Apple's Xcode 8 signing changes, so that may end up meaning we need to tweak these again for that (when it GMs).

**Comment by koedal** [comment]
Will do.
