### ISSUE TITLE
App Store rejects binary with "ITMS-90562: Invalid Bundle"

### ISSUE THREAD

**Issue by yoasha** [google/google-api-objectivec-client-for-rest#322]
My iOS app is integrated with google-api library and works great for years now. Yesterday I grabbed the latest google-api sources, archived my app and uploaded to the App Store. Short after got rejection email with the above error.

After several hours of investigation I found that the latest commit of GTLRRuntimeCommon.m is the root cause of the rejection. When skipping this commit, everything goes well.

The rejection appears to be that the App Store can't rebuild the binary from bitcode. And indeed, if I try to archive my app, distribute it to "Development" rather than "App Store Connect", and then choose "Rebuild from Bitcode", Xcode will show a failure.

According to the documentation, one of the reasons for the error is inconsistent usage of "__asm". The latest commit includes the usage of "__asm", so it's only a guess it might be the cause as I'm not familiar with it.

See https://developer.apple.com/library/archive/technotes/tn2432/_index.html#//apple_ref/doc/uid/DTS40017150-CH1-TNTAG3-KNOWN_BITCODE_ISSUES

Any thoughts?

**Comment by thomasvl** [comment]
Thanks, rolling back.  We'll have to see if we can do this without the asm trick.
