### ISSUE TITLE
Service definition for DialogFlow v2beta1 is missing

### ISSUE THREAD

**Issue by DmitryKlymenkoAU** [google/google-api-objectivec-client-for-rest#329]
Please add it :)

Thanks

**Comment by thomasvl** [comment]
I'm not sure if you are asking for the service definition or this library (objective-c_ to support it).  But I don't see a v2 rest api?  https://www.googleapis.com/discovery/v1/apis?name=dataflow only slow _ v1b3_. And https://cloud.google.com/dataflow/docs/reference/rest also seems to only list a _v1b3_ api.

You might need to use [support options](https://cloud.google.com/dataflow/docs/support) with the service directly to get it documented so it can be generated for this library or others.

**Comment by thomasvl** [comment]
Closing this out since there isn't anything we can do on this library since the discovery document seems to be for the older one.
