### ISSUE TITLE
Stuck in `postNotificationOnMainThreadWithName`

### ISSUE THREAD

**Issue by OneSecure** [google/google-api-objectivec-client-for-rest#333]
When I degug my project, the main thread always stuck in this line. Is this a bug?

https://github.com/google/google-api-objectivec-client-for-rest/blob/0e124d1fde92d5123e64cc8fd0cabb815c3b7a04/Source/Objects/GTLRService.m#L2575

**Comment by thomasvl** [comment]
That's not a lot of information to go on.  Can you make a small example apps that reshow your problem?  It sounds like it is going to be some interaction with other things, so without knowing more about the state of the app, no on is really going to be able to suggest much.
