### ISSUE TITLE
Could not determine client ID from request

### ISSUE THREAD

**Issue by acarter1863** [google/google-api-objectivec-client-for-rest#35]
Hi

I'm running the example YouTubeSample app in XCode but get the error "Could not determine client ID from request". I haven't modified the code. Here are the steps I follow.
Enter in a ClientID
Leave the Client Secret blank as it is not found in console.developers.google neither is it found in the .plist.
Sign into Google account
Press GetPlaylist

The NSError *callbackError in the completion handler of the following call
 _channelListTicket = [service executeQuery:query
                           completionHandler:^(GTLRServiceTicket *callbackTicket,
                                               GTLRYouTube_ChannelListResponse *channelList,
                                               NSError *callbackError)
returns
2016-08-28 15:06:43.213 YouTubeSample[38574:278119] Error Error Domain=com.google.HTTPStatus Code=400 "(null)" UserInfo=...
Error data:
{
    error = "invalid_request";
    "error_description" = "Could not determine client ID from request.";
}

Any suggestions?

**Comment by thomasvl** [comment]
FYI - the [http logging](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) can be useful to see what is actually going between clients/servers.

Have you set the cilent ID you create in the UI of the sample?  @grantkemp added some [more complete info](https://github.com/google/google-api-objectivec-client-for-rest/tree/master/Examples#to-obtain-an-oauth-client-key
) to using the examples.  Are those the steps you followed?

**Comment by acarter1863** [comment]
Thanks @thomasvl 

Yes, those were the steps I followed. Trial and error taught me that when you stop the app and restart it but remain logged in to your Google account this error happens. When I enter the client ID followed by signing into Google, it works.

Is there a blog or forum that's frequented regularly in regard to google-api-objectivec-client-for-rest because I don't feel my next question is an 'issue'. I'll post it here to get started.

Simply, I'd like to use google-api-objectivec-client-for-rest to run the Google Sheets API Quickstart for iOS here https://developers.google.com/sheets/quickstart/ios?ver=swift The instructions for that link refer to using GoogleAPIClient and doesn't work.

The examples in google-api-objectivec-client-for-rest include files that reference being generated by a ServiceGenerator. While I've gotten them to work, I can't figure out how to replicate those examples for Google Sheets and think the simple approach of getting that Quickstart to work would be a faster approach for me to learn.

"Migrating From GTL to GTLR" doesn't have enough detail for me to understand how to get the Quickstart app to work. So I'm commenting out the #import statements that are of no relevance and reverse enginnering the code. I just think/hope that someone has been down this path and left more obvious breadcrumbs.

**Comment by thomasvl** [comment]
As mentioned in the README.md (shown on the project page), there is a [Google group for discussion](http://groups.google.com/group/google-api-objectivec-client).

Re stop/start, sounds like NSUserDefaults might not be storing things before you kill the app.  NSUserDefaults auto saves, but the example might need a `-synchronize` call before exiting.

Re the quickstart - https://github.com/google/google-api-objectivec-client-for-rest/issues/24 got filed for another one, I've opened another internal one for Sheets.  As far as migration goes; I hadn't seen that one, sadly it wasn't using generated classes for the old library, it actually is hand rolling all the fetches, so the guide doesn't really apply.  You likely are better off just following the wiki for how to pull in the library and add the dependency for the Sheets subspec to get those classes.  Then use the [api reference](https://developers.google.com/sheets/reference/rest/) along with the comments that show up in the [generated api](https://github.com/google/google-api-objectivec-client-for-rest/tree/master/Source/GeneratedServices/Sheets) to help navigate things.

**Comment by grantkemp** [comment]
@acarter1863 Which example project did you use to generate that error. I am unable to replicate it. If you can share the steps- I can try help more specifically. 

@thomasvl  it sounds like the Google Sheets use case is something that a lot of users are going to encounter.  It will likely drive increased usage of this module if its made as simple and easy to implement as possible. I will have a bash at building a simple example to contribute back when I have some time- it sounds like something we will make frequent use of at work. 

If anyone else wants to have a bash - then we can make it a collaborative effort. 

Cheers

GK

**Comment by acarter1863** [comment]
@grantkemp Yes, I'd like to be part of the bash for Sheets. The example I've been testing is YouTubeSample. Here are the steps I follow:
From a Mac terminal I call git clone --recursive git://github...
Navigate and open YouTubeSample in Xcode
Run
Press Client ID and enter the one I've created in console.developers.google.com // The app is also enabled
Press Sign In
Select 'Watch History' from Playlist dropdown // Ensure watch history is resumed in YouTube
The playlist appears as expected.

Stop the app in Xcode
Run the app again
The app shows I'm stilled signed in so it doesn't occur to enter the Client ID again
Select 'Watch History' from Playlist dropdown or Press Get Playlist
This generates the "Could not determine client ID from request."

So I enter the client ID again
Select 'Watch History' from Playlist dropdown or Press Get Playlist
The same error is returned, "Could not determine client ID from request."

Signing out and back in again and the app resumes working as expected.

@thomasvl Thanks for opening an internal ticket for Sheets. What's the best way to keep track of the progress? I agree with your assessment of the Example app. It does seem like an NSUserDefaults issue. I'll follow up on your suggestions for getting Sheets to work. Much appreciated.

**Comment by thomasvl** [comment]
fyi - _Stop the app in Xcode_ means you're killing the app.  Even with the commit I just did, it might not "fix" things since the kill prevents the app from doing anything to ensure state was saved.  If you quit the app, then things likely will work better.

As far as tracking, there isn't a way to do that at the moment short of checking the page for updates.  I'll try to circle back when I see updated on the internal bug.

**Comment by thomasvl** [comment]
Looks like the quickstart does talk about GTLR now, so closing this out just to keep better track of what really is open/needing follow up.
