### ISSUE TITLE
Daily limit for unauthenticated use exceeded. Continued use requires signup

### ISSUE THREAD

**Issue by sssbohdan** [google/google-api-objectivec-client-for-rest#352]
I've updated pod version from `1.2.1` to `1.3.11` and spotted that now 'GTLRDriveService' doesn't have `authorizer` property, therefore, I'm getting `Daily limit for unauthenticated use exceeded. Continued use requires signup.` but my user is authorized.

**Comment by sssbohdan** [comment]
Also it seems that service doesn't have `fetcherService` so how download files? Can you help me with that please?

**Comment by thomasvl** [comment]
Sounds like you are using Swift and a bridging header, please see the wiki for help:

https://github.com/google/google-api-objectivec-client-for-rest/wiki/BuildingTheLibrary#using-a-swift-bridging-header
