### ISSUE TITLE
Using Package Manager Resources in Swift PM Unit Tests

### ISSUE THREAD

**Issue by karimhm** [google/google-api-objectivec-client-for-rest#359]
Currently, in order to have successful tests when using the Swift Package Manager the files inside `Data` folder are copied manually to the unit test bundle resources folder.
https://github.com/google/google-api-objectivec-client-for-rest/blob/680acf416493e6e90b00149e97558668197e5156/Source/Tests/GTLRServiceTest.m#L127-L189

[Swift 5.3](https://swift.org/blog/5-3-release-process/) introduced a new feature called [Package Manager Resources](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md). Once this gets rolled into production, it must be used to copy resources rather than doing it manually.

**Comment by thomasvl** [comment]
Xcode 11.4.1 seems to fail `swift test` results at the moment because of the text files (it seems to expect .o files get created from them).

**Comment by karimhm** [comment]
Swift 5.3 should sole all the issues. it might ship with Xcode 11.5 or 12

**Comment by thomasvl** [comment]
Closing this out, `main` moved to be resource free (basically changed the helper api to just return the data blobs instead of writing them into the package on disk).
