### ISSUE TITLE
Implement NSCoding for GTLRBatchResult

### ISSUE THREAD

**Issue by JonasGessner** [google/google-api-objectivec-client-for-rest#36]
`GTLRBatchResult` is a subclass of `GTLRObject`, which implements `NSSecureCoding`. However encoding and decoding a `GTLRBatchResult` results in an empty batch result, not the original batch result that was encoded. This is not the expected behavior, the batch result class should be codable.

**Comment by thomasvl** [comment]
Yup, we've usually seen this also come up for the Query classes.  Just curious, is there a reason you save the batch vs. just saving the objects from different operations?

**Comment by JonasGessner** [comment]
I'm doing some caching where I cache the response objects for each query. I'm trying to make a general implementation that doesn't need to worry about the type of query or response. Basically I compute a hash from the query, then execute the query and save the response object, or return the cached response if it exists.

Are there other GTLRObject classes that don't support coding?

The batch result simply needs to store its successes, failures and response headers, something like this:

```objc
- (void)encodeWithCoder:(NSCoder *)aCoder {
    [super encodeWithCoder:aCoder];
    
    [aCoder encodeObject:self.successes forKey:@"successes"];
    [aCoder encodeObject:self.failures forKey:@"failures"];
    [aCoder encodeObject:self.responseHeaders forKey:@"responseHeaders"];
}
```

**Comment by thomasvl** [comment]
GTLRQuery (and BatchQuery), likely doesn't fully support encode/decode.

**Comment by JonasGessner** [comment]
The GTLRObject subclasses in the generated services all support coding though (meaning that no data is lost when encoding and decoding)? I've tested the youtube classes and they seem to work fine, so I'm guessing just the GTLRBatchResult needs to be updated.

**Comment by JonasGessner** [comment]
Thanks! I appreciate the quick fix :)
