### ISSUE TITLE
Support for Google Visualization/Charts

### ISSUE THREAD

**Issue by mohitathwani** [google/google-api-objectivec-client-for-rest#362]
I’m building an application on top of Google Sheets and one of my features is to query a sheet for some information. From my research, Google Sheets API doesn’t directly support that but it is possible using Google Visualization APIs. I was able to successfully run a query on my sheet from the browser by constructing the url appropriately. My question is whether there are any plans to support the Visualization APIs in this library?

**Comment by thomasvl** [comment]
The project auto generates everything in discovery's directory, you can see these in the [API Explorer](https://developers.google.com/apis-explorer).  Developers can also use the ServiceGenerator to directly generate anything they have a discovery document for.

**Comment by thomasvl** [comment]
You'd need to ask on the support areas for the product. Since this library generates for over 100 apis, we're not experts on all of the APIs or what is available.
