### ISSUE TITLE
unauthorized_client and crashed

### ISSUE THREAD

**Issue by KiranPatelSpaceo** [google/google-api-objectivec-client-for-rest#372]
Getting string "**unauthorized_client**" in place of Dictionary and getting crash

[__NSCFString objectForKey:]: unrecognized selector sent to instance 

GTLRObject.m file

- (id)JSONValueForKey:(NSString *)key {
  **id obj = [self.JSON objectForKey:key];**
  return obj;
}

I am using the latest version 

let me know in which case getting **unauthorized_client**  ?

**Comment by thomasvl** [comment]
There really isn't much to go on here.

From the info, it sounds like `self.JSON` might be just a `NSString` and not a `NSDictionary` so fetching an attribute for what should be an object is what is failing.  But without more information about what you are doing, it is hard to tell why things went wrong.

**Comment by shahardra** [comment]
Ok
