### ISSUE TITLE
Cross Platform G-Suite APIs for Swift

### ISSUE THREAD

**Issue by adiwajshing** [google/google-api-objectivec-client-for-rest#375]
Hi, 

I was wondering if Google will ever develop a cross-platform G-Suite API for Swift, specifically for server side applications?

I did build an *incomplete* [implementation](https://www.github.com/adiwajshing/Queenfisher) myself -- because my work required it -- but is Google interested in building such an API for Swift?

**Comment by thomasvl** [comment]
The folks that historically worked on this repo, don't work on it, but there is https://github.com/googleapis/google-api-swift-client, I believe it is parallel in concept to this library, but written in Swift.

**Comment by adiwajshing** [comment]
Oh wow, this swift library seems even more incomplete than mine :/
Regardless, I'll take this issue there.

Thank you!
