### ISSUE TITLE
Download progress of google drive file

### ISSUE THREAD

**Issue by Burtan** [google/google-api-objectivec-client-for-rest#376]
Hey, I followed the example to download a file from google drive on iOS. However the download progress shows always a total bytes size of -1

```
        let drive = GDrive.getGDrive() /GDriveService

        let query = GTLRDriveQuery_FilesGet.queryForMedia(withFileId: fileId)
        let request: URLRequest = drive.request(for: query) as URLRequest
        let fetcher: GTMSessionFetcher = drive.fetcherService.fetcher(with: request)

        fetcher.destinationFileURL = "temp file path"

        fetcher.downloadProgressBlock = { read, totalRead, totalSize in
            //totalsize is always -1
        }

        fetcher.beginFetch { data, error in
            ...
        }
```

**Comment by nanaluz** [comment]
> Hey, I followed the example to download a file from google drive on iOS. However the download progress shows always a total bytes size of -1
> 
> ```
>         let drive = GDrive.getGDrive() /GDriveService
> 
>         let query = GTLRDriveQuery_FilesGet.queryForMedia(withFileId: fileId)
>         let request: URLRequest = drive.request(for: query) as URLRequest
>         let fetcher: GTMSessionFetcher = drive.fetcherService.fetcher(with: request)
> 
>         fetcher.destinationFileURL = "temp file path"
> 
>         fetcher.downloadProgressBlock = { read, totalRead, totalSize in
>             //totalsize is always -1
>         }
> 
>         fetcher.beginFetch { data, error in
>             ...
>         }
> ```
