### ISSUE TITLE
Delete file on AppData by GTLRBatchQuery throw error

### ISSUE THREAD

**Issue by nguyendinhtrieu1996** [google/google-api-objectivec-client-for-rest#378]
I try to delete multiple files on GG Drive App Data by GTLRBatchQuery. However response data with error code -3001 (GTLRServiceErrorBatchResponseUnexpected)

* Sample code

GTLRBatchQuery *batchQuery = [GTLRBatchQuery batchQuery];
GTLRDriveQuery_FilesDelete *query1 = [GTLRDriveQuery_FilesDelete queryWithFileId:fileId_1];
GTLRDriveQuery_FilesDelete *query2 = [GTLRDriveQuery_FilesDelete queryWithFileId:fileId_2];

[service executeQuery:batchQuery
              completionHandler:^(GTLRServiceTicket * _Nonnull callbackTicket,
                                       id  _Nullable object,
                                       NSError * _Nullable callbackError) {
    
}];

* Response data

--batch_hXL_3_UnLsQ_AAYW6kQ4LYU
Content-Type: application/http
Content-ID: response-gtlr_39

HTTP/1.1 204 No Content
Date: Wed, 24 Jun 2020 09:21:24 GMT

--batch_hXL_3_UnLsQ_AAYW6kQ4LYU
Content-Type: application/http
Content-ID: response-gtlr_40

**Comment by thomasvl** [comment]
When you say an error was thrown, what do you mean?  Is it simply that you are getting an error back in the completion handler?

What version of the library are you using?  https://github.com/google/google-api-objectivec-client-for-rest/pull/347 was a fix for something similar.

**Comment by nguyendinhtrieu1996** [comment]
Yes, I get error back in completion handler.

I am using library version 1.3.9 and I update to newest version 1.4.1.
And I get error code (-3002) when trying delete multiple file with GTLRBatchQuery

Thanks for supporting.

**Comment by thomasvl** [comment]
The second response data is a little odd, what you pasted doesn't actually have a HTTP header for that part of the mime document.  Can you make a repo case or full logs so we can try to figure out what might be happening?

**Comment by nguyendinhtrieu1996** [comment]
I'm so sory, full response data when I try to delete multiple files with GTLRBatchQuery
I think I get error (-3002) when process response data in GTLRService, because when delete it's wrong format data: https://developers.google.com/drive/api/v3/batch#batch-example-response

*Response Data
--batch_hXL_3_UnLsQ_AAYW6kQ4LYU
Content-Type: application/http
Content-ID: response-gtlr_39

HTTP/1.1 204 No Content
Date: Wed, 24 Jun 2020 09:21:24 GMT


--batch_hXL_3_UnLsQ_AAYW6kQ4LYU
Content-Type: application/http
Content-ID: response-gtlr_40

HTTP/1.1 204 No Content
Date: Wed, 24 Jun 2020 09:21:24 GMT

**Comment by nguyendinhtrieu1996** [comment]
All response data have same format. And when I check on GG Drive App, my data is delete successfull.

**Comment by nguyendinhtrieu1996** [comment]
Repo steps when parse batch response data:
  1. Call [GTLRService responsePartsWithMIMEParts:]
2. Then call [GTLRService responsePartWithMIMEPart:]
3. [GTLRService batchResultWithResponseParts: batchClassMap: objectClassResolver]

In step 3, I will get error code GTLRServiceErrorBatchResponseStatusCode because ‘responsePart’ statusCode = 0
So in batchResponse all data will in failure dictionary

**Comment by thomasvl** [comment]
Repo steps normally are a full steps so we can trace thru things.  Can you repro the issue with [logging enabled](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic)? The fully HTTP transaction for the request and response might be enough for me to mock this out into a test case to help confirm what is happening and try to see where things go wrong.

**Comment by thomasvl** [comment]
Yea, looking at this more closely, it seems like you're missing an end marker in the snippet, also, some double blank lines you singles.  So getting some real code and/or raw log files so nothing is lost is going to be required to tell what's going wrong.  At the moment, I'm not sure what is things failing to be pasted, or maybe markdown modifying what is pasted, vs. what the server is actually returning too you.

**Comment by nguyendinhtrieu1996** [comment]
My log when I try to delete multiple files with GTLRBatchQuery

[fetch_1.txt](https://github.com/google/google-api-objectivec-client-for-rest/files/4838121/fetch_1.txt)

**Comment by thomasvl** [comment]
Thanks, I think I see the issue, it's a long standing edge case in a reply.
