### ISSUE TITLE
Crash on request to admob report 

### ISSUE THREAD

**Issue by alexmomotiuk** [google/google-api-objectivec-client-for-rest#385]
I send request to AdMob but code crashing
` 
let service = GTLRService()
service.setValue(user.authentication.fetcherAuthorizer(), forKey: "authorizer")
service.rootURLString = "https://admob.googleapis.com/"
service.apiKey = "<My API Key>"
        
        let query = GTLRQuery(pathURITemplate: "v1/accounts/", httpMethod: "GET", pathParameterNames: nil)
service.executeQuery(query) { (ticket, data, error) in
            let pubId = (((data as! GTLRObject).jsonValue(forKey: "account") as! [Any]).first as! [String: Any])["publisherId"] as! String
            
            let query1 = GTLRQuery(pathURITemplate: "v1/accounts/\(pubId)/mediationReport:generate", httpMethod: "POST", pathParameterNames: nil)
            query1.bodyObject = GTLRObject.init(json: ["reportSpec":[
                "dateRange": [
                    "startDate": ["year": 2018, "month": 9, "day": 1],
                    "endDate": ["year": 2018, "month": 9, "day": 30]
                ],
                "dimensions": ["AD_SOURCE", "APP", "COUNTRY"],
                "metrics": ["OBSERVED_ECPM"],
                "dimensionFilters": [
                    [
                        "dimension": "COUNTRY",
                        "matchesAny": ["values": [ "US", "UA"]]
                    ]
                ],
                "sortConditions": [
                    ["dimension":"APP", "order": "ASCENDING"]
                ],
                "localizationSettings": [
                    "currencyCode": "USD",
                    "languageCode": "en-US"
                ]
            ]])
            service.executeQuery(query1) { (ticket, data, error) in
                print(data)
            }
        }
`

Crash stacktrace

`
2020-08-01 17:51:51.139259+0300 AdMobTracker[46083:1915952] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM allKeys]: unrecognized selector sent to instance 0x600002ad8480'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5eb94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e4286c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e44b58 _CF_forwarding_prep_0 + 120
	5   GoogleAPIClientForREST              0x000000010d579da5 -[GTLRObject JSONDescription] + 213
	6   GoogleAPIClientForREST              0x000000010d579c19 -[GTLRObject description] + 41
	7   libswiftFoundation.dylib            0x00007fff51bfc1fd $sSo8NSObjectCs23CustomStringConvertible10FoundationsACP11descriptionSSvgTWTm + 13
	8   libswiftCore.dylib                  0x00007fff5178ff62 $ss20_debugPrint_unlockedyyx_q_zts16TextOutputStreamR_r0_lF + 306
	9   libswiftCore.dylib                  0x00007fff5180e1f5 $ss11_debugPrint_9separator10terminator2toySayypG_S2Sxzts16TextOutputStreamRzlFSS_Tg5 + 197
	10  libswiftCore.dylib                  0x00007fff51806548 $sSq16debugDescriptionSSvg + 296
	11  libswiftCore.dylib                  0x00007fff5178f63c $ss15_print_unlockedyyx_q_zts16TextOutputStreamR_r0_lF + 684
	12  libswiftCore.dylib                  0x00007fff5180f612 $ss6_print_9separator10terminator2toySayypG_S2Sxzts16TextOutputStreamRzlFs7_StdoutV_Tg5Tm + 258
	13  libswiftCore.dylib                  0x00007fff5180e0e9 $ss5print_9separator10terminatoryypd_S2StFTm + 185
	14  libswiftCore.dylib                  0x00007fff5180d84f $ss5print_9separator10terminatoryypd_S2StF + 31
	15  AdMobTracker                        0x000000010cbcfa29 $s12AdMobTracker11AppDelegateC4sign_12didSignInFor9withErrorySo07GIDSignI0CSg_So13GIDGoogleUserCSgs0L0_pSgtFySo17GTLRServiceTicketC_ypSgANtcfU_yAP_AqNtcfU_ + 201
	16  AdMobTracker                        0x000000010cbcfb6a $sSo17GTLRServiceTicketCypSgs5Error_pSgIeggng_AByXlSgSo7NSErrorCSgIeyByyy_TR + 282
	17  GoogleAPIClientForREST              0x000000010d58de5a __135-[GTLRService handleParsedObjectForFetcher:executingQuery:ticket:error:parsedObject:hasSentParsingStartNotification:completionHandler:]_block_invoke + 346
	18  libdispatch.dylib                   0x000000010d835f11 _dispatch_call_block_and_release + 12
	19  libdispatch.dylib                   0x000000010d836e8e _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000010d844e67 _dispatch_main_queue_callback_4CF + 1357
	21  CoreFoundation                      0x00007fff23da1869 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x00007fff23d9c3b9 __CFRunLoopRun + 2041
	23  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	24  GraphicsServices                    0x00007fff38c39bbe GSEventRunModal + 139
	25  UIKitCore                           0x00007fff49325968 UIApplicationMain + 1605
	26  AdMobTracker                        0x000000010cbcfd6b main + 75
	27  libdyld.dylib                       0x00007fff520ce1fd start + 1
)
`

**Comment by thomasvl** [comment]
You appear to be building up your queries and object by hand.  Is there a reason you can't use the [generated AdMob api](https://github.com/google/google-api-objectivec-client-for-rest/tree/master/Source/GeneratedServices/AdMob)?

**Comment by alexmomotiuk** [comment]
@thomasvl thanks a lot for response, I missed this. I will try generated api.
