### ISSUE TITLE
error: could not build Objective-C module 'GoogleAPIClientForREST' in LLDB

### ISSUE THREAD

**Issue by MoathOthman** [google/google-api-objectivec-client-for-rest#388]
Hey guys, 

I have integrated GoogleAPIClientForREST into my swift project. and it's working fine, Thank you !!!. 
but when I try to debug something and try to use LLDB i get this issue and it prevents me from using lldb. 

steps: 

- Set a breakpoint anywhere in the codebase.
- when the break point is reached
- try to run any command e.g. po foo 

I get this error in the console

```
error: <module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/GoogleAPIClientForREST-umbrella.h"
        ^

/Users/moathaliwat/Desktop/PixilProjects/giftogo/giftogo_ios/giftogo/Pods/Target Support Files/GoogleAPIClientForREST/GoogleAPIClientForREST-umbrella.h:13:9: note: in file included from /Users/moathaliwat/Desktop/PixilProjects/giftogo/giftogo_ios/giftogo/Pods/Target Support Files/GoogleAPIClientForREST/GoogleAPIClientForREST-umbrella.h:13:
#import "GTLRCalendar.h"
        ^

/Users/moathaliwat/Desktop/PixilProjects/giftogo/giftogo_ios/giftogo/Pods/GoogleAPIClientForREST/Source/GeneratedServices/Calendar/GTLRCalendar.h:11:9: note: in file included from /Users/moathaliwat/Desktop/PixilProjects/giftogo/giftogo_ios/giftogo/Pods/GoogleAPIClientForREST/Source/GeneratedServices/Calendar/GTLRCalendar.h:11:
#import "GTLRCalendarObjects.h"
        ^

error: /Users/moathaliwat/Desktop/PixilProjects/giftogo/giftogo_ios/giftogo/Pods/GoogleAPIClientForREST/Source/GeneratedServices/Calendar/GTLRCalendarObjects.h:12:11: error: module 'GoogleAPIClientForRESTCore' not found
  @import GoogleAPIClientForRESTCore;
          ^

error: could not build Objective-C module 'GoogleAPIClientForREST'

Couldn't initialize Swift expression evaluator due to previous errors.
```

any idea what could be the issue?
thanks a lot .

**Comment by thomasvl** [comment]
First report we've had for this, so it might be something specific to your setup/integration.  Can you make a stand alone repro case?

The fact that you have a `GoogleAPIClientForREST-umbrella.h` that appears to import a specific service is a little bit of a surprise.  The podspec [defaults things to the _Core_ lib without any services](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/GoogleAPIClientForREST.podspec#L27-L32). So where that larger one is coming from is a little strange.

@paulb777 fyi

**Comment by MoathOthman** [comment]
@thomasvl thank you for your response, on a standalone project its fine. am not sure what could cause it! its kinda not trivial project and there are a lot of configurations going on 😓

**Comment by MoathOthman** [comment]
@thomasvl am not sure if this helpful , but I bisected the issue and it happened when we added some packages using Swift package manager to the project. 

to reproduce the same behavior you can download this repo. 
 https://github.com/MoathOthman/GoogleAPIClientForREST-Test
- set a breakpoint somewhere and run the app.

**Comment by thomasvl** [comment]
Hm, that sounds like it might actually be a bug with the Xcode SwiftPM support or an interaction between that and CocoaPods. So you might beed to file an issue with CocoaPods and/or Apple's Feedback since this is all in the plumbing they do.

**Comment by MoathOthman** [comment]
@thomasvl thank you for the quick response, I will do submit and issue then.

**Comment by ymmuse** [comment]
We mixed Swift PM and CocoaPods to use and I met the same problem in our project. Eventually, I solved it that all dependents used the CocoaPods to manage.

**Comment by farshadtx** [comment]
I don't think this is SPM related.

I had `GoogleSignIn` and `GoogleAPIClientForRest` in my project as Pod dependencies and the rest was SPM when I noticed debugging is completely off. 

Playing with all possible cases, if I keep `GoogleSignIn` and all SPM packages, LLDB works fine and can debug but if I add this repo + all SPM packages then debugging will stop working. 

I tried adding this repo as an SPM but I was not able to get it to work! so ended up removing all SPMs and add them as CocoaPods.

**Comment by thomasvl** [comment]
We just did a 2.0 release where we changed the project layout to use the same sorta layout that Firebase, etc. do, so hopefully this will solve these build related issues for folks.

**Comment by leo150** [comment]
Had the same error after adding [swift-collections](https://github.com/apple/swift-collections) with SPM as the first and only package. `pod deintegrate` doesn't help. Removing the package solved the issue. Rest client 2.0.

**Comment by thomasvl** [comment]
@leo150 if you've got a new repo case, I'd suggest opening a new issue. Since the structure has completely changed, it's likely to be a something different than before.

**Comment by thomasvl** [comment]
fyi - We've gotten no other reports of issues with 2.0, and from have some indications the past issues are gone for others.
