### ISSUE TITLE
Creating a mock for GIDGoogleUser

### ISSUE THREAD

**Issue by mohitathwani** [google/google-api-objectivec-client-for-rest#389]
I have a class called GoogleUserManager which is responsible for handling sign in and sign out with Google. This class conforms to the GIDSignInDelegate protocol. This protocol declares a function

```
- (void)signIn:(GIDSignIn *)signIn
didSignInForUser:(GIDGoogleUser *)user
withError:(NSError *)error;
```

The syntax is in ObjC since I have taken it directly from the Google header, but I am developing my code in Swift.
I am trying to write a unit test to verify the logic I have within this delegate callback. The problem I am running in to is creating a mock for GIDGoogleUser. It looks like GIDGoogleUser has properties for other types like GIDProfileData  and there's no setters available for these properties.

How would I go about testing this callback?

**Comment by thomasvl** [comment]
`GIDSignInDelegate` I believe is part of https://developers.google.com/identity/sign-in/ios and not a part of this project.  This project uses an `authorizer` that conforms to the `GTMFetcherAuthorizationProtocol`, so it doesn't deal with the `GIDSignInDelegate` protocol.  You'll likely need to follow up with their support area about the their specific apis.
