### ISSUE TITLE
Linking to Framework not working on Device

### ISSUE THREAD

**Issue by koedal** [google/google-api-objectivec-client-for-rest#39]
I followed the instructions for Linking to the Framework and it works fine on the simulator.

When trying to run on device I get the following error. I've followed all suggestion on the Internet I've found and not had success yet. 

dyld: Library not loaded: @loader_path/../Frameworks/GTLR.framework/GTLR
  Referenced from: /var/containers/Bundle/Application/B9FEEC03-BF14-4F15-8D58-E934CAAB0EE8/AppName.app/AppName
  Reason: image not found

**Comment by thomasvl** [comment]
When did you last fetch the sources?  This sounds like https://github.com/google/google-api-objectivec-client-for-rest/issues/27

**Comment by koedal** [comment]
I was on v1.0.2. Although, issue #27 wasn't the whole fix.

I also had to add the framework to the Embedded Binaries which isn't mentioned in the documentation but #27 description alluded to.

![embedded binaries](https://cloud.githubusercontent.com/assets/1350867/18064766/7093cc74-6df6-11e6-83a4-25e7c9ce8507.png)

**Comment by thomasvl** [comment]
Thanks, tweaked the docs to hopefully spell that better out.
