### ISSUE TITLE
GTLR.Framework cannot generate.

### ISSUE THREAD

**Issue by kotercy** [google/google-api-objectivec-client-for-rest#397]
I download the project.open the 'source'folder,select 'osx framework and test'target.then I build ,failed.some target files not exist.is there a target contain full files to generate GTLR framework?
 best wishes, thanks

**Comment by thomasvl** [comment]
I can't seem to reproduce the failure.  What version of the library are you checking out?  What version of Xcode are you using?

Using be519851659f18000404761603a4cc24a8aaf216.

Xcode:
```
$ xcodebuild -version
Xcode 12.0
Build version 12A7209
```

Building:
```
$ xcodebuild -project Source/GTLRCore.xcodeproj -scheme "OS X Framework and Tests" -configuration build
...
** BUILD SUCCEEDED **
```

And opening the project doing the same things also seems to succeed.

When you cloned the project, [did you forget to have it fetch the submodules](https://github.com/google/google-api-objectivec-client-for-rest/wiki#subsidiary-libraries)?

**Comment by kotercy** [comment]
the library I checked out is be51985,xcode is Xcode beta 12.2.
the steps I did is below:
1. download the latest zip code  the version is be51985
2.open the download project.the path is google-api-objectivec-client-for-rest-master/source/GTLRCore.xcodeproj
3.in the project is select 'osx framework and test' target.then build,.error!the detail error information is 
in attach file
<img width="885" alt="截屏2020-09-23 上午11 17 11" src="https://user-images.githubusercontent.com/17897001/93962904-72b6fe00-fd8e-11ea-84aa-b84ebc0962b5.png">

I donot know what submodules means。what is  I need to do about this .I open the link can not find information

thanks

**Comment by thomasvl** [comment]
GitHub autogenerates the zips and doesn't include git submodules, and we don't have any control over that.  Either use SwiftPM, CocoaPods, or to use the checked in Xcode projects, just a direct git clone so you can get the submodules.

**Comment by kotercy** [comment]
I use git pull code ,then the target worked.framework generated successfully! 
I am a newbie to macOS develop.can you introduce some books or videos for me to raise the technical levels?
Best regards.

**Comment by thomasvl** [comment]
Glad you got things working.

**Comment by kotercy** [comment]
thank you
