### ISSUE TITLE
Importing framework in iOS app

### ISSUE THREAD

**Issue by Rufy86** [google/google-api-objectivec-client-for-rest#419]
I have difficulty understanding what is the flow of operations to be performed in order to integrate the framework into my ios project. I have followed without any problem the addition of the Sign In with the google button and now I would like to use the google api to manage various services such as the drive and spreadsheet. I understand that I have to use cocoapods but the documentation is not consistent. in some cases it says to call the pod GoogleAPIClientForREST, but in the examples they call GoogleAPIClientForREST / Spreadsheet.

On top of that, I, like many other developers, are developing in swift. The examples are written in Objective-C. I know there are developers (a minority) still developing in Objective-C, but then couldn't you create a (possibly easy to integrate) library written in swift with examples written in swift? Or couldn't you at least write the examples in swift?

In the meantime, could you write in the documentation a succession of clear and simple steps to be performed in order to successfully integrate the framework?

thanks

**Comment by thomasvl** [comment]
Which docs are you referring too?  The wiki pages here or something else?

As far as examples - #234 tracks having Swift examples, that is something someone else could provide PRs for since we haven't had a chance to do it yet.

**Comment by Rufy86** [comment]
I'm referring to the wiki pages here.

The first problem is to have a step-by-step tutorial to add the framework in a iOS project
About the examples, I will take a look to #234 Issue

**Comment by thomasvl** [comment]
Tweaked the wiki.  fyi - CocoaPods isn't the only options, hence how long the page is, we try to cover a few of the methods, but like most integrations, the exact things that can be needed will depend on what a project wants to do.

**Comment by Ahhxjxu** [comment]
- [@[]()]()
