### ISSUE TITLE
iOS framework requires CFBundleShortVersionString

### ISSUE THREAD

**Issue by JonasGessner** [google/google-api-objectivec-client-for-rest#42]
Hey, the iOS framework (not sure about the OS X framework) requires a CFBundleShortVersionString to be uploaded to iTunes Connect. Currently if you build and try to submit you get this error:

```
The Info.plist file is missing the required key: CFBundleShortVersionString.
```

**Comment by thomasvl** [comment]
#52 should have fixed this
