### ISSUE TITLE
Uploading to GCS with a Signed URL

### ISSUE THREAD

**Issue by gshahbazian** [google/google-api-objectivec-client-for-rest#420]
I am looking to into how to upload a file to GCS with a given Signed URL (https://cloud.google.com/storage/docs/access-control/signed-urls).

Is it possible to form a `GTLRStorageQuery_ObjectsInsert` from a given signed url and upload a file with `chunked-resumable` uploading enabled?

**Comment by thomasvl** [comment]
Disclaimer first - those of us that work on this library are familiar with the discovery system and the way these apis work from a REST/JSON pov; but we aren't experts in the 100+ apis that it can generate for.  So for service specific things, you likely will have to use the support/help areas documented on the service api pages.

Taking a quick look, the docs on signed-urls seems to mostly talk about using it with Service Accounts, which tend to be something you see more in server to server communications that client to server.  Odds are `GTLRStorageQuery_ObjectsInsert` could be used to help build up a raw request if that's what you are after.

I'm also not completely sure what you looking for with your questions.  The GTLR apis all support an `authorizer` on the `Service` objects, that which given active credentials automatically add the authorization headers to requests, they don't require interaction unless the user's credentials have been revoked/expired. So I'm not completely clear what your trying to do that is different by wanted signed urls - unless it is service account, which gets to the heart of my initial comment about that being usually more server to server, and baking credentials into client apps means they are basically exposed for someone to extract and reuse/abuse.

**Comment by gshahbazian** [comment]
Hello @thomasvl thanks for the reply! My question is not really about how signed urls work or if they fit the current use case. We've been using them for quite some time to generate temporary urls from a server useful to upload from a client without authenticating the client.

I am currently looking into making use of chunked-resumable uploads to GCS and am curious if `GTLRStorageQuery_ObjectsInsert` could be used with a signed url, rather than specifying the bucket name and item name.

**Comment by thomasvl** [comment]
Ah, clearly I needed a little more coffee.  `GTLRStorageQuery_ObjectsInsert` is geared to what we get from discovery, it doesn't do anything on it's own, and so it _works_ via an `execute` off the Service.  So building up something for this would likely be mostly on your own.  You might be able to use part of the library as examples but without really digging into this services specifics, I don't think there would be anything that close to what it wants.

**Comment by gshahbazian** [comment]
@thomasvl understood, thanks for the info!
