### ISSUE TITLE
How to solve GTMOAuth2WindowController problem with Rest mode

### ISSUE THREAD

**Issue by zldragon** [google/google-api-objectivec-client-for-rest#425]
Hi, sir
   In my previous project, I used GTMOAuth2WindowController as the login interface. And I can get the error message that the Controller is closed in the following way.
    SEL theSel = @selector(windowController:finishedWithAuth:error:);
    [windowController signInWindowModalForWindow:self.superWindow delegate:self finishedSelector:theSel];

However, the new rest method just opens a web page to log in. my question is
 If the user closes the web page during the login process, can the event be obtained?

**Comment by thomasvl** [comment]
This project doesn't directly open any UI for auth, instead it uses a protocol to allow the support from other libraries.  It sounds like you might have been using google/gtm-oauth2, but that was deprecated a while ago, so the issue likely needs to be filed with what ever you are using now.
