### ISSUE TITLE
GTLRDriveQuery_FilesUpdate to update file content, got 403 error

### ISSUE THREAD

**Issue by eschao** [google/google-api-objectivec-client-for-rest#43]
I don't know how exactly use this API to update file content since I didn't get detail information from Document and DriveSample application. Thus, I tried to write it like:

```
GTLRUploadParameters *uploadParameters = [GTLRUploadParameters
                    uploadParametersWithData:data
                                    MIMEType:@"binary/octet-stream"];
GTLRDriveQuery_FilesUpdate *query = [GTLRDriveQuery_FilesUpdate
                                 queryWithObject:cloudPreference
                                          fileId:cloudPreference.identifier
                                uploadParameters:uploadParameters];

[self.driveService executeQuery:query
              completionHandler:^(GTLRServiceTicket *callbackTicket,
                                  GTLRDrive_File *uploadedFile,
                                  NSError *callbackError) {
                  if (callbackError == nil) {
                      NSLog(@"Updating file is finished!");
                  }
                  else {
                      NSLog(@"Failed to update file: %@", callbackError);
                  }
              }];
```

The error is: Failed to update file: **Error Domain=com.google.HTTPStatus Code=403 "(null)" UserInfo={data=<7b226572 726f7222 3a7b2265 72726f72 73223a5b ...**

Actually data is JSON format, I tried MIMEType with "applicaton/json" but still got 403 error. I can't google anything about this API with such error. The file is created by my application and I can download data from Google drive in my application. But I don't know what's wrong with my updating codes, Could anyone help me? Thanks a lot!

**Comment by thomasvl** [comment]
The library has built in [logging](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) that can help figure out what is going on.

**Comment by thomasvl** [comment]
Closing for lack of followup.

**Comment by timeflying** [comment]
http://stackoverflow.com/questions/39178794/use-googledrive-api-gtlrdrivequery-filesupdate-to-update-file-content-got-403
```
GTLRDriveQuery_FilesUpdate *query = [GTLRDriveQuery_FilesUpdate
                                 queryWithObject:cloudPreference
                                          fileId:cloudPreference.identifier
                                uploadParameters:uploadParameters];
```
to
```
GTLRDriveQuery_FilesUpdate *query = [GTLRDriveQuery_FilesUpdate
                                 queryWithObject:[GTLRDrive_File object]
                                          fileId:cloudPreference.identifier
                                uploadParameters:uploadParameters];
```

**Comment by VivekVirani** [comment]
hi, @timeflying your solution is not work for me. I found **Error Domain=com.google.HTTPStatus Code=403 "(null)" UserInfo={data={length = 239, bytes = 0x7b226572 726f7222 3a7b2265 72726f72 ... 61626c65 2e227d7d }, data_content_type=application/json; charset=UTF-8}** this same error. 

**Code:**

` let query = GTLRDriveQuery_FilesGet.query(withFileId: fileId)
        self.service.executeQuery(query) { (ticker, file, err) in
            if err == nil {
                
                let file = file as! GTLRDrive_File
                print(file.name ?? "","get file name")
                file.name = newTitle
                file.descriptionProperty = "new descrit"
                file.mimeType = "*/*"
                
                let uploadParam = GTLRUploadParameters(data: newdata,mimeType: "*/*")/
                let updateQuery = GTLRDriveQuery_FilesUpdate.query(withObject: file, fileId: fileId, uploadParameters: uploadParam)
                
                self.service.executeQuery(updateQuery) { (ticket, uFile, err) in
                    if err == nil {
                        let updated = uFile as! GTLRDrive_File
                        completionBlock(updated,nil)
                    } else {
                        print("rename not worked error occur")
                        completionBlock(nil,err)
                    }
                }
            } else {
                print("main error occur")
                completionBlock(nil,err)
            }
        }`

I don't know what's wrong with above codes, Could anyone help me? Thanks a lot!
