### ISSUE TITLE
Required field externalUserAgent when using Swift

### ISSUE THREAD

**Issue by Neil3079** [google/google-api-objectivec-client-for-rest#437]
I am writing a Swift application, it seems that due to the fact optionality isn't correctly expressed we are unable to call 

`OIDAuthState.authState(byPresenting: request) { (state, error) in
                print(state)
                print(error)
            }`

I am unable to find any documentation on how to create an object conforming to `OIDExternalUserAgent` and I sense that probably is not the best approach. Is there a workaround?

**Comment by thomasvl** [comment]
`OIDAuthState` & `OIDExternalUserAgent` aren't part of this library, I'd suggest using those projects pages for help.
