### ISSUE TITLE
Gmail: Resumable attachment uploads

### ISSUE THREAD

**Issue by abynim** [google/google-api-objectivec-client-for-rest#439]
Does the client support resumable attachment uploads for Gmail? 

All the examples I've seen online seem to suggest using the single-step multipart upload process. Are there any examples that show how to use the three-step process for resumable uploads mentioned in the [Upload Attachments Guide](https://developers.google.com/gmail/api/guides/uploads#resumable)? Is it supported by this client?

**Comment by thomasvl** [comment]
I can't say I've looked specifically at the gmail case.  The library has some support around uploads, but there is also a building block for resumable in [google/gtm-session-fetcher](https://github.com/google/gtm-session-fetcher) (`GTMSessionUploadFetcher`), so you should be able build up something from those parts.

**Comment by Ray5254** [comment]
Hello gmail this issue resumable attach abynim open it and pixe and next time let me know straight away and explain to me on webmitting. If issue hang up not moving  it's mean they creit blocking move to hold stop if they want to do better good  relationship individuals partner what you all think a bout my opinion
