### ISSUE TITLE
Integrating GTLRStorage

### ISSUE THREAD

**Issue by foffer** [google/google-api-objectivec-client-for-rest#44]
I'm finding it very difficult to integrate the Storage module. I see there is submodules defined in the podspec, but cocoapods doesn't seem to pull the down, even if specified with /Core at the end.

I've also tried to follow the guide and generate a service, but the guide tells your to generate the service with the --gtlrFrameworkName flag, which doesn't work. So I'm a bit stuck.

EDIT: Included Podfile

```
target 'MyApp Intra' do
  use_frameworks!
  # Pods for MyApp
  pod 'FirebaseOSX'
  pod 'GTMOAuth2'
  pod 'GoogleAPIClientForREST'
  //I've tried below as well. And both together
  pod 'GoogleAPIClientForREST/Core'
  pod 'Alamofire'
  pod 'Sparkle', '~> 1.10'
  pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git', :branch => '4.x'
end
```

**Comment by thomasvl** [comment]
Can you post what your pod file looks like and what errors you go so folks can try to see what is going wrong?

**Comment by foffer** [comment]
@thomasvl sorry, of course. See above

**Comment by thomasvl** [comment]
```
pod 'GoogleAPIClientForREST/Storage'
```

doesn't work?

**Comment by foffer** [comment]
For some stupid reason I though I had to declare it with /Core. This works. Sorry for wasting your time :/ Thanks, Chris
