### ISSUE TITLE
Accessing GTLRAdMob_GenerateNetworkReportResponse crashes application

### ISSUE THREAD

**Issue by NickAtGit** [google/google-api-objectivec-client-for-rest#447]
Hey there, I'm currently playing around with the AdMob API and I want to get the daily estimated earnings via the `GTLRAdMob_GenerateNetworkReportRequest` but when I access the report the application crashes with `Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM allKeys]: unrecognized selector sent to instance 0x282582a30'`. I do see valid data in the debugger and when I print report.json I see correct json but when I try to access report.row/header/footer or printing like below it crashes. Am I missing something?

```
        let reportSpec = GTLRAdMob_NetworkReportSpec()
        let dateRange = GTLRAdMob_DateRange()
        let startDate = GTLRAdMob_Date()
        startDate.day = 2
        startDate.month = 4
        startDate.year = 2021
        
        dateRange.startDate = startDate
        dateRange.endDate = startDate
        reportSpec.dateRange = dateRange
        reportSpec.metrics = [kGTLRAdMob_MediationReportSpec_Metrics_EstimatedEarnings]
        
        let reportRequest = GTLRAdMob_GenerateNetworkReportRequest()
        reportRequest.reportSpec = reportSpec
        let query = GTLRAdMobQuery_AccountsNetworkReportGenerate.query(withObject: reportRequest, parent: name)
        
        service.executeQuery(query) { ticket, object, error in  //service is GTLRAdMobService
            
            print(ticket)
            print(error)
            
            
            if let report = object as? GTLRAdMob_GenerateNetworkReportResponse {
                print(report)
            }
        }
```

**Comment by NickAtGit** [comment]
<img width="1193" alt="Bildschirmfoto 2021-04-03 um 13 46 56" src="https://user-images.githubusercontent.com/7500549/113477571-104c6200-9483-11eb-8e48-8bb4a96c9f3a.png">
I think that must be a bug in the lib. In `GTLRObject.m` we expect a dictionary but the actual data is an array...

**Comment by NickAtGit** [comment]
I temporarily fixed the method for me but I think it needs more than this in the future...

```
 - (id)JSONValueForKey:(NSString *)key {
     
   if ([self.JSON isKindOfClass:[NSMutableDictionary class]]) {
     id obj = [self.JSON objectForKey:key];
     return obj;
   }
     
     if ([self.JSON isKindOfClass:[NSArray class]]) {
         
         NSArray *array = (NSArray *)self.JSON;
         
         for (int i = 0; i < [array count]; i++)
         {
             NSDictionary *dict = array[i];
             if ([dict valueForKey:key] != nil) {
                 return [dict valueForKey:key];
             }
         }
     }
     
     return nil;
 }
 ```

**Comment by thomasvl** [comment]
Any chance you can send in a [log of the data](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) your are seeing so we can look more specifically?  Do you get the failure when accessing specific fields or just when you try to turn it into a Response?

**Comment by NickAtGit** [comment]
How can I send you the logs in private? The logs contain sensitive data. I can also anonymise the logs if needed.

**Comment by NickAtGit** [comment]
> Do you get the failure when accessing specific fields or just when you try to turn it into a Response?
I get the crash when accessing fields.

**Comment by thomasvl** [comment]
Did a little digging, and the problem is the library code (and generated code) is correct for what is in the [discovery document](https://admob.googleapis.com/$discovery/rest?version=v1).  From the defined objects:

```json
    "GenerateNetworkReportResponse": {
      "id": "GenerateNetworkReportResponse",
      "type": "object",
      "properties": {
        "footer": {
          "description": "Additional information about the generated report, such as warnings about the data.",
          "$ref": "ReportFooter"
        },
        "row": {
          "$ref": "ReportRow",
          "description": "Actual report data."
        },
        "header": {
          "description": "Report generation settings that describes the report contents, such as the report date range and localization settings.",
          "$ref": "ReportHeader"
        }
      },
      "description": "The streaming response for the AdMob Network report where the first response contains the report header, then a stream of row responses, and finally a footer as the last response message. For example: [{ \"header\": { \"dateRange\": { \"startDate\": {\"year\": 2018, \"month\": 9, \"day\": 1}, \"endDate\": {\"year\": 2018, \"month\": 9, \"day\": 1} }, \"localizationSettings\": { \"currencyCode\": \"USD\", \"languageCode\": \"en-US\" } } }, { \"row\": { \"dimensionValues\": { \"DATE\": {\"value\": \"20180918\"}, \"APP\": { \"value\": \"ca-app-pub-8123415297019784~1001342552\", displayLabel: \"My app name!\" } }, \"metricValues\": { \"ESTIMATED_EARNINGS\": {\"microsValue\": 6500000} } } }, { \"footer\": {\"matchingRowCount\": 1} }]"
    },
```

and from the definition of the query:

```
      "resources": {
        "networkReport": {
          "methods": {
            "generate": {
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly",
                "https://www.googleapis.com/auth/admob.report"
              ],
              "parameterOrder": [
                "parent"
              ],
              "parameters": {
                "parent": {
                  "description": "Resource name of the account to generate the report for. Example: accounts/pub-9876543210987654",
                  "required": true,
                  "location": "path",
                  "type": "string",
                  "pattern": "^accounts/[^/]+$"
                }
              },
              "streamingType": "SERVER_SIDE",
              "request": {
                "$ref": "GenerateNetworkReportRequest"
              },
              "flatPath": "v1/accounts/{accountsId}/networkReport:generate",
              "id": "admob.accounts.networkReport.generate",
              "response": {
                "$ref": "GenerateNetworkReportResponse"
              },
              "httpMethod": "POST",
              "path": "v1/{+parent}/networkReport:generate",
              "description": "Generates an AdMob Network report based on the provided report specification. Returns result of a server-side streaming RPC. The result is returned in a sequence of responses."
            }
          }
        },
```

So there's nothing that says this actually returns a list of those objects instead of a single instance.  It appears the `streamingType` might be a hint it isn't something [documented](https://developers.google.com/discovery/v1/reference/apis).

I first stumbled into these in Q4 2020, so I've gone back and asked more questions on those threads so try and get some clarity on how clients are supposed to handle these, but at the moment they seem to be something we can't directly deal with in generators with the documented information.  ☹️

**Comment by NickAtGit** [comment]
@thomasvl thanks for the digging. But I'm not 100% sure what your message means to me. Is it a bug or am I using the API wrong?

**Comment by NickAtGit** [comment]
I found just this Issue #372 which also mentions a crash in the same method...

**Comment by thomasvl** [comment]
This isn't a bug in the library or an error on your side.  The problem is how the api is describing itself, it seems like no client will be able to generate for what is really returned with what is currently documented.
