### ISSUE TITLE
Fetching files from drive

### ISSUE THREAD

**Issue by tharak** [google/google-api-objectivec-client-for-rest#45]
Hi, I'm trying to print some JSON files from my drive and I keep getting this message: 
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
Here is the code:

```
class func googleDriveFetchFiles(){
    print("Getting files...")
    let query = GTLQueryDrive.queryForFilesList()
    query.fields = "nextPageToken, files(id, name, webViewLink, webContentLink, mimeType)"
    query.mimeType = "application/vnd.google-apps.json"
    service.executeQuery(
        query,
        delegate: self,
        didFinishSelector: #selector(self.finishedDriveQuery(_: fileList: error:))
    )
}

class func finishedDriveQuery(ticket : GTLServiceTicket, fileList : GTLDriveFileList, error : NSError?) {
    if let error = error {
        print(error.localizedDescription)
        return
    }
    if let files = fileList.files  as? [GTLDriveFile] where !files.isEmpty{
        print("Found \(files.count):")
        for file in files {
            let fileURL = "https://www.googleapis.com/drive/v3/files/\(file.identifier)?alt=media"
            fetchFile(fileURL)
        }
    } else {
        print("No files found.")
    }
}

class func fetchFile(fileURL: String){
    let fetcher = service.fetcherService.fetcherWithURLString(fileURL)
    fetcher.beginFetchWithCompletionHandler({ (data, error) -> Void in
        if error == nil {
            print(data)
        } else {
            print("An error occurred: " + error!.localizedDescription)
        }
    })
}
```

this prints:
Getting files...
Found 10:
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)
An error occurred: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)

Why is it returning 403? I'm already authenticated because I'm can get the files id's right?

**Comment by thomasvl** [comment]
Drive cab be a little pick on what files can be exported vs. fetch with a get.  In the Example, we support both modes, and rather then building the URL yourself, you can also use the api to do it (not the use of the _Media_ versions of the methods: https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Examples/DriveSample/DriveSampleWindowController.m#L241

To trouble shoot things, it usually helps to use the built in [logging](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic), as there can be more details within the json payload that you aren't currently reporting.

**Comment by tharak** [comment]
Found the solution,
on API Manager/Dashboard/Google Drive API/Drive UI Integration, select Multiple file support, put a  icon image so you can enable the save button, click on save changes. Re-auth on the app. Change fetchFile method to:

class func fetchFile(fileURL: String){
        let fetcher = service.fetcherService.fetcherWithURLString(fileURL)
        fetcher.authorizer = service.authorizer
        fetcher.beginFetchWithCompletionHandler({ (data, error) -> Void in
            if error == nil {
                if let data = data {
                    if let json = String(data: data, encoding: NSUTF8StringEncoding){
                        print(json)
                    }
                }
            } else {
                print(fetcher.response)
                print("An error occurred: " + error!.localizedDescription)
            }
        })
    }

**Comment by tharak** [comment]
@thomasvl  i tried to use query for downloading but GTLQueryDrive has no such query "queryForMediaWithFileId"

**Comment by thomasvl** [comment]
That query method is in the library replacing this one: https://github.com/google/google-api-objectivec-client-for-rest-for-rest.  See the note on the README.md for this repo.

**Comment by thomasvl** [comment]
Oops, scratch that, juggling to many thing, you are on the right project.

**Comment by thomasvl** [comment]
Well, I take that back.  GTLR does have the method; but looking again, you talked about `GTLQueryDrive`, so it seems you are commenting on GTLR's issue tracker, but you are using the sources from the older GTL project.

**Comment by tharak** [comment]
Damn.. I must have changed the sources the other day while I was failing to get the files with the REST version. Thanks for your help, I will try to use the REST version now that I have a working project with the old version.
