### ISSUE TITLE
app/src/main/res/values-pl/strings.xml

### ISSUE THREAD

**Issue by piyaphart90** [google/google-api-objectivec-client-for-rest#454]
app/src/main/res/values-pl/strings.xml

_Originally posted by @piyaphart90 in https://github.com/k0shk0sh/FastHub/pull/2982#pullrequestreview-653982353_

**Comment by piyaphart90** [comment]
app/src/main/res/values-pl/strings.xml

**Comment by saper1980** [comment]
# #
