### ISSUE TITLE
Campaign Manager - dfareporting_utils 

### ISSUE THREAD

**Issue by pjodonova** [google/google-api-objectivec-client-for-rest#483]
Hi there - Most of the [sample](https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v3_4/download_file.py) py download or create reports for GCM rely on the "import dfareporting_utils" but even after pip installing google-api-python-client I am getting an error message that no module is found.  Is there a way I can install this module?

Thanks!

**Comment by thomasvl** [comment]
Sounds like you are asking about the some Python package?  This is a library with Objective-C code, so usable from ObjC or Swift.  Sounds like you need to ask on another project.
