### ISSUE TITLE
CM360 API: connecting issues

### ISSUE THREAD

**Issue by vinsthe** [google/google-api-objectivec-client-for-rest#484]
Dear all,
I’m trying to use CM360 API via Java but unfortunately I’m facing a connection issue.

Attached you have the json file needed to connect and the java class used to connect to the API service.
The attached code sample is taken from your page (https://support.google.com/campaignmanager/answer/2835059?hl=en#zippy=%2Chow-can-i-get-help-with-the-apis).

Running it, I got the following error:

nov 12, 2021 10:58:58 AM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
AVVERTENZA: unable to change permissions for everybody: C:\Users\vinmosch\.store\dfareporting_sample
nov 12, 2021 10:58:58 AM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
AVVERTENZA: unable to change permissions for owner: C:\Users\vinmosch\.store\dfareporting_sample
credential => com.google.api.client.auth.oauth2.Credential@6842775d
Exception in thread "main" java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setResponseReturnRawInputStream(Z)Lcom/google/api/client/http/HttpRequest;
      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:434)
      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
      at com.sapient.qa.campaignmanager.CampaignManagerAPI.main(CampaignManagerAPI.java:59)

Would you be so kind to help me on sorting out the issue?

Another moment, I was not able to find how to make/reproduce a search as it can be done via the website https://campaignmanager.google.com:
•	By specifying the Account value(in my case is 718661);
•	By specifying the AD value;
•	By specifying the ads to be searched;
Sample url: https://campaignmanager.google.com/trafficking/#/accounts/718661/advertisers/9928394/creatives?q=CD~Jeep-renegade-September_LG~ES_TA~PIDE-TU-OFERTA_PR~RENEGADE_SZ

Any help from you is really appreciated.

Thanks in advance,
Vincenzo

[files.zip](https://github.com/google/google-api-objectivec-client-for-rest/files/7538459/files.zip)

**Comment by thomasvl** [comment]
Since you seem to be asking about Java, it sounds like your question is for some other project and not related to this project.  This is the client library for Objective-C.

**Comment by vinsthe** [comment]
Hi @thomasvl,
I was addressed to this project by Google.
Can you please share to me if there is a similar projet for Java?

Thanks in advance,
Vincenzo

**Comment by thomasvl** [comment]
There's a lot of different folks working on a lot of different Google projects, so we can't all speak for everything.

The page you initial reference appears to have a _Need more help_ section, so I'd suggest starting with that.
