### ISSUE TITLE
Usage on Linux

### ISSUE THREAD

**Issue by nehalvpatel** [google/google-api-objectivec-client-for-rest#493]
Hello!

## Background

For context, I've been trying to add this as a dependency to a SPM project on Ubuntu 20.04.

Although Swift has the ability to interop with Objective-C code, there are a few roadblocks:
- This package relies on the Objective-C runtime (`objc/runtime.h`), which AFAIK is not possible to directly use on Linux.
- This package relies on Foundation (`Foundation/Foundation.h`). Apple has an effort to bring Foundation functionality to Linux targets with [swift-corelibs-foundation](https://github.com/apple/swift-corelibs-foundation). This is unfortunately not possible to use in this case because it is a pure Swift shim and only usable from Swift code. Since this package is Objective-C based, there is no way for the shim to do its work pre-interop.

There already are a few Swift-based REST clients for the Google API, and I'm probably going to be using one of those unless someone chimes in here with a solution. 😄

## Mea culpa

I understand if providing Linux support is out of scope for this project. It is not my intention to ask you to expand your scope. I'm mainly trying to see if using this package is possible at all on Linux. With that said, it might be helpful to start a discussion about this for other people also looking to use this package on Linux.

## Possible solutions

- 🦄:  I don't imagine that this is trivially possible, but a community-organized fork that removes the reliance on the Objective-C runtime and Foundation. If Linux support is considered to be within the scope for this REST client, this could be Google-led.
- ❓: A way to cross-compile this library to a Linux target while building on macOS. I know cross-compilation is possible, but I'm not sure if it's possible to make a static binary like this that would just work on Linux without the Objective-C runtime being present.
- ⚠️: A community-organized rewrite in Swift. If Linux support is considered to be within the scope for this REST client, this could be Google-led. I imagine this might be something on the roadmap anyway and probably is something you would not want to comment on.

**Comment by thomasvl** [comment]
Swift on Linux doesn't support Objective-C.  So supporting linux would be a completely new project/complete rewrite to be Swift only.  And in being Swift only, it would no longer be able to support existing ObjC users.  So as you guess, being Swift only and thus supporting linux is out of scope for this project.
