### ISSUE TITLE
DCM API Migration Issue

### ISSUE THREAD

**Issue by loliveira-leega** [google/google-api-objectivec-client-for-rest#495]
Hi

We are facing some issue with the DCM API migration. 

The documentation guide still using v3.4: 
![image](https://user-images.githubusercontent.com/83982205/148432249-077e7c5c-b051-42f4-84f9-3c966bc2ba6b.png)

So i found a github example (suggested by google documentation):
https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v3_5/authenticate_using_user_account.py

![image](https://user-images.githubusercontent.com/83982205/148432304-5d4b1d5a-17ea-4ff4-838d-1b3f3337f379.png)

When a try this i got this error:
![image](https://user-images.githubusercontent.com/83982205/148432385-ab1f8add-0691-4679-b808-159f84dd7751.png)

Could you help us please?

cordially,
Lucas

**Comment by thomasvl** [comment]
It looks like you are asking about a python library?  This project is for an Objective-C library.  You likely need to find the correct github project for what you are using.
