### ISSUE TITLE
Error each time the version is updated using Cocoapods: Need to add 2 lines of code to GLTRService.h to fix

### ISSUE THREAD

**Issue by ghb101** [google/google-api-objectivec-client-for-rest#506]
Any time a new version is available and installed using CocoaPods, there is an  error in running my app. 
A while ago I found a fix online, which was the following.

**Add the following lines to the GLTRService.h file in the GoogleAPIForClientRest/Core folder
#import <GTMSessionFetcher/GTMSessionFetcher.h>
#import <GTMSessionFetcher/GTMSessionFetcherService.h>**

This solves the issue, but has to be done every time a new version is updated via CocoaPods.  Just wondering if this is a known issue and if it can be fixed.

**Comment by ghb101** [comment]
Thanks Thomas...I see the docs at https://github.com/google/google-api-objectivec-client-for-rest/wiki/BuildingTheLibrary reference adding the lines below for the GTLRService.h file when using CocoaPods. 

#import <GTMSessionFetcher/GTMSessionFetcher.h>		
#import <GTMSessionFetcher/GTMSessionFetcherService.h>

 When I was dealing with the issue over a year ago this was not available and it took a while to figure out the issue. Each time the  POD is updated it takes me a minute to remember that this issue reappears and I have to import those lines again.  Not a big deal, just wondered if there was a way to not have to go through that each time a new version is updated via CocoaPods.

It would be great to be able to use this library via SwiftPM.  I'm trying migrate all my CocoaPod integrations to SwiftPM.  I tried with this library but too many errors to solve...didn't realize it wasn't an option yet.

**Comment by thomasvl** [comment]
I think you are referring to the directions that talk about adding them to your own bridging header, not having to modify the library.
