### ISSUE TITLE
Upload creative files to CM360

### ISSUE THREAD

**Issue by JoseLuisCR2022** [google/google-api-objectivec-client-for-rest#535]
Hello, sorry for my English but I'm from Uruguay, I'm using the google.dfareporting client library in node js and I'm not sure how to upload a creative file to Campaign manager 360.
My specific question is: Is there a method within the google.dfareporting library to upload creative files?
Thanks for your time!

**Comment by thomasvl** [comment]
This issue tracker is for this Objective-C library, it isn't specific to the dfareporting api. You should try the listed [support options](https://developers.google.com/doubleclick-advertisers/get-support) for that api.
