### ISSUE TITLE
DCM API Assistance needed

### ISSUE THREAD

**Issue by AhmadMaherIsmail** [google/google-api-objectivec-client-for-rest#555]
Hello,

I am facing a problem with the DCM API using Python. I implemented a code based on the ones you had on Github. Basically, what is happening is that the code creates trackers on the Advertiser level, links them to the campaign, and then assigns the creative to it's respective placement

I want to hand out the project to other team members, but I would rather have them given an executable file, which is why, I have installed pyinstaller Library and converted the code. However, when trying to execute the code, it is prompting an error regarding OAuth2, taking into consideration, it is well tested and was working perfectly fine

The error is: "WARNING: Please configure OAuth 2.0. To make this sample run you will need to populate the client_secrets.json file found at "A specific path"". Noting that the file is already there in the directory path they stated

Attached an error screenshot for reference

Are there any ideas/suggestions to make that work?

Thank you in advance, Team! Your help is highly appreciated!
![Capture](https://user-images.githubusercontent.com/56027136/180167123-ce53c6d3-f5ef-4cda-aaf5-2be38ec698f0.PNG)

**Comment by thomasvl** [comment]
This is the issue track for an Objective-C library that works with REST+JSON apis; and for issues with that library, not the services specifically. I'd suggest you check the support pages for the library/api you are using and as in their specific locations.
