### ISSUE TITLE
CM360 API Issue

### ISSUE THREAD

**Issue by AhmadMaherIsmail** [google/google-api-objectivec-client-for-rest#563]
Hello
I am trying to change the tag setting of every placement in the placements_id array in a code for tracker assignment I implemented
This is the function I developed:
"
# change placement tag setting
def change_placement_tag_setting(profile_id, placement_id, tag_setting, service):
    placement = {
        "id": placement_id,
        "tagSetting": {
            "includeClickThroughUrls": "false",
        },
    }

    request = service.placements().patch(profileId=profile_id, body=placement)

    # Execute request and pprint response.
    response = request.execute()

    pprint(
        "Placement with ID %s is now associated with campaign %s."
        % (response["id"], response["name"])
    )

    return response["id"]
"

and this is it's call from the main function:
"
for placement_name, placement_id in tqdm(placement_ids.items()):
        change_placement_tag_setting(profile_id, id, "true", service)
"

It is providing me an error that states: TypeError: Missing required parameter "id" pinpointing the last line of code shared
Any ideas?

**Comment by thomasvl** [comment]
The issue tracker for for an Objective-C library, looks like your code might be python?  I'd suggest you try opening an issue on that project or on whatever forum they suggest for questions.
