### ISSUE TITLE
GCM360 Python sample code not working

### ISSUE THREAD

**Issue by tonyluo7** [google/google-api-objectivec-client-for-rest#564]
Following sample code returns "INTERNAL: Error processing the request"

GCM360 sample code,

(https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v4/insert_offline_user_conversion.py)

My python testing code, using service account 

https://github.com/tonyluo7/GCM360-PUBTest

I can provide my private key if required, thanks!

**Comment by thomasvl** [comment]
This repository and issues track are for an Objective-C library, not a python library.  I'd suggest you use the help area referenced from the site for the api in question.

**Comment by tonyluo7** [comment]
Will do, this link is provided by GCM help desk though. 

"However, should the issue be persistent on your end, would you be able to confirm that you are also encountering the same error using our [API Explorer](https://developers.google.com/doubleclick-advertisers/rest/v4/conversions/batchinsert?hl=en&apix=true)? Asking this because if you only encounter this using the [sample code from our client library](https://github.com/googleads/googleads-dfa-reporting-samples/tree/master/python/v4), we would highly suggest that you reach out to the [developer's support specialist](https://github.com/google/google-api-objectivec-client-for-rest/issues) as they are the one who maintains our client libraries and would be the best people to help with your integration."

**Comment by thomasvl** [comment]
Where's that quote from?  I'm not sure why they are pointing you here.

Your _API Explorer_ link has a _Support_ section at the top: https://developers.google.com/doubleclick-advertisers/get-support?hl=en

**Comment by tonyluo7** [comment]
It's from following support forum, the code I were advised to add didn't work either. 

https://groups.google.com/g/google-doubleclick-for-advertisers-api/c/OeJBjBh-_lE

**Comment by thomasvl** [comment]
Thanks, I'll reach out to try and make sure they send folks to better places in the future.
