### ISSUE TITLE
'Foundation/Foundation.h' file not found

### ISSUE THREAD

**Issue by pierdr** [google/google-api-objectivec-client-for-rest#57]
I'm trying to compile GTLRiOSCore and/or GTLROSCore with no luck. I tried both from within the examples or from the GTLRCore.xcodeproj in Sources but what I get in both cases is 'Foundation/Foundation.h' file not found.

![screen shot 2016-10-24 at 4 21 48 pm](https://cloud.githubusercontent.com/assets/2287727/19649488/47d81b3c-9a06-11e6-80fe-c630cb7caa57.jpg)

I'm on macOs 10.11.4 and using Xcode 7.3.
Anyone encountered the same problem?

**Comment by thomasvl** [comment]
Are there any other errors/warnings given when you opened the projects?  Foundation is part of the system libraries, so it sounds like something is very wrong with Xcode.

**Comment by pierdr** [comment]
This has been probably my fault, so I launch the "buildStripHeaders" that is in every example folder, and somehow it deleted all the .h files on my whole computer! 

I have no idea how this is possible but it happened. Now restoring everything with time machine.
