### ISSUE TITLE
Insecure API when using in React Native iOS app

### ISSUE THREAD

**Issue by master4-2021** [google/google-api-objectivec-client-for-rest#579]
There are some insecure APIs that exists in this repository that Apple considered insecure and recommended not using:
https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1

These are reported when using Mobile Security Framework (https://github.com/MobSF/Mobile-Security-Framework-MobSF) to scan the IPA.

strlen:
https://github.com/google/google-api-objectivec-client-for-rest/blob/883b23e77b63028ef41ace7148f9f308775f99de/Sources/Core/GTLRBase64.m#L84
https://github.com/google/google-api-objectivec-client-for-rest/blob/883b23e77b63028ef41ace7148f9f308775f99de/Sources/Core/GTLRRuntimeCommon.m#L227
https://github.com/google/google-api-objectivec-client-for-rest/blob/883b23e77b63028ef41ace7148f9f308775f99de/Sources/Core/GTLRRuntimeCommon.m#L276

I understand that the use of these function does not definitely leads to security issues, but I want to bring this to your attention, and check if these are safe to use within our application.

**Comment by thomasvl** [comment]
The GTLRBase64.m call is fine, this is in some UTF-8 conversion code from Foundation, if someone wants to look a submitting a PR it might be possible to tweak it to do the conversion and get the length at the same time.

The two calls in GTLRRuntimeCommon.m are from apis that only vend cstrings, so strlen is the correct call and the way the value is used is correct.
