### ISSUE TITLE
404 /resumable/upload/drive/v3/files

### ISSUE THREAD

**Issue by R4N** [google/google-api-objectivec-client-for-rest#580]
Appreciate this library and have been using it for years.

Currently using v2.0.0, but also tested updating to v3.0.0 (and updating package dependencies) and the same thing is occurring there.

We've recently run into an issue where it seems like the resumable upload path is returning 404 when attempting to upload files using the GTLRDriveService. We haven't made any recent adjustments to our code which interfaces with the driveService or handles the upload/download query setup.

Other creates without the resumable path appears to be working correctly.

Here's a small code snippet example of one of the queries:

```
- (void)_sampleUpload {
    GTLRDriveService *service = self.driveService2;
    // some previous logic had an uploadProgressBlock set, and we're clearing it out here
    // dont think this is relevant and all, but wanted to leave it in there for completeness
    [service setUploadProgressBlock:nil];
    GTLRUploadParameters *uploadParameters = [GTLRUploadParameters uploadParametersWithFileURL:self.sampleFileURL MIMEType:ZTDriveDatabaseFileMIMEType];
    GTLRDrive_File *remoteFile = [GTLRDrive_File object];
    remoteFile.name = @"test.txt";
    // this folder identifier was retrieved from a previous query and is confirmed to be correct
    remoteFile.parents = @[self.folderIdentifier];
    // our custom mime type
    remoteFile.mimeType = ZTDriveDatabaseFileMIMEType;
    GTLRDriveQuery_FilesCreate *query = [GTLRDriveQuery_FilesCreate queryWithObject:remoteFile uploadParameters:uploadParameters];
    [service executeQuery:query completionHandler:^(GTLRServiceTicket * _Nonnull callbackTicket, GTLRDrive_File * _Nullable folderItem, NSError * _Nullable callbackError) {
        // callbackError contains 404 error
    }];
}
```

I've enabled GTMSessionFetcher logging, and this is the result of the query which fails:

```
2023-03-02 17:15:01 +0000      drive.files.create      request/response log
elapsed: 0.100sec
request: POST https://www.googleapis.com/resumable/upload/drive/v3/files?prettyPrint=false
   headers: 9    authorized
   data: 117 bytes, application/json; charset=utf-8
response:  status 404 not found  ⚑
   headers: 10 
   data: 1603 bytes, text/html
```

Adjusting the property of the `GTLRUploadParameters` to upload with a single request as follows:

```
    uploadParameters.shouldUploadWithSingleRequest = YES;
```

succeeds without issue (different file size as I was using a different test file here, but same code path other than changing the above upload param):

```
2023-03-02 17:40:02 +0000      drive.files.create      request/response log
elapsed: 0.985sec
request: POST https://www.googleapis.com/upload/drive/v3/files?prettyPrint=false&uploadType=multipart
   headers: 6    authorized
   data: 16644 bytes, multipart/related; boundary=END_OF_PART
response:  status 200
   headers: 10 
   data: 129 bytes, application/json
```

When digging into the `error.userInfo["data"]` which is returned with the 404 error code, this is the only thing I could locate within it which seemed to point to the error reason:

```
  <p><b>404.</b> <ins>Thatâs an error.</ins>
  <p>The requested URL <code>/resumable/drive/v3/files?prettyPrint=false</code> was not found on this server.  <ins>Thatâs all we know.</ins>
```

One thing I noticed which was a little bit odd, is that the error details (within the html above) seems to have a different path than the request which was logged:

`/resumable/drive/v3/files?prettyPrint=false` from html error details vs `/resumable/upload/drive/v3/files?prettyPrint=false` from the logged request.

I took a look to see if maybe the resumable upload path had changed, but didn't notice that it had.

Has something related to resumable uploads (or its path) changed at all recently? We've just started experiencing/receiving this error in the last few days.

**Comment by thomasvl** [comment]
If you haven't made any changes, then there's a chance something has changed on the server side.  I'd suggest looking at the Drive api page for what they suggest for feedback/help and follow up there (use the http logs).  That should get the help from people who know that specific service.  Since this library supports ~250 services, we aren't able to really tack all the ins and outs of each service that can be generated for.

**Comment by R4N** [comment]
@thomasvl 

Thanks for the response and recommentation. Will look for where to ask in the Drive api page, appreciate it.

**Comment by stevendev** [comment]
We have the exactly same issue. Any solutions?

**Comment by nebulabox** [comment]
Our customer also had the same problem, unable to upload files.
The Android SDK works fine, only the Objective-C SDK failed. 
This is probably an issue with the sdk codes, so please don't close this issue.

**Comment by R4N** [comment]
Just wanted to follow up here with the response I received from the Google Drive API team:

>I appreciate the information provided and after investigating the behavior you reported I concluded the 404 error might be an expected behavior due to the endpoint currently in use in your code implementation. According to the details you provided the endpoint you shared is the following:
https://www.googleapis.com/resumable/drive/v3/files?prettyPrint=false
According to the Google Drive API documentation the POST request should be made through the up to date endpoint which is the following:
https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable
Here you can check details on this matter: https://developers.google.com/drive/api/guides/manage-uploads#initial-request

We're obviously not constructing either of those urls but deferring them to the client library to generate.

When looking at the Drive API documentation here: https://developers.google.com/drive/api/guides/manage-uploads#uploading for multiple request (which I believe is the default unless you set the `shouldUploadWithSingleRequest` upload parameter)

>If the upload request is interrupted, or if you receive a 5xx response, follow the procedure in [Resume an interrupted upload](https://developers.google.com/drive/api/guides/manage-uploads#resume-upload).

Then within the Resume an interrupted upload section of the documentation (linked above) it mentions that 404 means that the upload session has expired and to restart the upload:

>A 404 Not Found response indicates the upload session has expired and the upload must be restarted from the beginning.

So my speculation is that this is what's occurring (haven't actually confirmed this):

1. The resumable multi-request upload starts.
2. It's interrupted, so it attempts to go through the "resume interrupted upload" flow.
3. The callbackError in the completion block is code 404, indicating the upload session has expired (this is where we're reporting the error and bailing out).

This makes me curious if we should be checking the error code in the completion block and trying to retry the upload if we receive 404 (and possibly handle 308 as mentioned in the resume upload Google Drive API documentation)?

I did test retrying the upload if receiving a 404 locally and it seemed to work (after receiving a few 404's).

From the Drive sample code here for uploading a file: https://github.com/google/google-api-objectivec-client-for-rest/blob/main/Examples/DriveSample/DriveSampleWindowController.m#L785

If the callbackError is nil its assumed to have completed successfully, but if it's filled, then it's assumed to be an error and displayed in the interface.

So maybe something has changed server side in the way that resumable uploads are handled (or how they are being interrupted) and either the client library or we are supposed to handle it differently?

**Comment by thomasvl** [comment]
Also from some discussions within Google:

https://developers.google.com/drive/api/guides/manage-uploads says the uploads should be using `https://www.googleapis.com/upload/drive/v3/files`, but looking at the discovery document (`https://www.googleapis.com/discovery/v1/apis/drive/v3/rest`), they tend to have entries like:

```json
"protocols": {
 "simple": {
  "multipart": true,
  "path": "/upload/drive/v3/files"
 },
 "resumable": {
  "multipart": true,
  "path": "/resumable/upload/drive/v3/files"
 }
}
```

Which seems to conflict on the urls to use for resumable vs. simple.

So the's some checking being done to see why things differ/changed, as the core library hasn't change in a very long time (just new service generation being done for updates), it seems like things weren't expected to break.

**Comment by thomasvl** [comment]
Sounds like the server side folks identified an issue and addressed it, closing this again.
