### ISSUE TITLE
Failed to upload file to Google Drive

### ISSUE THREAD

**Issue by nebulabox** [google/google-api-objectivec-client-for-rest#581]
GTMSessionFetcher invoking fetch callbacks, data {length = 1630, bytes = 0x3c21444f 43545950 45206874 6d6c3e0a ... 2e3c2f69 6e733e0a }, error Error Domain=com.google.HTTPStatus Code=404 "(null)" UserInfo={data={length = 1630, bytes = 0x3c21444f 43545950 45206874 6d6c3e0a ... 2e3c2f69 6e733e0a }, data_content_type=text/html; charset=UTF-8}

**Comment by admchm** [comment]
I am also not able to upload a file to Google Drive. I will try to provide some logs a little bit later.

**Comment by thomasvl** [comment]
Similar to #580 - The library hasn't changed in this space, and if you haven't made any changes, then it is likely something on the server side, I'd suggest using the Drive api specific help pages and sharing with them the HTTP logs to show them what is going over the wire.

**Comment by admchm** [comment]
Thank you @thomasvl. It seems like the issue has been fixed over the weekend.

**Comment by thomasvl** [comment]
Sounds like the server side folks identified an issue and addressed it, glad things are working.
