### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by MrEri** [google/google-api-objectivec-client-for-rest#589]
![截屏2023-04-12 22 40 48](https://user-images.githubusercontent.com/14019719/231494039-0dd5ae27-6ddd-4250-b0a6-abb66a5ee157.png)

**Comment by thomasvl** [comment]
When did you last update the repo?  #587 went in just a few minutes ago to address an issue with the Examples.  Try updating your copy  and rerun `pod install` and see if that helps.

**Comment by thomasvl** [comment]
And `main` has now been updated to use GTMAppAuth 3.0 for the examples.
