### ISSUE TITLE
Configure range with multiple sheet

### ISSUE THREAD

**Issue by paul-lavoine** [google/google-api-objectivec-client-for-rest#593]
Hello,

I struggle with the Sheet request API

I try to create a **GTLRSheets_Request**.
I created an object **GTLRSheets_DeleteRangeRequest**
I try to configure my item with a range like for exemple, I would like the following range : 'ID_Sheet_1!A0:B9'

So when I create my item in Swift 
```
  let gridRange = GTLRSheets_GridRange.init()
  gridRange.startColumnIndex = NSNumber(value: 0)
  gridRange.endColumnIndex = NSNumber(value: 1)
  gridRange.startRowIndex = NSNumber(value: 0)
  gridRange.endRowIndex = NSNumber(value: 9)

  gridRange.sheetId = NSNumber(value: 0)     //   --->  I struggle with this one
```

I guess the **sheetId** should be the ID of the sheet like `ID_Sheet_1`. But the API only accept an Int and not a String 
https://github.com/google/google-api-objectivec-client-for-rest/blob/883b23e77b63028ef41ace7148f9f308775f99de/Sources/GeneratedServices/Sheets/Public/GoogleAPIClientForREST/GTLRSheetsObjects.h#L8249

I tried to use 0, 1, 2 ... But only '0' works and this update only the first sheet.
If I have multiple sheet like : **ID_Sheet_0**, **ID_Sheet_1**, **ID_Sheet_2** .... I don't know how to access to the other sheet

Do you have any idea ?

Thanks

**Comment by thomasvl** [comment]
My guess would be you need to get the ID from a sheet when you first retrieve it, not directly hard code something.

Since this library support a hundred plus apis, we aren't really exports on all (any) of them, I'd suggest using the resources from the [Support section of the Sheet's API docs](https://developers.google.com/sheets/api/support).

**Comment by paul-lavoine** [comment]
Yes that was it. Thanks
