### ISSUE TITLE
 google_api_SWIFT_client_for_rest

### ISSUE THREAD

**Issue by Volodymyr-13** [google/google-api-objectivec-client-for-rest#596]
Since this is official repo from Google, where is the repo for Swift language?
I'm not saying that ObjC is dead, but this is already almost ancient language nowadays in **2023**

Time to update/keep up with new trends! 
- Swift only
- SwiftUI
- examples(Swift, SwiftUI)

**Comment by StevenEWright** [comment]
If you're having trouble using it for a swift project you might want to read:

https://github.com/google/google-api-objectivec-client-for-rest/blob/main/USING.md

**Comment by thomasvl** [comment]
This library works from Swift (and it used by server folks), so there hasn't been a strong push to rewrite things. It also use some things via the ObjC runtime to make smaller code than what a pure Swift implementation might generated.  There was a parallel project start with pure Swift bindings if you'd prefer: https://github.com/googleapis/google-api-swift-client
