### ISSUE TITLE
Swift Package manager include redundant modules

### ISSUE THREAD

**Issue by chienpm304** [google/google-api-objectivec-client-for-rest#607]
I got included all modules when import the Drive module using Xcode SPM.
<img width="384" alt="Screen Shot 2023-09-17 at 09 35 44" src="https://github.com/google/google-api-objectivec-client-for-rest/assets/37016896/81c71365-2be7-4cef-9e5d-24972488a08e">

**Comment by thomasvl** [comment]
I believe Xcode always shows everything in the package, but doesn't mean it builds/links everything, you should still be able to depend only on the explict target(s) you want.

**Comment by chienpm304** [comment]
I can feel it could be much lagging after import GoogleDriveAPI, I don't think only GoogleDriveAPI at that big too slow down the Xcode

**Comment by thomasvl** [comment]
That's likely feedback to file with Apple for Xcode. The way SwiftPM works with targets in a package.  Since SwiftPM maps a package to a repo, it's not like we can easily move to a individual package per service, as that would require a non trivial number of git repos be created/maintained.

**Comment by thomasvl** [comment]
Closing as there really isn't anything this project can do for this as it is just how Xcode's SPM integration work.  The slowness might also go away after Xcode has finished index things when GTLR get updated in your workspace.
