### ISSUE TITLE
iOS Swift - Trying to use the Gmail API but it's crashing

### ISSUE THREAD

**Issue by dannymout** [google/google-api-objectivec-client-for-rest#61]
For months, I've been trying to use the Gmail API. I've attempted multiple times to follow the guide on the [Gmail API Website](https://developers.google.com/gmail/api/quickstart/ios?ver=swift) with Swift. It worked until Apple released Swift 3, which made some changes to the language. So, now when I copy and paste the code provided on the Gmail API site, Xcode shows a whole bunch errors, all of which were fixable but simply click on the fix the error shows. So once I fix everything that Xcode tells me needs to be, I run the app. I'm able to sign in to my Google account, but once I give my app the permission, rather than then the WebView closing and the UITextView showing a list of the folders in my email, the app shows something that says, "Copy and Paste this code into the app." Then, it crashes with a SIGABRT error.

So the issue I'm having is that Google hasn't updated the code for Swift 3, and I'm not fluent in Obj-C, and Xcode doesn't fix the errors, rather something it's doing is crashing the app. Also, trying to use "Legacy Swift Version", in Build Settings also causes problems, now with the AppDelegate. Google doesn't seem to offer more documentation. Is there anyway I could at least use the API with Alamofire?

**Comment by thomasvl** [comment]
Thanks for the report, I've filed a bug against the team that maintains that site to have them update for Swift 3.

**Comment by dannymout** [comment]
@thomasvl Ok, thanks. I don't know if that would wok though, because I've clicked on "Send Feedback" and complained about this multiple times, and they've done nothing. The page was even updated after I've sent the feedback and nothing.
