### ISSUE TITLE
-[GTLRService requestUserAgent] blocks the calling thread in GTMFetcherApplicationIdentifier()

### ISSUE THREAD

**Issue by bhamiltoncx** [google/google-api-objectivec-client-for-rest#615]
By default, `-[GTLRService executeQuery:completionHandler:]` blocks the calling thread to invoke `GTMFetcherApplicationIdentifier()`:

https://github.com/google/google-api-objectivec-client-for-rest/blob/a91e1a0fad3740f42fa214cef9e60459ac9fd80a/Sources/Core/GTLRService.m#L290

That method is synchronized on a process-wide mutex:

https://github.com/google/gtm-session-fetcher/blob/ffb0463f5e57d250c101eca46fc9cb5a0035dc6c/Sources/Core/GTMSessionFetcher.m#L4811

This causes stalls, hangs, and watchdog terminations when `GTLRService` is invoked from the UI thread to asynchronously execute a query, since another thread can be busy reading all the data from disk / other services to calculate the User-Agent string.

Last year, I filed and fixed https://github.com/google/gtm-session-fetcher/issues/352 on the `GTMSessionFetcher` side to allow doing this work asynchronously. I enabled it by default in https://github.com/google/gtm-session-fetcher/pull/357 . We should make use of that in `GTLRService` as well.

**Comment by thomasvl** [comment]
Makes sense, did you want to look at doing a PR to add it?

**Comment by thomasvl** [comment]
> Yes, I'm thinking about which queue this async work needs to happen on. Should I use one of the existing queues in `GTLRService`? I'm not sure which one is appropriate.

The _callback queue_ feels wrong, it defaults to the _main queue_, and since folks generally will likely use it for where they want to update models, etc. it seems maybe a little wrong to slow things down to the point.

The _parse queue_ makes a little sense, in that it is where we do some of the internal overhead work, it is serial, so that could slow things down a little, but maybe that's not that bad?

**Comment by bhamiltoncx** [comment]
Can definitely use the parse queue — this shouldn't introduce additional latency, since the latency will either be on the calling thread or on the parse queue.

**Comment by Minhone1** [comment]
![FB_IMG_1708266277097](https://github.com/google/google-api-objectivec-client-for-rest/assets/161184683/2c7c4dd2-d8a2-4909-b07f-31bdc7b4e5f6)
