### ISSUE TITLE
how to create a shareable link in iOS

### ISSUE THREAD

**Issue by wangbourne** [google/google-api-objectivec-client-for-rest#64]
In web version, we can right click "get a shareable link" button to generate a share link. Is there a counterpart on iOS API?

**Comment by thomasvl** [comment]
This library supports a server google apis, you question is pretty general, so I'm not sure what you are actually asking about.

**Comment by wangbourne** [comment]
my question is quite straightforward,  and want to know some snippet codes to generate a shareable link in iOS App 

![image](https://cloud.githubusercontent.com/assets/2090084/20406251/4a5f5a36-ad58-11e6-80d1-55c7a2397e74.png)

**Comment by thomasvl** [comment]
It might be straight forward once everyone knows the context, but it still isn't clear. Is that a screen shot from within some part of the Drive UI?  Is it directly in Docs/Sheets/etc?  Or something else?
