### ISSUE TITLE
Crashed after using GTMAppAuth

### ISSUE THREAD

**Issue by zlstt** [google/google-api-objectivec-client-for-rest#67]
*** Terminating app due to uncaught exception 'Attempted to create a token refresh request from a token response with no refresh token.', reason: 'Attempted to create a token refresh request from a token response with no refresh token.'
When run the Drive Sample, it crashed by calling fetchFileList ([service executeQuery:query
                        completionHandler:^(GTLRServiceTicket *callbackTicket,
                                            GTLRDrive_FileList *fileList,
                                            NSError *callbackError) {  ) :

**Comment by thomasvl** [comment]
Looks like https://github.com/google/GTMAppAuth doesn't have an issues tab to directly report this. 

@WilliamDenniss - the error going to be coming from GTMAppAuth, any ideas?

**Comment by WilliamDenniss** [comment]
@thomasvl I've enabled the issues tab on GTMAppAuth now, but will address this issue here.

@zlstt I can't repro this, can you share some more detailed steps to reproduce?

Here's what I tried:

### Steps to Reproduce
1. Run the following commands:
```
git clone --recursive git@github.com:google/google-api-objectivec-client-for-rest.git
cd google-api-objectivec-client-for-rest/Examples/DriveSample/
open DriveSample.xcodeproj
```
2. From XCode proj, hit 'Run'
3. Visited https://console.developers.google.com/apis/credentials/?project=_ copied client id & secret into app.
4. Tapped sign-in, completed sign-in.
5. Tapped Get file list.

### Expected Results
View a list of files.

### Actual Results
Same as expected.

**Comment by WilliamDenniss** [comment]
Note: I had an unrelated issue which #68 fixes.

**Comment by WilliamDenniss** [comment]
@zlstt is your OAuth client registerd with type "Other" in https://console.developers.google.com/apis/credentials/?project=_ ? If you are using the "Web" type, it could cause this issue as Google's OAuth server will only issue a refresh token *once* to Web clients (unless you explicitly ask for a new one), which would result in GTMAppAuth not having any refresh tokens after the first time you authorize the app, and could cause this problem.

macOS is classified as "Other" during client registration, and that's what you need to use.

The reasons is the following: Google's OAuth server expectation is that there is only one instance of the Web client, therefore it should manage its refresh tokens and not forget them. Native clients (the "Other" type) don't have this limitation, as the user may have multiple installs, each with a different refresh token.

Incidently https://github.com/openid/AppAuth-iOS/pull/23 will allow GTMAppAuth to function without a refresh token for as long as the access token is valid – but without a refresh token the app would only authorize requests for an hour until the access token expires (Google access tokens expire after an hour), so you need to solve this issue regardless.

**Comment by zlstt** [comment]
Thanks, resolved! I registered as 'Web' type before.
