### ISSUE TITLE
Can't submit to App Store using this libaray

### ISSUE THREAD

**Issue by zlstt** [google/google-api-objectivec-client-for-rest#69]
My project has been disabled the BitCode, while submit to App Store, it resports
errors occurred in the app thinning process, and your app couldn’t be thinned. If your app contains bitcode, bitcode processing may have failed. Because of these errors, this build of your app will not be able to be submitted for review or placed on the App Store. For information that may help resolve this issue, see Tech Note 2432. 
The following solution does not help.
http://stackoverflow.com/questions/39390546/itunes-connect-errors-occurred-in-the-app-thinning-process-and-your-app-couldn/39484306#39484306

If I remove this lib, everything is OK. Please help

**Comment by thomasvl** [comment]
Are you using the Xcode projects checked in?  CocoaPods?  Integrating via sources?  From the sounds of things and the info you linked, it will depend on how you are integrating the library, if you are using the Xcode project checked in, you might need to tweak the projects settings as they suggest.

**Comment by zlstt** [comment]
I downloaded all the projects and build it as framework.  But this method can't submit to App Store.

Now I copy all the source code to my project, and it is OK. 
I can't find where the problem of projects settings

**Comment by tdestro** [comment]
Do you have public code we can look at? Are you using CocoaPods?

**Comment by zlstt** [comment]
No, I just download this project ( download Zip, not use CocoaPods), and build it.

**Comment by stevendev** [comment]
We got the same issue. App Store returns an app thinning error when we submit our app to app store. My submission goes fine as soon as I remove GLTR.framework.   
The bitcode is disabled in my project.

**Comment by zlstt** [comment]
copy all the source code to your project, and don't use it as lib, and it is OK

**Comment by stevendev** [comment]
This is not a good option. Google need fix it.

**Comment by stevendev** [comment]
I fixed it after 7 attempts. Below is what I did in project settings.
1. Change "Install Directory" to "$(LOCAL_LIBRARY_DIR)/Frameworks".
2. Change "Dynamic Library Install Base Name" to "@rpath".

**Comment by thomasvl** [comment]
I thought I looked at this once before, and that could still trip up if a developer was sharing the framework between an iOS app and an iOS extension (share/today/etc.), because the extension needs to reference it in the parent app?

**Comment by R4N** [comment]
@thomasvl 

I think number 2 from @stevendev's proposed adjustments to project settings would be useful.

From my usage, if I embed the GTLR framework within my main application and then link against it from a separate framework, it runs fine on simulator, but as soon as I try to run it on device the GTLR.framework isn't found with this type of message:

```
dyld: Library not loaded: @loader_path/Frameworks/GTLR.framework/GTLR
  Referenced from: ....
  Reason: image not found
```

Which is similar to #27 and #39 -- and the general solution there is that the GTLR framework wasn't added to Embedded Binaries.  Unfortunately it doesn't make sense to embed it again if you're linking against it in a separate framework (when it's already embedded in the main application).

I've also tried to adjust the Runpath search paths (of the separate framework) to every combination of @loader_path/@exectuable_path I could think that would make sense.

Setting the Dynamic Library Install Base Name to `@rpath` resolves this issue.  `@rpath` is also the default setting when creating a new framework.

I tried it out with an embedded appex (Safari Extension) also linking against the GTLR embedded binary of the main application and it seems to build fine on my end.

If you think this is an appropriate adjustment, I'd be happy to issue a PR, just lmk.

**Comment by thomasvl** [comment]
Sorry, was out the other week, so catching up now.  If you want to send in a PR that's fine, will take a look as I finish catching up on stuff.

**Comment by thomasvl** [comment]
I haven't cut a release with #186 - but can folks confirm the state of things on master fixes the issue for them?  If so, we can look at doing a release to provide folks a tag with this change.

**Comment by R4N** [comment]
Working well on my end.  Thanks!

**Comment by thomasvl** [comment]
Ok, will cut a release shortly to pick up this and other things that recently came in via PRs.
