### ISSUE TITLE
Add instalation steps for Cocoapods / Carthage

### ISSUE THREAD

**Issue by lferro9000** [google/google-api-objectivec-client-for-rest#7]
The readme misses some normal information regarding how to install the library with both CocoaPods and Carthage which are the major dependency managers used by iOS/Mac OS developers.

**Comment by thomasvl** [comment]
Currently we have that on the wiki: https://github.com/google/google-api-objectivec-client-for-rest/wiki/BuildingTheLibrary

I'll keep this open to look at moving more info or atleast some pointers.

**Comment by thomasvl** [comment]
Thanks again.  I added a note to the README pointing off the the wiki.

**Comment by fjaeger** [comment]
Any news on Carthage support? Would be awesome!
