### ISSUE TITLE
The request did not specify any iOS bundle ID

### ISSUE THREAD

**Issue by JonasGessner** [google/google-api-objectivec-client-for-rest#70]
An error saying "The request did not specify any iOS bundle ID. Please ensure that the client is sending it or use the API Console to update your key restrictions" appears whenever I try to make any request with an iOS API key that has bundle ID restrictions. I am not sending a custom user agent string and I double checked and made sure the user agent string really contains the bundle ID and it does.

I'm not sure if this is a problem on the client side (possibly wrong formatting of the user agent), or a server side issue. There used to be a bug on the server side, which absolutely no one at Google even remotely cared about: https://code.google.com/p/gdata-issues/issues/detail?id=5770 and while the error message here is different it could still be the same bug.
I don't understand how Google would have every bit of this feature implemented in the console for years and now they're even suggesting to use the feature, yet the actual check for the bundle ID always fails (which would essentially be one liner). Seeing how no one cared about that bug report from 2014 it seems pretty plausible though.

Could you clear this up? Is it a bug in this library or still on the server side?

**Comment by thomasvl** [comment]
What api is failing?  Can you get a [http log](https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic) to provide more info?

**Comment by thomasvl** [comment]
ps - there were some recent changing on the auth server side of things, so there is the possibility it is some interaction there that we haven't heard about yet.

**Comment by JonasGessner** [comment]
It's happening with the YouTube API. The API log doesn't really provide any infos, I'm doing the same requests that have always worked with non iOS API keys. Here are the request headers and response body:

```
Request headers:
  Accept: application/json
  Cache-Control: no-cache
  Content-Type: application/json; charset=utf-8
  User-Agent: <bundleID>/<appVersion> google-api-objc-client/3.0 iPhone/10.1 hw/sim (gzip)

Response body: (497 bytes)
{
  "error" : {
    "message" : "The request did not specify any iOS bundle ID. Please ensure that the client is sending it or use the API Console to update your key restrictions.",
    "errors" : [
      {
        "message" : "The request did not specify any iOS bundle ID. Please ensure that the client is sending it or use the API Console to update your key restrictions.",
        "reason" : "ipRefererBlocked",
        "domain" : "usageLimits",
        "extendedHelp" : "https:\/\/console.developers.google.com\/apis\/credentials?project=..."
      }
    ],
    "code" : 403
  }
}
```

**Comment by thomasvl** [comment]
@WilliamDenniss Is this fallout from the server side changes on auth?

**Comment by WilliamDenniss** [comment]
Not any OAuth related changes, as OAuth is unrelated to API keys.

**Comment by WilliamDenniss** [comment]
Can I suggest removing the Bundle ID restriction from your API Key in the console, applying the same workaround in the issue you linked?

**Comment by JonasGessner** [comment]
That's what you inevitably have to do to be able to use the API key at all. It's not really a workaround though, it's just completely avoiding the feature. I know you're not responsible for this, but it's such a let down by Google.

**Comment by ahmadtbox** [comment]
Hi Everyone , Can you please help me, I am also getting this error when using google custom search api to fetch images , please see this :  https://cloudup.com/cvcekW46S5e
I have restricted my Api-key for iOS, but when I remove this restriction, and set it to **None**, It only return 2 images.
What I am doing wrong ?

Any help will be greatly appreciated, Please help me to resolve this.

Thanks in advance...!

**Comment by thomasvl** [comment]
@ahmadtbox removing the API key should be fine.  Generally, please don't overload issues with multiple/different things, as it makes them harder to follow.  Customsearch seems to have a [num](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/Customsearch/GTLRCustomsearchQuery.h#L671) argument you could try raising, otherwise, I'd suggest the [Custom-Search Support area](https://developers.google.com/custom-search/docs/support) as that should be monitored by the teams that work on the server side and that will know the specific service better.
