### ISSUE TITLE
Where is the downloadUrl in V3?

### ISSUE THREAD

**Issue by stevendev** [google/google-api-objectivec-client-for-rest#73]
There is a GTLDriveFile.downloadUrl in V2. We use the downloadUrl to stream video from Google Drive to MPMoviePlayerController. However, we cannot find the regarding API in V3. Are there any alternative methods to stream videos?

**Comment by thomasvl** [comment]
Unfortunately those of us maintaining the ObjC library don't know the ins/outs of every api support.  The _GeneratedServices_ directory is just that, they are generated from documents the services vend.  We try to do samples for some of the apis, but they don't cover everything.  The [docs from this api](https://developers.google.com/youtube/v3/guides/implementation), talk about migration so you likely want to go through their info to see what they have, and failing that try their [Support info](https://developers.google.com/youtube/v3/support).

**Comment by stevendev** [comment]
OK, fixed. We use files.get with ?alt=media to replace downloadUrl.

https://developers.google.com/drive/v3/web/migration
The migration guide is helpful. Thanks for the help!

**Comment by thomasvl** [comment]
Good.  Np.
