### ISSUE TITLE
Update the client library to use GTMAppAuth instead of the GTMOAuth2 library

### ISSUE THREAD

**Issue by dsanghan** [google/google-api-objectivec-client-for-rest#74]
Since GTMOAuth2 is deprecated, is there a timeline for migrating to the newer GTMAppAuth libs?

**Comment by thomasvl** [comment]
Not sure what you are asking for this project.  This project doesn't directly depend on any auth, the `GTMSessionFetcher` provided a `@protocol` for and authorizer that can be set on the `Service` objects.  You can get a compatible object from `GTMAppAuth` already, and the code for this library "just works".  The Samples directory has been updated to use `GTMAppAuth` already.

**Comment by thomasvl** [comment]
PS - We still need to update some of the Wiki info that is talking about gtm-oauth2.

**Comment by dsanghan** [comment]
Ah ok. That's all I needed. Thanks!
