### ISSUE TITLE
how to get a valid token for REST API

### ISSUE THREAD

**Issue by wangbourne** [google/google-api-objectivec-client-for-rest#75]
REST APIs are related to token.I can get a token and persist it after signing in my Google Account via https://github.com/google/GTMAppAuth.
My question is how I can verify the token's validity later if I have signed in days/weeks ago  since I don't expect to sign in every time when I call REST APIs

Thanks

**Comment by wangbourne** [comment]
what does it mean : " If you are using reloading from the keychain as suggested and attaching an authorizer to your service, it should silently refresh the token based on server response and resend the query. ", are there any code snippets?

**Comment by thomasvl** [comment]
Just like the examples:

Load from the keychain at startup -

https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Examples/CalendarSample/CalendarSampleWindowController.m#L97-L100

When the initial sign in done, set the authorizer and save to the keychain:

https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Examples/CalendarSample/CalendarSampleWindowController.m#L990-L999

The rest happens within the library.

**Comment by wangbourne** [comment]
Yes, we can get authorisation from keychain. However, this does not mean the token within this authorisation is valid  not (I get the token via: _authorization.authState.lastTokenResponse.accessToken). 

So there must be a method to check the validity of token.  Does it make sense?

Thanks

**Comment by thomasvl** [comment]
Why do you directly need the token?  i.e. - You are asking on the GTLR project where you shouldn't directly need this, so I'm trying to figure out what you are doing to help out.

**Comment by wangbourne** [comment]
In my project, most of case, I can use Objective C SDK to achieve. For example, i can use GTLRDriveService to upload a file. However, I have to use couple REST APIs too since they are not included in the SDK. 

Take an example: _https://www.googleapis.com/drive/v3/files/%@/permissions_. I use HTTP post method. Following are some code snippets and you can find out I need token to assemble header:

```
NSString *urlStr = [NSString stringWithFormat:@"https://www.googleapis.com/drive/v3/files/%@/permissions",fileID];
    
    // 1
    NSURL *url = [NSURL URLWithString:urlStr];
    NSURLSessionConfiguration *config = [NSURLSessionConfiguration defaultSessionConfiguration];
    [config setHTTPAdditionalHeaders:@{@"Authorization":[NSString stringWithFormat:@"Bearer %@",_session.accessToken],
                                       @"Content-Type": @"application/json"}];
    NSURLSession *session = [NSURLSession sessionWithConfiguration:config];
    
    // 2
    NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url];
    request.HTTPMethod = @"POST";
    
    // 3.Create a JSON representation of the dictionary you will post to the web service.
    NSDictionary *dictionary = @{@"role": @"reader",@"type": @"anyone"};
    NSError *error = nil;
    NSData *data = [NSJSONSerialization dataWithJSONObject:dictionary
                                                   options:kNilOptions error:&error];
    [request setHTTPBody:data];
    
    // 3
    NSURLSessionDataTask *postDataTask = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
        
        if (!error) {
           //do some
            
        } else {
           //do others
            
        }
        
        
    }];
    
    [postDataTask resume];
```

**Comment by thomasvl** [comment]
From your code snippet, it sorta looks like you might actually want: https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/GeneratedServices/Drive/GTLRDriveQuery.h#L1036

As far as authorizing the request; don't try to set the headers directly; the authorizer on the service conforms to [GTMFetcherAuthorizationProtocol](https://github.com/google/gtm-session-fetcher/blob/master/Source/GTMSessionFetcher.h#L642), that has a [block based](https://github.com/google/gtm-session-fetcher/blob/master/Source/GTMSessionFetcher.h#L670-L671) and [selector based](https://github.com/google/gtm-session-fetcher/blob/master/Source/GTMSessionFetcher.h#L646-L648) calls to authorize a `NSMutableURLRequest`, either one will add the headers doing a token refresh as needed.

**Comment by wangbourne** [comment]
@thomasvl 
you are star and finally i figured out :)

Below is my code that works in my project for anyone who is interested

```
    GTLRDriveService *service = _session.driveService;
    GTLRDrive_Permission *permission = [GTLRDrive_Permission object];
    permission.role = @"reader";
    permission.type = @"anyone";
    
    GTLRDriveQuery_PermissionsCreate *query =
    [GTLRDriveQuery_PermissionsCreate queryWithObject:permission fileId:fileID];
    [service executeQuery:query
        completionHandler:^(GTLRServiceTicket *callbackTicket,
                            GTLRDrive_File *fileItem,
                            NSError *callbackError) {
            //do something here
        }];
```
