### ISSUE TITLE
Progress not working with MIME type "application/octet-stream"

### ISSUE THREAD

**Issue by tobihagemann** [google/google-api-objectivec-client-for-rest#78]
Downloading files of MIME type `application/octet-stream` and showing its progress doesn't seem to work. `totalBytesExpectedToWrite` is always `-1`. I'm working on an app for file encryption/decryption, that's why I'm almost exclusively working with files of this MIME type.

Here is one example: https://drive.google.com/open?id=0B3zSI_PrS4g5MFZjazM4Xzk1aDQ

It's an encrypted file, so you wouldn't see any content, but at least you could try and download it!

I'm not sure if I'm jumping to any conclusions too fast, because I had an almost identical case with the OneDrive SDK. The problem was that the file is being gzipped when downloading it. At least there was a [workaround](https://github.com/OneDrive/onedrive-sdk-ios/issues/7#issuecomment-140804425). Could there be a workaround here as well?

**Comment by thomasvl** [comment]
Do you have a code example of what isn't working?

**Comment by tobihagemann** [comment]
```objc
GTLRDriveService *driveService = [[GTLRDriveService alloc] init];
driveService.fetcherService.configurationBlock = ^(GTMSessionFetcher *fetcher, NSURLSessionConfiguration *configuration) {
  configuration.sharedContainerIdentifier = @"…";
};
GTLRDriveQuery_FilesGet *query = [GTLRDriveQuery_FilesGet queryForMediaWithFileId:identifier];
NSURLRequest *downloadRequest = [driveService requestForQuery:query];
GTMSessionFetcher *fetcher = [driveService.fetcherService fetcherWithRequest:downloadRequest];
fetcher.destinationFileURL = [NSURL fileURLWithPath:localPath];
fetcher.downloadProgressBlock = ^(int64_t bytesWritten, int64_t totalBytesWritten, int64_t totalBytesExpectedToWrite) {
  // totalBytesExpectedToWrite is always -1 for binary files, for other files it's having a "normal" value
};
[fetcher beginFetchWithCompletionHandler:^(NSData *data, NSError *error) {
  // ...
}];
```

The `fetcher.downloadProgressBlock` always has a `totalBytesExpectedToWrite` of `-1` for binary files. Btw, the same code works for other file types. So I'm guessing it has to do something with `application/octet-stream` specifically.

**Comment by sergiocampama** [comment]
This is the same issue that you had with OneDrive. The proposed solution in that issue is to add the "Accept-Encoding" header with value "gzip;q=0". In order to do that with GTLR, you can add `driveService.additionalHTTPHeaders = @{@"Accept-Encoding": @"gzip;q=0"};` to your code. I tested this locally and I stopped getting -1 for `totalBytesExpectedToWrite`.

**Comment by tobihagemann** [comment]
I guess I should've just tried the same solution. 😅 Thank you for the confirmation! 👍
