### ISSUE TITLE
git clone --recursive submodules to build service generator

### ISSUE THREAD

**Issue by nathan2day** [google/google-api-objectivec-client-for-rest#80]
I suggest the readme is updated to indicate that this repository contains submodules.  A quick way to clone with submodules is:

git clone --recursive https://github.com/google/google-api-objectivec-client-for-rest.git

The submodules are required to build the service generator.

**Comment by thomasvl** [comment]
fyi - It is mentioned on the [wiki for the ServiceGenerator](https://github.com/google/google-api-objectivec-client-for-rest/wiki/ServiceGenerator).

The readme currently is trying to point to other docs to avoid duplicating info, any suggestions on what would help?

**Comment by nathan2day** [comment]
okay thanks, I was working through the following guide:

https://cloud.google.com/appengine/docs/java/endpoints/calling-from-ios

when step 3 resulted in a build error, i read the git readme.  I've also suggested the appengine doc is updated, didn't get as far as the wiki for the service generator, as I then starting to explore why the submodules folder were empty and came across the --recursive option - it occurred that if it takes a while for the appengine doc to get corrected, others would follow the similar path to me and so having a mention in the readme would be helpful to others

**Comment by thomasvl** [comment]
Thanks, I filed a internal bug against that page to get it updated.  It looks like it also might need an update to use the REST discovery document (not RPC).  So I filed one for that also.
