### ISSUE TITLE
How to use this new library with <Google/SignIn.h>

### ISSUE THREAD

**Issue by scinfu** [google/google-api-objectivec-client-for-rest#84]
Hi,
How this new library work with <Google/SignIn.h>.
I can login whit GIDSignIn giving the scope @"https://www.googleapis.com/auth/drive" but when i use GTLRDriveService to fetch files it give me i do not have permissions .

What i mistake?

**Comment by amarzulli** [comment]
Hello
Appears you need to wait to allow Google Signin to authenticate before calling any methods that use the authentication.  I used `[self performSelector:@selector(Method) withObject:nil afterDelay:3.0 ];` to delay my code for 3 seconds after calling `[[GIDSignIn sharedInstance] signIn];` and this worked for me.

**Comment by scinfu** [comment]
Tried but do not work , i think i need set `GTMAppAuthFetcherAuthorization` to my `GTLRDriveService` but i do not know how .
Here is mi code .

Init

```
NSError* configureError;
 _downloads = [NSMutableArray array];
[[GGLContext sharedInstance] configureWithError: &configureError];
NSAssert(!configureError, @"Error configuring Google services: %@", configureError);
NSString *driveScope = @"https://www.googleapis.com/auth/drive";
NSArray *currentScopes = [GIDSignIn sharedInstance].scopes;
[GIDSignIn sharedInstance].scopes = [currentScopes arrayByAddingObject:driveScope];
[GIDSignIn sharedInstance].delegate = self;
[GIDSignIn sharedInstance].uiDelegate = self;
[[GIDSignIn sharedInstance]signInSilently];
```
GTLRDriveService
```
- (GTLRDriveService *)driveService {
    static GTLRDriveService *service = nil;
    if (!service) {
        service = [[GTLRDriveService alloc] init];
        service.shouldFetchNextPages = YES;
        service.retryEnabled = YES;
        service.APIKey = @"My_APIKey";
    }
    return service;
}
```

After login 

```
- (void)fetchFileList:(id)sender {
  GTLRDriveService *service = self.driveService;
  GTLRDriveQuery_FilesList *query = [GTLRDriveQuery_FilesList query];
  query.fields = @"kind,nextPageToken,files(mimeType,id,kind,name,webViewLink,thumbnailLink,trashed)";
  [service executeQuery:query
      completionHandler:^(GTLRServiceTicket *callbackTicket,
                          GTLRDrive_FileList *fileList,
                          NSError *error) {
    if (error) {
        [self logMessage:@"Error: %@", error];
    } else {
      for (GTLRDrive_File *item in fileList) {
        [self logMessage:@"Item: %@ (%@)", item.name, item.webViewLink];
      }
    }
  }];
}
```

And this is the error :

```Error Domain=com.google.GTLRErrorObjectDomain Code=403 "The user does not have sufficient permissions for this file." UserInfo={GTLRStructuredError=GTLRErrorObject 0x600000650920: {message:"The user does not have sufficient permissions for this file." errors:[1] code:403}, NSLocalizedDescription=The user does not have sufficient permissions for this file.}```

**Comment by scinfu** [comment]
this is the solution:

`[service setAuthorizer:[GIDSignIn sharedInstance].currentUser.authentication.fetcherAuthorizer];`

**Comment by aaroncrespo** [comment]
Wouldn't this be useful to add to some documentation somewhere? @thomasvl I didn't know you could use google sign in for this project. I thought Google Auth was required.

**Comment by thomasvl** [comment]
https://github.com/google/google-api-objectivec-client-for-rest/wiki#authentication-and-authorization has a small note about it.

**Comment by aaroncrespo** [comment]
Oh neat sorry. Is there guidance on which is the best approach? or are they different flavors of the same thing. (client config look to be exactly the same)

**Comment by thomasvl** [comment]
Both work, I've been pushing on some folks within Google to get a better story around this question.  For the moment, the main difference I see is one is all source, the other is a binary release, and that can lend itself to differences in using them.  Last time I looked, the SignIn one didn't cover tvOS (or watchOS).
