### ISSUE TITLE
How to Get And Set Header cookie using GoogleEndpoint (GTLRServiceTicket)

### ISSUE THREAD

**Issue by ominfowaveIOS** [google/google-api-objectivec-client-for-rest#86]
i have use GoogleEndPoint GTLRCore Library, user login not get cookie in GoogleEndPoint & How to set Header cookie GoogleEndPoint API

Note : AFHTTPRequestOperation *operation is working fine
NSDictionary *headers = operation.response.allHeaderFields;

**Comment by thomasvl** [comment]
This library doesn't use AFHTTPRequestOperation, so I'm a little confused by the reference.

The base GTLRQuery class exposed extra headers to add: https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Objects/GTLRQuery.h#L116

For the response, the completion handler gets the the ticket (GTLRServiceTicket), that exposes the `objectFetcher` which has a `responseHeaders` property.

**Comment by lmgagne** [comment]
I believe what this person is asking is how to send session cookie to google endpoints. Any idea?

**Comment by thomasvl** [comment]
The mentioned api on the query will let you add a cookie header.

**Comment by lmgagne** [comment]
would you have an example on how to do this?

**Comment by thomasvl** [comment]
I'm not sure the details for the EndPoints, but setting HTTP headers is pretty simple.  On the query just set the `additionalHTTPHeaders` property like: https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Tests/GTLRServiceTest.m#L341-L342.  If the value should be the same on all queries, you can set it directly on the, here's an example of that: https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Tools/ServiceGenerator/SGMain.m#L918

**Comment by thomasvl** [comment]
If the session cookie reference is for authentication, then you likely should be using OAuth2 instead and the [built in authorization support](https://github.com/google/google-api-objectivec-client-for-rest/wiki#authentication-and-authorization) should work.

**Comment by thomasvl** [comment]
Closing this out since there doesn't seem to be follow up.
