### ISSUE TITLE
Are iOS app extensions actually supported?

### ISSUE THREAD

**Issue by tererecool** [google/google-api-objectivec-client-for-rest#87]
We were intensively trying to make the code, that already works in the app itself, work in our app extension (document provider) without any luck. With the dropbox SDK it was not a problem, do you actually support app extensions? I could not find any example/documentation specific for app extensions.

**Comment by thomasvl** [comment]
Can you expand on what problems you are seeing?  There shouldn't be anything directly in GTLR that has issues with iOS extensions, the gtm-session-fetcher can be a little more tricky to use because of the support it has for background tasks to ensure operations complete when the user leaves the app.

**Comment by thomasvl** [comment]
Scratch that, I'm guessing you are hitting the background task support within GTLR.  Sorry, I've been looking at the one in SessionFetcher lately and was focused on that.

Yes, this code can be used (via the defines) an in extension, but CocoaPods doesn't make it overly easy.  I think some of the logic done in https://github.com/google/gtm-session-fetcher/pull/70 could be raised to this level to help simplify things.  We'll try to get some time to look at it or someone else can look and send in a PR for it.

**Comment by thomasvl** [comment]
The v1.2.1 included the change that should have made working with extensions much simpler.  There is still a preprocessor define to strip the support, but without doing that, there are no direct calls to `+[UIApplication sharedApplication]`, and runtime checks are done instead.
