### ISSUE TITLE
Linking issue using generated services and cocoapods

### ISSUE THREAD

**Issue by redi-wassere** [google/google-api-objectivec-client-for-rest#88]
All in the name of CI (through bitbuckets) I upgraded my cloud endpoints server to use the new supported gradle plugin, which sent me down quite the rabbit hole. I was using cloud endpoints 1.0 and had to upgrade to 2.0. This took away support for RPC via iOS, so I had to upgrade to using this,  newer library in my iOS app and GTLR from GTL. 

I am generating services and objects using the service generator against my endpoints project. Now when trying to compile and link Im getting lots of errors like the following:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GTLRServUsApiQuery_PaymentsDeletePaymentMethod", referenced from:
      objc-class-ref in CreditCardFormV.o
  "_OBJC_CLASS_$_GTLRServUsApi_UploadResponseDTO", referenced from:
      objc-class-ref in ProfileVC.o
  "_OBJC_CLASS_$_GTLRServUsApiQuery_UsersUploadUrl", referenced from:
      objc-class-ref in ProfileVC.o
```

Lots of searching hasnt found anything that works to solve this for me. Any help would be highly appreciated.

**Comment by thomasvl** [comment]
Without seeing your setup it is sorta hard to know what's failing, but given you are missing the Query classes and atleast one object class, it sounds like you aren't actually linking in the generated code.

**Comment by redi-wassere** [comment]
This was solved by removing the directory containing the .m and .h files and re-adding them to xcode as a new Group. I tried messing with every build setting that made any sense, but in the end, bridging head was correct and the build settings were as well.
