### ISSUE TITLE
The operation couldn’t be completed. (com.google.HTTPStatus error 403.)

### ISSUE THREAD

**Issue by sourov2008** [google/google-api-objectivec-client-for-rest#91]
error: The operation couldn’t be completed. (com.google.HTTPStatus error 403.)

I am trying to download from google drive file in iOS and getting error in the following

```
GTLServiceDrive* googleDriveService = [[GTLServiceDrive alloc] init];

NSString *urlTest = [NSString stringWithFormat:@"https://www.googleapis.com/drive/v3/files/%@?alt=media",itemIdentifier[indexPath.row]];
GTMSessionFetcher *fetcherTest = [googleDriveService.fetcherService fetcherWithURLString:urlTest];
[fetcherTest beginFetchWithCompletionHandler:^(NSData *data, NSError *error) {
    if (error == nil) {
        NSLog(@"Retrieved file content");
        NSLog(@"File size is : %.2f MB",(float)data.length/1024.0f/1024.0f);
        // Do something with data
    } else {
        NSLog(@"error: %@", [error localizedDescription]);
    }
}];
```

**Comment by thomasvl** [comment]
There really isn't enough information here to offer much help on.  The library has built in logging you can use: https://github.com/google/google-api-objectivec-client-for-rest/wiki#logging-http-server-traffic that might help shed some details.

 Some file types have to be exported vs. downloaded, so it could be that; the Drive example has a passing reference to this: https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Examples/DriveSample/DriveSampleWindowController.m#L246-L254.  The authoritative answer will be in the Drive docs themselves.

**Comment by sourov2008** [comment]
Yes I have checked pdf or docs issues . But still there is same problme

**Comment by thomasvl** [comment]
You still haven't provided much more to try to help.  My only other guess is going to be something around authorization given the 403 failure.  But if the query to get the file list worked, I would have though you had the authorizer set on the driveService and hence the fetcherService within it; but that would be something to double check.  The mentioned http logs would help tell if the request has authorization.

**Comment by braazzyx** [comment]
It’s not letting me comment on YouTube videos

**Comment by braazzyx** [comment]
And that’s messing up my money
