### ISSUE TITLE
generating API - problem on double type 

### ISSUE THREAD

**Issue by dounaka** [google/google-api-objectivec-client-for-rest#93]
when generating the API, I have this issue for the double type in Java 
"found a type/format pair of 'number/(null)', and don't how to map that to Objective-C"

it occurs only for double type

any idea ?

thank you

**Comment by thomasvl** [comment]
This came up once before (#85), do you have a doc that you can share? The discovery docs for [type and format](https://developers.google.com/discovery/v1/type-format) indicate that _number_ for `type` should always have a `format` also.  So it would be nice to figure out if there is an issue server side.

**Comment by dounaka** [comment]
I have the same problem for Android (generating client lib) 
On this simple class 
public class GeoPoint implements Serializable {
    public static final int EARTH_RADIUS = 6378;
    private static final long serialVersionUID = 1L;
    public double lat, lng;
}

the model generated is 
public final class GeoPoint extends com.google.api.client.json.GenericJson {
  /**  The value may be {@code null}.*/
  @com.google.api.client.util.Key
  private Number lat;

  /** The value may be {@code null}. */
  @com.google.api.client.util.Key
  private Number latitude;
...
}

During clientLib generation (iOS + Android) 
double, Double are converted to Number 

I hope it helps

**Comment by thomasvl** [comment]
By "same problem on Android" you mean something errors out there also?

I've opened an internal bug against against the discovery generation since spec says the `format` is required.

**Comment by dounaka** [comment]
yes, because both are during on a double field generation/convertion

here is the discovery file for GeoPoint 
 "GeoPoint": {
   "id": "GeoPoint",
   "properties": {
    "lat": {
     "type": "number"
    },
    "latitude": {
     "type": "number"
    },
    "lng": {
     "type": "number"
    },
    "longitude": {
     "type": "number"
    }
   },

**Comment by dounaka** [comment]
i created 4 dummy methods 
    public Float getTestFloatClass() {  return 1.2f; }
    public float getTestFloat() { return 1.2f;}
    public Double getTestDoubleClass() {return 1.2;}
    public double getTestDouble() {return 1.2; }

and the Json is not the same for double & float

"testDouble": {
     "type": "number"
    },
    "testDoubleClass": {
     "type": "number"
    },
    "testFloat": {
     "format": "float",
     "type": "number"
    },
    "testFloatClass": {
     "format": "float",
     "type": "number"
    }
   },

**Comment by thomasvl** [comment]
Thanks, I've relayed this along to the internal bug.  For now you can likely work around it by editing the discovery document generated to add the missing _"format": "double"_ for those fields.

**Comment by dounaka** [comment]
same for a the java type 'short', format is missing

**Comment by thomasvl** [comment]
What guide/tools are you using to generate your api doc?  Just want to confirm I'm looking in the right folks server side.

**Comment by dounaka** [comment]
I used this doc 
https://cloud.google.com/appengine/docs/standard/java/endpoints/migrating
https://cloud.google.com/endpoints/docs/frameworks/java/generate-client-libraries-android
and I generated the discovery file with gradle task in Android Studio

I cannot retest I rollback to endpoints framework 1.0

**Comment by thomasvl** [comment]
fyi - https://github.com/cloudendpoints/endpoints-java/pull/62

**Comment by thomasvl** [comment]
Have you had a chance to see if that update on cloudendpoints fixes this?

**Comment by dounaka** [comment]
No, I did a rollback to the version 1 - we will go on production soon, we
schedule the migration for next release

thank you




Solutions TI - Web J2EE Android

Karim Dounas

514-512-6678
kdounas@gmail.com

**Comment by thomasvl** [comment]
Closing this out since the bug was in another project and it should be fixed now.
