### ISSUE TITLE
how can i identify the case of "insufficient space"?

### ISSUE THREAD

**Issue by wangbourne** [google/google-api-objectivec-client-for-rest#94]
I can see kinds of error codes [here](https://developers.google.com/drive/v3/web/handle-errors), but there's no insufficient space related. Is there anyone know and how to identify when this happens? I think there must be an error code or something related to this.

**Comment by thomasvl** [comment]
That's one the server teams will know as it isn't client specific.  You'll probably want to try their [Support Info](https://developers.google.com/drive/v3/web/support) for where to task where someone server side is more likely to see the question to answer.

**Comment by thomasvl** [comment]
Closing this out since there doesn't seem to be follow up.
