### ISSUE TITLE
GTLR executeQuery in background fetch mode is not working

### ISSUE THREAD

**Issue by nitinkolala** [google/google-api-objectivec-client-for-rest#95]
Tried to fetch latest calendar events in iOS Background Fetch mode using below 2 methods,

1. service.executeQuery(<#T##query: GTLRQueryProtocol##GTLRQueryProtocol#>, delegate: <#T##Any?#>, didFinish: <#T##Selector?#>)
 2. service.executeQuery(<#T##query: GTLRQueryProtocol##GTLRQueryProtocol#>, completionHandler: <#T##GTLRServiceCompletionHandler?##GTLRServiceCompletionHandler?##(GTLRServiceTicket, Any?, Error?) -> Void#>)

But once excute query is executed then neither delegate nor completion handler is getting called. same code is working fine in foreground mode. I have enabled iOS background fetch mode capability for my main project. After executeQuery i see below logs,

[] nw_socket_get_input_frames recvmsg(fd 7, 1024 bytes): [57] Socket is not connected
[] nw_socket_get_input_frames recvmsg(fd 27, 1024 bytes): [57] Socket is not connected
[] nw_endpoint_handler_add_write_request [8.1 216.58.199.138:443 failed socket-flow (satisfied)] cannot accept write requests
[] __tcp_connection_write_eof_block_invoke Write close callback received error: [22] Invalid argument

How can we make GTLR Query to work in "Background Fetch" mode?

**Comment by thomasvl** [comment]
What do you mean by "Background Fetch" mode?  Are you referring to `useBackgroundSession` on `GTLRUploadParameters`?

**Comment by nitinkolala** [comment]
I mean if my iOS application is in background. In order to fetch latest google calendar events when app is in background mode, i enabled xcode-> Target -> capabilities->Background Modes->Background Fetch mode is enabled. Attached screen shot for the same
<img width="971" alt="screen shot 2017-03-02 at 5 03 10 pm" src="https://cloud.githubusercontent.com/assets/7093171/23505704/d02dfab4-ff6a-11e6-9462-1c30ea4e985b.png">

**Comment by thomasvl** [comment]
That's for a full background `NSURLSession` support.  Those are supported for media uploads (as mentioned in the headers).  The OS does those out of process, so they don't really make as much sense for normal queries, and aren't supported there.

If you start a request and the backgroundTask support is enabled in this library and the SessionFetcher library; a background task will be used to try to ensure you get the result of the api request.

**Comment by cashmash** [comment]
@thomasvl 
Hi and first of all thanks.

Are you refering to `shouldFetchInBackground`?

i.e.:
```
let calService = GTLServiceCalendar()
calService.authorizer = authorization
calService.shouldFetchInBackground = true
```

**Comment by thomasvl** [comment]
@cashmash GTL is [being phased out](https://github.com/google/google-api-objectivec-client#warning-deprecation-notice) in favor of GTLR.  GTLR is the project here that you commented on. On GTLR, as long as you aren't compiling GTLR with `GTM_BACKGROUND_TASK_FETCHING` defined to zero, the background support automatically happens.
