### ISSUE TITLE
Get url from query

### ISSUE THREAD

**Issue by mgatelabs** [google/google-api-objectivec-client-for-rest#97]
I just did some hacking into the code and figured out that sometimes I need the query URL + access_token in order to stream video content to my iOS device.  It would be handy, if the service method **URLFromQueryObject: usePartialPaths: includeServiceURLQueryParams:** was made public and could also have an extra option to append the current access_token

**Comment by thomasvl** [comment]
[requestForQuery](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Source/Objects/GTLRService.h#L361) will do a bunch of the work and you can get the URL back out.

**Comment by thomasvl** [comment]
Closing this out since there doesn't seem to be follow up.
